### ISSUE TITLE
support for minimum/maximum dates

### ISSUE THREAD

**Issue by monikasynowiec** [wojtekmaj/react-calendar#1]
Could you please add support for minumum and maximum dates, so that the calendar will be blocked when I try to navigate to dates beyond allowed range?

**Comment by wojtekmaj** [comment]
Hey @monikasynowiec, just added support for `minDate` and `maxDate` parameters. Thanks for suggestion!

**Comment by caub** [comment]
@wojtekmaj Does it support something like `excludedDates` in react-datepicker https://reactdatepicker.com/#example-exclude-dates or  similarly `disabledDays` in react-day-picker https://react-day-picker.js.org/examples/disabled-weekends?

Best

**Comment by wojtekmaj** [comment]
Check tileDisabled and please don't dig up 4 year old tickets with unrelated questions.
