### ISSUE TITLE
Default CSS not loaded when using CSS modules

### ISSUE THREAD

**Issue by myasul** [wojtekmaj/react-calendar#100]
<img width="460" alt="screen shot 2018-08-07 at 10 50 25 am" src="https://user-images.githubusercontent.com/25900564/43751549-eab3a6e8-9a2f-11e8-9983-b465d60d09ef.png">

Hi,
I just wanted to ask if I'm doing it right. Whenever I add the Calendar component in my react project the default styling is not being applied.

I'm using it like this. Can you advise what I'm doing wrong? Thank you!
``` javascript
import React from 'react';
import Calendar from 'react-calendar';

import classes from './Filter.css';

const filter = (props) => (
    <div className={classes.Filter}>
        <Calendar />
    </div>
);
```

Note: I also ejected my CRA and enabled CSS modules

**Comment by wojtekmaj** [comment]
Can I see your Webpack config?

**Comment by myasul** [comment]
Hi!

This a snippet of my config.
``` javascript
                    {
                        test: /\.css$/,
                        use: [
                            require.resolve('style-loader'),
                            {
                                loader: require.resolve('css-loader'),
                                options: {
                                    importLoaders: 1,
                                    modules: true,
                                    localIdentName: '[name]__[local]__[hash:base64:5]'
                                },
                            },
                            {
                                loader: require.resolve('postcss-loader'),
                                options: {
                                    // Necessary for external CSS imports to work
                                    // https://github.com/facebookincubator/create-react-app/issues/2677
                                    ident: 'postcss',
                                    plugins: () => [
                                        require('postcss-flexbugs-fixes'),
                                        autoprefixer({
                                            browsers: [
                                            '>1%',
                                                'last 4 versions',
                                                'Firefox ESR',
                                                'not ie < 9', // React doesn't support IE8 anyway
                                            ],
                                            flexbox: 'no-2009',
                                        }),
                                    ],
                                },
                            },
                        ],
                    },
```

When I tried disabling the css modules it worked. Is there a way to make it work with css modules enabled? Thank you!

**Comment by spnv** [comment]
++

**Comment by gman666** [comment]
I suggest copying the stylesheet from dist/Calendar.css into your own project, and then customising from there.

As you appear to be using css-loader, with modules: true, everything is local scope by default. To style child selectors, you will then need to export them as global, e.g. 

.reactCalendar :global {
 ... paste all the Calendar.css styles here
}

You can then include it in your jsx with:

<Calendar className={style.reactCalendar} value={new Date()} />

Working well for me...

**Comment by jfcali** [comment]
I found a solution using custom rules in webpack. 

I first declared a rule where every '.css' file loaded directly from 'node_modules' does not use modules, like so:
```
          {
            test: /\.css$/,
            include: /node_modules/,
            use: [
              'style-loader',
              {
                loader: 'css-loader',
                options: {
                  modules: false
                }
              }
            ]
          },
```
Then I added a rule which allows React to import a flagged file which does not use css modules as well, in order to override styles, like so:

```

          {
            test: /\.css$/,
            resourceQuery: /override/,
            use: [
              'style-loader',
              {
                loader: 'css-loader',
                options: {
                  modules: false
                }
              }
            ]
          },
```

So wherever you are using the Picker, you can do something like this:
```
import DateRangePicker from '@wojtekmaj/react-daterange-picker'; // includes original CSS - no conflict with modules
import './custom.css?override'; // includes your custom CSS
```

**A VERY important note**

Newer React apps (using `create-react-app` v2.x) come with a pre-established rule that works similar, although it's the other way round:
```
          // Adds support for CSS Modules (https://github.com/css-modules/css-modules)
          // using the extension .module.css
          {
            test: cssModuleRegex,
            use: getStyleLoaders({
              importLoaders: 1,
              modules: true,
              getLocalIdent: getCSSModuleLocalIdent,
            }),
          },
```
This allows CSS files to be the default and by adding a custom extension, Webpack can differentiate which files should be treated as a module. Here is the [changelog](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#detailed-changelog).

Hope this helps!

**Comment by harry100** [comment]
Use both style-loader and css-loader in the config.
{
            test: /\.css$/,
            use: [
              { loader: "style-loader" },
              { loader: "css-loader" },
        ]
}
This solved the issue for me
