### ISSUE TITLE
Please help me testing the next release!

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#102]
Hi!
Upcoming React-Calendar v2.17.0 will introduce several improvements, most importantly support for Arabic and Hebrew calendar.

**If you are a person coming from any country using locale listed below** (mostly: Israel, Brazil, Middle-eastern countries, South American countries), **please kindly test the newest release, if the calendar with your `locale` looks right to you.** 

You can comment with your feedback below and/or use 👍 👎 reactions. **Thank you!**

Current pre-release has version number `2.17.0-beta` and is published on npm/yarn under `next` tag. If you don't have a project to experiment on, you can test how the calendar would look like on my test suite:

http://projects.wojtekmaj.pl/react-calendar/test

The following locales will have US-style calendar applied (Sunday first, Sat-Sun weekend):

* es-AR
* es-BO
* es-CL
* es-CO
* es-CR
* es-DO
* es-EC
* es-GT
* es-HN
* es-MX
* es-NI
* es-PA
* es-PE
* es-PR
* es-SV
* es-VE
* pt-BR

The following locales will have Arabic style calendar applied (Saturday first, Fri-Sat weekend):

* ar
* ar-AE
* ar-BH
* ar-DZ
* ar-EG
* ar-IQ
* ar-JO
* ar-KW
* ar-LY
* ar-OM
* ar-QA
* ar-SA
* ar-SD
* ar-SY
* ar-YE
* dv
* dv-MV
* ps
* ps-AR

The following locales will have Hebrew calendar applied (Sunday first, Fri-Sat weekend):

* he
* he-IL

**Comment by itayronen** [comment]
Tested "he-IL" and it worked 👍 

In our project, we are using react-date-picker that uses this package.
We will wait for the update to get there.

Thank you :)

**Comment by wojtekmaj** [comment]
@itayronen Thank you for your input. It won't be long until the update gets to react-date-picker, as I'm the author of them both :) I have issues displaying the calendar properly for Brazilian Portugese on older iPhones, but once that gets resolved, which I assume will happen today, I can go forward with the release.

**Comment by rgaino** [comment]
Hi @wojtekmaj , I am just starting to use the calendar today, literally just ran npm install, but my app is in Brazilian Portuguese so if you need anything let me know please.

**Comment by wojtekmaj** [comment]
Hey @rgaino, basically any of your device that has Brazilian Portugese set as the main language should show the calendar in Portugese and also show Sunday as the first day of the week.

If anything's wrong, I'd appreciate if you could open [this link](http://projects.wojtekmaj.pl/react-calendar/test/locale.html) on the same device & browser you have issues with, and copy & paste the results here.

**Comment by rgaino** [comment]
@wojtekmaj what do you consider an older iPhone? The oldest I have access to is a 6s.

**Comment by wojtekmaj** [comment]
Hmmm, not sure. I think 6s would do. I got this screenshot from my friend from Brazil and it doesn't look like the proper calendar layout kicked in.

![received_268579777076930](https://user-images.githubusercontent.com/5426427/44204798-7958fd00-a154-11e8-9415-52ec92fc2930.jpeg)

**Comment by rgaino** [comment]
What is wrong with it? In Brazil the first day of the week is actually Monday, it's actually a norm from the Brazilian Association of Technical Norms (ABNT). But it's not uncommon at all to see calendars with Sunday as first week, people are really used to both. But officially, this one looks good to me.

**Comment by wojtekmaj** [comment]
Ah! Okay, thank you for the insight. I guess nothing stops us from a release now :)

**Comment by hlolli** [comment]
is-IS isn't working
