### ISSUE TITLE
React-calendar Server Side Error. (Calendar.css in entry.js)

### ISSUE THREAD

**Issue by wesias7** [wojtekmaj/react-calendar#108]
When "Server Side Rendering", it is not loaded due to the "Calendar.cs" file in "entry.js".

And I'm going to do this. However, it requires patches.

**if(typeof window === 'object' && window){ require('./Calendar.css'); }**

The message below shows my error.

**(function (exports, require, module, __filename, __dirname) { .react-calendar {**
**SyntaxError: Unexpected token .
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)**

**Comment by wesias7** [comment]
Dear friends who were worried like me,
Let me use the feedback I've been looking for in three days.

I tried to use "react-calendar" for "redux-ssr." By the way, there is an error in the "Server Webpack" setting.

First
To "npm -g install webpack@3.10.0 webpack-dev-server@2.3.0"
I reinstalled "webpack env".

lastly
Added through "npm install --save-dev null-loader style-loader@0.18.1 css-loader@0.28.3".
I modified the file "webpack.config.js".

`
const base = pos => group([
  setOutput({
    filename: '[name].js',
    path: outputPath,
    publicPath,
  }),
  defineConstants({
    'process.env.NODE_ENV': process.env.NODE_ENV,
    'process.env.PUBLIC_PATH': publicPath.replace(/\/$/, ''),
  }),
  addPlugins([
    new webpack.ProgressPlugin(),
  ]),
  happypack([
    babel(),
  ]),
  **assets(pos),**
  resolveModules(sourceDir),

  env('development', [
    setOutput({
      publicPath: devDomain,
    }),
  ]),
])

const server = createConfig([
  **base('server'),**
  entryPoint({ server: serverEntryPath }),
  setOutput({
    filename: '../[name].js',
    libraryTarget: 'commonjs2',
  }),
  addPlugins([
    new webpack.BannerPlugin({
      banner: 'global.assets = require("./assets.json");',
      raw: true,
    }),
  ]),
  () => ({
    target: 'node',
    externals: [nodeExternals()],
    stats: 'errors-only',
  }),

  env('development', [
    serverSourceMap(),
    addPlugins([
      new SpawnPlugin('npm', ['start']),
    ]),
    () => ({
      watch: true,
    }),
  ]),

])

const client = createConfig([
  **base('client'),**
  entryPoint({ client: clientEntryPath }),
  addPlugins([
    new AssetsByTypePlugin({ path: assetsPath }),
    new ChildConfigPlugin(server),
  ]),

  env('development', [
    devServer({
      contentBase: 'public',
      stats: 'errors-only',
      historyApiFallback: { index: publicPath },
      headers: { 'Access-Control-Allow-Origin': '*' },
      host,
      port,
    }),
    sourceMaps(),
    addPlugins([
      new webpack.NamedModulesPlugin(),
    ]),
  ]),

  env('production', [
    splitVendor(),
    addPlugins([
      new webpack.optimize.UglifyJsPlugin({ compress: { warnings: false } }),
    ]),
  ]),

])`

1) If you look at it, you've added an instrument called "pos." Separate this server or client.
2) We added the "base function ['server or client']" and it is forwarded to an asset().

**Comment by wojtekmaj** [comment]
This is not a valid patch. On SSR, there should be CSS loaded as well. Otherwise you will get a flash of unstyled content or the page will be broken if the user disables JS.

You should configure your Webpack properly to load CSS files.

**Comment by wesias7** [comment]
thanks for your anwser!!

**Comment by ffasolin** [comment]
To anyone who wants to import the calendar with style and is still having issues, this is what you need to do: [3094](https://github.com/facebook/jest/issues/3094)
