### ISSUE TITLE
Add default styles for today's date

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#112]
@lostpebble in wojtekmaj/react-datetime-picker#30:

> Hi there,
> 
> I've just started using this and I notice that there is a class set on the calendar on the today's date tile (`react-calendar__tile--now`), but there are no styles applied to it which differentiate it from the others in any way.
> 
> Is this intentional? Would be nice to have the default styles include styling for that too. Maybe a very light grey, something subtle (when it is not the currently selected date).

**Comment by alexdriaguine** [comment]
@wojtekmaj if you need help I could do this :)

**Comment by wojtekmaj** [comment]
I'm fine, only this is queued for the next major release, as such style adjustments may break people's designs.
