### ISSUE TITLE
Next label doesn't work

### ISSUE THREAD

**Issue by materaldo** [wojtekmaj/react-calendar#113]
Hi, yesterday I saw some bug in my Calendar component. Previous week everything works correctly. Next label isn't working for me (prev label also but it is correct because minDate is current date). I didn't change nothing in my code from previous week and I can't find a solution. Do you know what could be wrong? This is my Calendar:

```
<Calendar
                    locale="en"
                    minDate={new Date()}
                    minDetail="month"
                    onChange={this.onDateChange}
                    tileClassName="calendarDay"
                    tileDisabled={this.isDayDisabled}
                    value={selectedDate}
                    prev2Label={<Empty/>}
                    next2Label={<Empty/>}
                    showNeighboringMonth={false}
                />
```

**Comment by wojtekmaj** [comment]
What do you mean by "doesn't work"?

**Comment by materaldo** [comment]
@wojtekmaj sorry for the wrong explanation. I mean that next label button look like it's working, but in real it doesn't. For now I have September and I cannot change it.

**Comment by wojtekmaj** [comment]
There's nothing wrong in your code I think.

Perhaps if the code "suddenly stopped working" you have updated React-Calendar to a version that has changed something? Try and set a version explicitly in your `package.json` file, like `"react-calendar": "2.16.0",` (mind the lack of `^`). If that will work for you, we need to figure out what change broke your implementation.

**Comment by materaldo** [comment]
I tried this. It doesn't help me :( . I also made new simple component with Calendar 
`<Calendar
                    locale="en"
                    onChange={this.onChange}
                    value={this.state.date}
 />`

Now I can change month by clicking on 'grey days' from prev or next months. Prev and next buttons still not working. I attached a photo of calendar.

![calendar](https://user-images.githubusercontent.com/11336052/45078380-2f7a8b80-b0f0-11e8-9c64-8b0e618c265e.png)

**Comment by wojtekmaj** [comment]
This is gonna be a wild guess, but remove `value` prop and try again. I suspect that you're creating new `value` with each render, which makes the calendar jump automatically to "newly" selected value, making you seem stuck on September.

**Comment by materaldo** [comment]
@wojtekmaj I don't know what was the reason but it started to working now. Earlier I didn't rerun application. I did it now (after update react-calendar). I apologize for the problem and thanks a lot for a help. Have a nice day.

**Comment by wojtekmaj** [comment]
Sure thing - if you ever need help in the future don't hesitate to write. :)
