### ISSUE TITLE
 Manually go to the activeStartDate

### ISSUE THREAD

**Issue by vitorcominato** [wojtekmaj/react-calendar#114]
Hi @wojtekmaj , first i want to congratulate you for the awesome datepicker that you've done, nice job! :) 

I have a calendar inside a dropdown component of mine that closes when the user clicks outside of the calendar.
The problem is that when i navigate through the months, don't select any day and close the dropdown,
i need that when he opens again, the calendar must open on the activeStartDate that i previously set.

So, there is a way that i manually go to the activeStartDate of the calendar?

Thanks again.

**Comment by vitorcominato** [comment]
Just found this.refs.calendarRef.setActiveStartDate and it worked.

**Comment by wojtekmaj** [comment]
I honestly didn't know you can do that :D Happy hacking!
