### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by yicaiweng** [wojtekmaj/react-calendar#116]
Hello there, 
How do I get rid of some of those elements such as the << >> arrows, change Mon Tue Wed to just M T W. 

Thanks in advance!

**Comment by jwrlee88** [comment]
check out the prevLabel and the prev2Label in the docs! The PrevLabel prop is what renders the '<' arrows, and the prev2Label is what renders '<<'

**Comment by yicaiweng** [comment]
thanks for your reply, I got that figured out. But not sure how to Chang Mon Tue We’d to just M T W T

**Comment by wojtekmaj** [comment]
You can hide that using CSS :) You need `display: none` on `.react-calendar__month-view__weekNumbers`.

**Comment by bobgutierrez** [comment]
Hi,
How can I change font family? Also, I want circles instead of squares when selecting a day, is that possible? Can I have today’s day showing with one style and another day selected i.e. 2 days ago, with a different style?

**Comment by yerassylad** [comment]
Hello, what can i do to change rendering of days to one line?
like:
1 2 3 4 ... 30

**Comment by wojtekmaj** [comment]
@bobgutierrez 
font family: Just via CSS `font-family`, should work fine.
circles: `border-radius: 50%` on `.react-calendar__tile--active` class

@yerassylad 
`flex-wrap: nowrap;` to `.react-calendar__month-view__days` and `margin: 0 !important;` to `.react-calendar__month-view__days .react-calendar__tile`

**Comment by Clepto** [comment]
Hello @wojtekmaj, can we pass styles using the `style` prop?

**Comment by sanjeevdev** [comment]
can add any html tag on Date box?

**Comment by wojtekmaj** [comment]
@Clepto no, it's not possible, sorry.

@saitodisse You can't, but you can use CSS `content` to prepend/append content with some additional text.

**Comment by llamerr** [comment]
> @bobgutierrez
> circles: `border-radius: 50%` on `.react-calendar__tile--active` class
This does not work, since they are not circles, but ellipsises - element is 36x29
![image](https://user-images.githubusercontent.com/1281970/57086011-073a3f80-6d06-11e9-8af3-1d6f1de27573.png)

**Comment by DDDDDanica** [comment]
@llamerr i found out you can do this to override the circle element style :)
```
"& abbr": {
              textDecoration: "none",
              width: "24px",
              height: "24px",
              borderRadius: "50%",
              display: "flex",
              justifyContent: "center",
              alignItems: "center"
            },
```

**Comment by DDDDDanica** [comment]
@wojtekmaj  The `fontFamily` worked for all the DOMs except for days:
<img width="723" alt="Screenshot 2019-10-01 at 18 10 02" src="https://user-images.githubusercontent.com/12678455/65984090-e1f95b00-e476-11e9-833f-95f3ddaf9f6d.png">

**Comment by CrazyPythonLover1** [comment]
how to change the border color of react-calendar?
.react-calendar{
    border: none !important;
}
I wrote this code .. but it doesn't work

**Comment by raraitis** [comment]
Hi, how could I change weekdays to - "M", "T", "W" ... instead of "MON" "TUE" "WED" ... ? And round  only left and right for the first and last selected date on selecting range?

**Comment by wojtekmaj** [comment]
> Hi, how could I change weekdays to - "M", "T", "W" ... instead of "MON" "TUE" "WED" ... ? 

See README for `formatShortWeekday`.

> And round only left and right for the first and last selected date on selecting range?

Tiles have classes:

* `.react-calendar__tile--range`
* `.react-calendar__tile--rangeStart`
* `.react-calendar__tile--rangeEnd`

I think they are pretty self explanatory. Add styles as you need them.

**Comment by sturmenta** [comment]
> how to change the border color of react-calendar?
> 
> ```css
> .react-calendar{
>     border: none !important;
> }
> ```
> 
> I wrote this code .. but it doesn't work

suggestion:

- create a duplicate of this file `import 'react-calendar/dist/Calendar.css';`
- import in your code `import "./Calendar.css";`
- customize the CSS freely
