### ISSUE TITLE
TypeScript return value in onChange

### ISSUE THREAD

**Issue by JamieEgeberg** [wojtekmaj/react-calendar#117]
For some reason i get an error when trying to use the return value with typescript, even though return value is set to "start", it gives an error  reading:

Argument of type 'Date | Date[]' is not assignable to parameter of type 'Date'.
1|webpack- |   Type 'Date[]' is not assignable to type 'Date'.
1|webpack- |     Property 'toDateString' is missing in type 'Date[]'.

shouldnt it know that the type of val would be Date and not an array, when the returnValue is set to "start"?

image of the props:
![image](https://user-images.githubusercontent.com/15196300/45293368-48bc7700-b4f8-11e8-929b-9de68894683a.png)

**Comment by wojtekmaj** [comment]
@alexdriaguine Looks like the improvements in TypeScript have been merged; would you like to create a PR with the new improvements?

**Comment by alexdriaguine** [comment]
@wojtekmaj I can see if I can find some time to take a dig at it this weekend :)

**Comment by alexdriaguine** [comment]
@wojtekmaj Sorry, been busy. If anyone else want's a crack at this, feel fre. Otherwise I'll get to it as soon is I get some free time :)

**Comment by wojtekmaj** [comment]
Closed because of #273
