### ISSUE TITLE
How to resize the calendar?

### ISSUE THREAD

**Issue by jwrlee88** [wojtekmaj/react-calendar#119]
Hello, 

is there any way to make the size of the calendar bigger? I tried making the calendar's width and height to 100% so that it just takes the size of the div, but it just looks like this screenshot here: http://i.imgur.com/7wmis0h.png

Any advice would be appreciated, thanks!

**Comment by wojtekmaj** [comment]
Hi there,
While the calendar will fill its container width, height is automatically calculated. So to expand its height you will need to expand the content somehow, for example by setting bigger top and bottom padding of the tiles.
