### ISSUE TITLE
onClickWeek and onClickMonthLabel

### ISSUE THREAD

**Issue by amansur** [wojtekmaj/react-calendar#12]
Hi there wojtekmaj

I'm really enjoying using your Calendar component. 

The showWeekNumbers prop is especially useful for me. Would it be possible to add a click listener for the week numbers similar to the other onClick{period} props.

For my use, I'm also disabling all views aside from Month using the minDetail prop. Since the month label no longer changes the view, I'd like to be able to attach a click handler on the month label. Could that be a prop as well?

Thanks again for the great module!

**Comment by amansur** [comment]
Thanks so much for the speedy enhancement!

Unfortunately, I wasn't able to get the new branch installed. Looking at the `node_modules/react-calendar` directory after using your install command, it seems to be missing the `build` folder?

> Failed to compile.
> 
> ./src/App.js
> Module not found: Can't resolve 'react-calendar' in '/Users/amansur/code/calendar-test/src'

**Comment by wojtekmaj** [comment]
Ah yeah, sorry, I missed the part that git branch lacks /build folder. You'd need to run `npm install` and `npm run build` in its directory to make it work.

**Comment by wojtekmaj** [comment]
...or take it precompiled from me:
[build.zip](https://github.com/wojtekmaj/react-calendar/files/1522503/build.zip)

**Comment by amansur** [comment]
Thank you, the precompiled version works great.

For the calculation, I assume you're using the ISO 8601 standard of having Monday be the first day of the week?

**Comment by wojtekmaj** [comment]
Not necessairly. If you explicitly chose calendarType `ISO 8601` or set non-`en-US` locale, then yes. Please mind that in US calendar not only the week starts on Sunday, but also week numbers are calculated differently.

**Comment by amansur** [comment]
The callback is always given the Monday as the weekStartDate. I've tried explicitly setting the `calendarType` prop to `'US'` and also excluded the prop (I'm in a en-US locale).

**Comment by wojtekmaj** [comment]
Sorry, my bad! Forgot to pass one parameter. ;)

[build.zip](https://github.com/wojtekmaj/react-calendar/files/1522619/build.zip)

**Comment by amansur** [comment]
Awesome, it works great now! Thanks again!

**Comment by wojtekmaj** [comment]
Glad I could help. Expect it in the next release :)

**Comment by wojtekmaj** [comment]
onClickWeekNumber has been added in v2.6.0. onClickMonthLabel would be too problematic, but I think you can apply custom callbacks by yourself, as well.
