### ISSUE TITLE
Date content overlap each other

### ISSUE THREAD

**Issue by karanshrm44** [wojtekmaj/react-calendar#120]
When I am trying to implement dates are overlapping each other 
https://3x5ywl0or5.codesandbox.io/
You can check at above link
just click on the select date

**Comment by wojtekmaj** [comment]
That looks pretty fine to me, what's the deal?

![obraz](https://user-images.githubusercontent.com/5426427/45585046-37031700-b8de-11e8-91cb-93ce0c9ab1aa.png)

What browser are you using?

**Comment by karanshrm44** [comment]
Actually I change the class  manually can you look the code in Home.css
and remove the those classes then look

**Comment by karanshrm44** [comment]
https://codesandbox.io/s/3x5ywl0or5

**Comment by karanshrm44** [comment]
Here is a code

**Comment by wojtekmaj** [comment]
Sorry, but I still don't understand what is your problem.
