### ISSUE TITLE
how to make it readonly / disabled?

### ISSUE THREAD

**Issue by ajalbani1** [wojtekmaj/react-calendar#123]

**Comment by wojtekmaj** [comment]
1. `tileDisabled={() => true}` would disable all tiles from being clicked.
2. `pointer-events: none` will disable all clicks on the calendar.

**Comment by GustavoOS** [comment]
@wojtekmaj any way to display the selected values but still make it read-only?

**Comment by wojtekmaj** [comment]
@GustavoOS Have you tried tileDisabled prop? It shouldn't make the values "not selected", but you may need some CSS changes to make it look nice.
