### ISSUE TITLE
Show only the days of the week Monday to Saturday

### ISSUE THREAD

**Issue by henriqueweiand** [wojtekmaj/react-calendar#126]
Is it possible to display only days between Monday and Saturday?

**Comment by wojtekmaj** [comment]
This is unusual enough you'd need to hack things around a little.

```
.react-calendar__month-view__weekdays__weekday,
.react-calendar__month-view__days__day {
  max-width: calc(100% / 6) !important;
  flex-basis: calc(100% / 6) !important;
}
.react-calendar__month-view__weekdays__weekday:nth-child(7n) { display: none; }
.react-calendar__month-view__days__day:nth-child(7n) { display: none; }
```

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by fosteman** [comment]
Hey @wojtekmaj,
What would be a setup for only current week ? (i.e. 7 days Monday-Sun)
Thanks a lot!

**Comment by wojtekmaj** [comment]
Just for reference for anyone coming to this thread now. It's been 2 years since this question was asked :)

Proper solution today would be to build tileClassName function that checks if a day is Sunday, and if so, returns a class name, e.g. "hidden".
