### ISSUE TITLE
How to use tileContent to replace content?

### ISSUE THREAD

**Issue by shaina33** [wojtekmaj/react-calendar#127]
I'm trying to replace the standard date (in the monthly view) with a custom component using the `tileContent` prop. However, it seems to only add content, rather than replacing the date entirely. As a simplified example, I just passed a function that returns `'x'`. I would expect every date to display as `x`. Instead, they display as `1x`, `2x`, etc.

Is it possible to entirely replace the content with my custom content?

Thank you!

```javascript
<Calendar
     onChange={ this.onDateChange }
     value={scheduledDate}
     tileContent={ ({date, view}) => ('x') }
/>
```

<img width="332" alt="screen shot 2018-09-27 at 4 54 08 pm" src="https://user-images.githubusercontent.com/17550347/46174214-6454ab00-c276-11e8-8f12-01ad6c3cb95d.png">

**Comment by shaina33** [comment]
Looking at the source code, it seems this is how it's supposed to be. For now, I've hidden the date using the following, but I'm still curious if there's a better way to remove it.
```
.react-calendar__tile time {
    display: none;
}
```

**Comment by wojtekmaj** [comment]
Hi Shaina,
your solution is correct. I think we can consider removing the day from the *calendar* an edge case ;)

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
