### ISSUE TITLE
year picker

### ISSUE THREAD

**Issue by daviddionys** [wojtekmaj/react-calendar#128]
Dear, your calendar is great for picking dates and establishing ranges for days, but when I tried to use the decadeview I was expecting to get a list of years in one tile.  Instead I got the normal calendar view for the startdate that I gave for the year.  I must admit that I did not analyse your source code in detail yet, but I just wonder if it is working at all.  Could you provide an example of the use of DecadeView (or YearView).   Even a screenshot of what it is supposed to be doing would be very helpful already.  

Thanks in advance,
David

**Comment by wojtekmaj** [comment]
You need to pass `maxDetail="decade"` to `<Calendar />`. This way the "max zoom" of the calendar will be decade view, which has a list of years, obviously. Clicking a year then will not cause it to "dive in" into YearView, but will return a new year in `onChange`.

**Comment by daviddionys** [comment]
Thank you so much, this gave exactly the view that I was after.
