### ISSUE TITLE
How to edit the style of week numbers? 

### ISSUE THREAD

**Issue by raini35** [wojtekmaj/react-calendar#129]
![editing_calendar](https://user-images.githubusercontent.com/13359863/46503846-bb67fc00-c7f1-11e8-902b-f6ef1fbc5e1c.gif)

react-calendar is great! I'm using it for a personal project and it's a life saver. I did run into a bit of a rut. So I set the attribute to show week numbers as true and the formatting is a bit off. (The gif above shows the edits I wanted to make.)  I tried going into the react-calendar module itself and change the Calendar.css and Calendar.less files, but it wasn't updating for some reason. 

Am I doing something wrong? What would be the best way to change the style?

**Comment by wojtekmaj** [comment]
Hi,
there are two ways you can change the style.

1. Import React-Calendar without the styles (more info in README), copy the original styles from this repo to your project, import them where how you want and edit as you want
2. Add another stylesheet to overwrite default React-Calendar styling when needed.
