### ISSUE TITLE
Implement activeStartDate as optional prop for Calendar, too

### ISSUE THREAD

**Issue by lightninglu10** [wojtekmaj/react-calendar#13]
Hey @wojtekmaj ,

I'm trying to use the activeStartDate to push my calendar to the active day, but it's not working.

I've set the minDate and activeStartDate to the same date, but whenever I open the calendar, I get that it still opens on the current day today.

<img width="264" alt="screen shot 2017-11-30 at 11 32 00 am" src="https://user-images.githubusercontent.com/2453737/33450928-340bf83c-d5c2-11e7-9029-efdaded0eae5.png">

This forces me to click next to get to the right date. Any idea what's up?

**Comment by wojtekmaj** [comment]
Hey Patrick,
activeStartDate is only handled by internal components used inside Calendar for telling them which period to display. So as of now, to open calendar by default on a given view, you'd have to pass a value to it. I do agree that it's quite stupid.

How does that sound?:

1. The calendar opens by default on selected value, if provided
2. **(new step)** If no value was provided, it opens by default on activeStartDate
3. If no activeStartDate was provided, it opens by default on today's date

**Comment by lightninglu10** [comment]
Yeah those steps look good. I'll pass a value to it for now.

**Comment by wojtekmaj** [comment]
Great! Expect a new version soon :) Thanks for your suggestion!

**Comment by wojtekmaj** [comment]
@lightninglu10, check out version 2.5.0!
