### ISSUE TITLE
Select multiple dates?

### ISSUE THREAD

**Issue by baba43** [wojtekmaj/react-calendar#136]
Hey there,

first of all, let me say thanks for this awesome library. It looks very nice and it work's smooth. 

However, what I need is a calendar where the user can pick multiple dates (not ranges). 
Is this somehow possible right now?

**Comment by wojtekmaj** [comment]
Hello,
no, it's not possible at the moment. It seems like it'd be a nice improvement though.

**Comment by nshoes** [comment]
Implemented this today by using a component as a state container. It was pretty easy! Leaving this here for anyone else:

```js
// helpers
const dateAlreadyClicked = (dates, date) => dates.some(d => dayjs(date).isSame(dayjs(d), 'day'))
const datesExcept = (dates, date) => dates.filter(d => !dayjs(date).isSame(dayjs(d), 'day'))
const Calendar = ({ classes }) => {
  const [dates, setDates] = useState([])

  const onClickDay = date => {
    if (dateAlreadyClicked(dates, date)) setDates(datesExcept(dates, date))
    else setDates([...dates, date])
  }

  const tileClassName = ({ date }) => {
    const classNames = [classes.dayTile]
    if (dateAlreadyClicked(dates, date)) return [classes.activeDay, ...classNames]
    return classNames
  }
  console.log(dates.length)
  return (
    <ReactCalendar
      next2Label={null}
      prev2Label={null}
      minDetail='month'
      className={classes.calendar}
      minDate={new Date()}
      tileClassName={tileClassName}
      formatShortWeekday={(_, date) =>
        dayjs(date)
          .format('ddd')
          .toUpperCase()
      }
      onClickDay={onClickDay}
    />
  )
}
```

**Comment by Edeph** [comment]
@nshoes I don't understand what the `classes` objeect passed to is supposed to be. I just assigned an existent class name from the `.css` file, the class name gets applied correctly (I can see it listed on the element when I inspect it), but the style itself is not applied ({color: 'red} for example).
