### ISSUE TITLE
Is it possible to change <button> tag to some other to avoid blocking any event of child elements in FF and IE?

### ISSUE THREAD

**Issue by Viktori** [wojtekmaj/react-calendar#138]
I'm using tileContent to add custom markup inside each day and assign some events to child elements, but it doesn't work for IE and Firefox because elements inside button are not clickable, they are just plain text. See https://bugzilla.mozilla.org/show_bug.cgi?id=843003.

So is it possible to replace button with div for example somehow?

Thanks a lot in advance, great component helps me a lot! 👍 But I really need some custom structure with custom events inside each day :(

**Comment by wojtekmaj** [comment]
Hi there,
sorry, it's not possible at the moment, see #85 for details why.
It's considered a bug by Mozilla, so I suggest pinging them in this bug or perhaps related one - https://bugzilla.mozilla.org/show_bug.cgi?id=1089326
