### ISSUE TITLE
Not getting the value of hover prop.

### ISSUE THREAD

**Issue by ChaitanyaGadodia** [wojtekmaj/react-calendar#139]
In the description, it says that hover is the date on which the user is hovering. But it seems that it is not being used in the CalendarProps.

**Comment by wojtekmaj** [comment]
You are not expected to use `MonthView`, `YearView`, `DecadeView`, `CenturyView` directly. `hover` is not used as a prop in Calendar, but it is used internally for date range selection.

**Comment by ChaitanyaGadodia** [comment]
So there is no way I can get the value of the date on which I am hovering in the current code?

**Comment by wojtekmaj** [comment]
You could get `Calendar`'s instance by using `ref` and access its `state` to get `hover` value out of it, I think 🤔
