### ISSUE TITLE
Tile being a button element interferes with content in FF and IE (part 2)

### ISSUE THREAD

**Issue by jhammersholt** [wojtekmaj/react-calendar#143]
I tested the &lt;div role="button"&gt; discussed in https://github.com/wojtekmaj/react-calendar/issues/85
Sadly have i client where it need to work in Firefox and i need clickable events inside the tiles, but i couldn't get it to work properly

This has a number of issues where CSS is one (hover effect not working).
Also when limiting the calendar with minDate and maxDate the clickOnDay/onChange of a disabled tile makes it behave wonky (when clicking later than maxdate) the last acceptable tile gets marked as if it was selected.

Any pointers on how to solve this is greatly appreciated

**Comment by jhammersholt** [comment]
I have given it a go can you look at this and give me any comments you have?

https://github.com/wojtekmaj/react-calendar/compare/master...VikarNU:JH-161749306

I'm not making a PR right now since i found a bug when selecting multiple dates (inconsistently the start and end would switch place in the resulting array)

**Comment by wojtekmaj** [comment]
Rebase your fork to 2.17.5 (master), it has this bug fixed. ;)

Other than that, it looks really good.

**Comment by jhammersholt** [comment]
Unfortunately i'm already using 2.17.5 so i must have broken it somehow :) Hopefully i'll find some time soon to bug fix it ;)
