### ISSUE TITLE
rangeStart/rangeEnd not appearing when using values other than midnight

### ISSUE THREAD

**Issue by pschuegr** [wojtekmaj/react-calendar#153]
Hi,

I'm having trouble initializing the date range on the calendar component:

```
<Calendar
  value={[Moment().toDate(), Moment().add(2, 'days').toDate()]}
  selectRange={true}
/>     
```

I would expect to see the range classes on some of the days: `.react-calendar__tile--rangeStart` etc.  But they do not show up.  Any suggestions?

**Comment by wojtekmaj** [comment]
The reason of that happening is that Moment().toDate() returns current hour of the day.
So your range does not cover the day fully, but just a part of it.

I do understand your confusion though and I think that a tile should be marked as `rangeStart` if a range starts somewhere within a given tile.
