### ISSUE TITLE
Update `value` with date range does not highlight correct range

### ISSUE THREAD

**Issue by andrewsim** [wojtekmaj/react-calendar#154]
I am using `selectRange=true` but modify it slightly so that the `startDate` and `endDate` will always jump to the first Monday and last Sunday of the respective weeks. 

```javascript
class MyCalendar extends React.Component {
  state = {
    date: undefined,
  }

  onChange = date => {
    const start = moment(date[0]).isoWeekday(1)
    const end = moment(date[1]).isoWeekday(7)

    this.setState({ date: [start.toDate(), end.toDate()] })
  }

  render() {
    return (
        <Calendar
          onChange={this.onChange}
          value={this.state.date}
          selectRange={true}
        />
    )
  }
}
```

Most of the time it works fine:

![a](https://user-images.githubusercontent.com/2834017/49397416-697d1d00-f733-11e8-89aa-ac4ea0eb7d16.gif)

However, I noticed that when I select two dates twice (or select a start date and an end date, then select another start date to the same week of the previous start date and another end date to the same week of the previous end date) then it will not highlight the date range that is passed to `value`.

![b](https://user-images.githubusercontent.com/2834017/49397503-b4973000-f733-11e8-8d1e-6f0b4069b32c.gif)

Am I doing anything wrong here or are there any other ways to achieve the desired effect?

**Comment by djdaniels90** [comment]
I have a similar issue.  It seems to click the dates in my case, adds active status classes to the surrounding buttons but does not seem to change the underlying dates.
I'll post some updates here about my specific case but it is essentially similar.  On a side note, what do you use to make those gifs?  I haven't found a particularly straightforward tool for doing it, usually, it requires a screen cap then convert.

**Comment by andrewsim** [comment]
> On a side note, what do you use to make those gifs?

[GIPHY Capture](https://giphy.com/apps/giphycapture) :wink:

**Comment by andrewsim** [comment]
some how I think it's cause by this check: 
https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.jsx#L227

since the dates to achieve my desired effect are technically the same compare to my previous selection (the first Monday to the last Sunday), so something did not kick in.

**Comment by wojtekmaj** [comment]
Hmmm. So the problem here is that you're setting the same date twice via props, so the calendar thinks "Oh okay, date from props did not change at all, so I might as well ignore it". If not for this check, the calendar wouldn't be able to have anything other than date from props selected, effectively blocking a new range from being selected.

A not ideal, but working workaround for that would be to reset the date for a split second:

```js
  onChange = (date) => {
    this.setState({ value: date }, () => this.setState({
      value: [getBeginOfWeek(date[0]), getEndOfWeek(date[1])],
    }));
  }
```
