### ISSUE TITLE
Keyboard navigation support

### ISSUE THREAD

**Issue by Rafi993** [wojtekmaj/react-calendar#162]
How do I add keyboard support. So that user can navigate the calendar using arrow keys.

**Comment by Rafi993** [comment]
This PR should add basic keyboard navigation https://github.com/wojtekmaj/react-calendar/pull/163 but we could add more too.

**Comment by Rafi993** [comment]
We could add more keyboard shortcuts similar to **react-dates**

**Comment by rodriguezmarting** [comment]
Would love this addition!
