### ISSUE TITLE
Should 2.18.0 have been a major version update?

### ISSUE THREAD

**Issue by darsee** [wojtekmaj/react-calendar#166]
Firstly, thank you for a very nice calendar component!

The order of the arguments for formatters changed in v2.18.0 ([here](https://github.com/wojtekmaj/react-calendar/commit/d9c9e6160cf8294a0a54e95e47e839837b424537#diff-e31d1fcc0ecfc901b7392dabe6bd0be7R9)) - should that have been a major version bump?

**Comment by wojtekmaj** [comment]
Yes, strictly following semver it should have been a major version update. Sorry for the commotion.
