### ISSUE TITLE
Clear value button

### ISSUE THREAD

**Issue by marius-ionescu** [wojtekmaj/react-calendar#167]
Hi, are there any plans to add a clear button to the component? much like react-select's clearable flag.

Or is there something similar already in place for it?

**Comment by wojtekmaj** [comment]
Hi,
no, there were no plans to change the layout of the calendar. As a workaround, you could add a clear button by simply adding the same onChange callback to your custom button which would nullify the value.

**Comment by Mione** [comment]
thanks vojtekmaj,
yup that's obviously a possibility, but I would argue cleareable is a useful feature to have already baked in.
If need be I would be willing to raise a PR for this

**Comment by wojtekmaj** [comment]
I've decided not to add Clear button to common UI. There are easy enough ways to add this button on your own if you need to.

**Comment by Frankoloko** [comment]
This does not work with the selectRange: true setting.

<Calendar onChange={this.dateRangeSelected} value={this.state.selectedDateRange} selectRange={true}/>

dateRangeSelected = selectedDateRange => {
    this.setState({ selectedDateRange: null });
}

This doesn't clear the selection

**Comment by wojtekmaj** [comment]
@Frankoloko Have you tried the new React Calendar 3.0 beta? It should work fine as a controlled component!

**Comment by arrmani88** [comment]
Hey guys @wojtekmaj , thanks for this amazing calendar, please have a look at [this issue](https://github.com/wojtekmaj/react-calendar/issues/281#issuecomment-1157160040).
Thanks
