### ISSUE TITLE
tileContent called before my data has loaded

### ISSUE THREAD

**Issue by Coder2012** [wojtekmaj/react-calendar#168]
![initial](https://user-images.githubusercontent.com/1157627/51991820-d0088800-24a3-11e9-8ecc-2375588905d2.PNG)

Now I select previous month and data updates:

![updated](https://user-images.githubusercontent.com/1157627/51991834-d860c300-24a3-11e9-909f-f4534018ac7a.PNG)

My data exists in redux store under results date.

When my app loads I have a list of dates which I use to render in `tileContent`. This works fine the first time, but when I change the month I load more data and this time it looks like `tileContent` is called before all my data arrives in `this.props.dates`. You can see that January data still highlighting in December.

How can I make `tileContent` function wait until my data loads or refresh the month view after it loads?

**Comment by Coder2012** [comment]
Thank you for the suggestion, I am using the calendar as follows:

`<ReactCalendar 
                    tileClassName="calendar-item" 
                    tileContent={this.tileContent} 
                    minDate={new Date('2005-01-01')}
                    maxDate={new Date()}
                    onChange={this.props.dateChangeHandler} 
                    onClickMonth={this.props.monthChangeHandler}
                    onActiveDateChange={this.props.calendarNavigationHandler} />`

and my `tileContent` fn:

`tileContent = ({ date, view }) => {
        let flightCount = this.dateExists(date.getMonth(), date.getDate());
        if (flightCount) {
            return view === 'month' && flightCount ? <span className={`calendar-flights ${this.getCountClass(flightCount)}`}>{date.getDate()}</span> : null;
        }
        return null;
    }`

I don't quite follow where I would make this update, the dates are passed as props to this wrapper component which contains your react-calendar component.

**Comment by Coder2012** [comment]
@icyJoseph @wojtekmaj 

Now I understand it, It's working how I need it to now. 

Thank you for your help!

**Comment by erbaafidotama** [comment]
> Thank you for the suggestion, I am using the calendar as follows:
> 
> ```
> <ReactCalendar 
>                     tileClassName="calendar-item" 
>                     tileContent={this.tileContent} 
>                     minDate={new Date('2005-01-01')}
>                     maxDate={new Date()}
>                     onChange={this.props.dateChangeHandler} 
>                     onClickMonth={this.props.monthChangeHandler}
>                     onActiveDateChange={this.props.calendarNavigationHandler} />
> ```
> 
> and my `tileContent` fn:
> 
> ```
> tileContent = ({ date, view }) => {
>         let flightCount = this.dateExists(date.getMonth(), date.getDate());
>         if (flightCount) {
>             return view === 'month' && flightCount ? <span className={`calendar-flights ${this.getCountClass(flightCount)}`}>{date.getDate()}</span> : null;
>         }
>         return null;
>     }
> ```
> 
> I don't quite follow where I would make this update, the dates are passed as props to this wrapper component which contains your react-calendar component.

Thank for open this issue before.

Can i know how you check date exist in `this.dateExists(date.getMonth(), date.getDate())` ?
