### ISSUE TITLE
tileClassName Not Working

### ISSUE THREAD

**Issue by searedahi** [wojtekmaj/react-calendar#169]
I was hoping you could identify why I cannot get tileClassName prop to fire.  tileDisabled and the onHeadcountChange and onExperienceDateChange events work just fine.  Thank you for your effort and for providing such an awesome plugin!

```
function renderExperienceInfoAndAvail(experienceDetails) {

    /////////

    return (
                <section id="experienceDetailsCalendarSection">
                    <Calendar
                        tileClassName={tileClassName}
                        onChange={onExperienceDateChange}
                        value={todaysDate}
                        tileDisabled={tileDisabled}
                    />
                </section>
    );
}


function tileClassName({ date }) {
    console.log('ClassOn: ' + date);
    return 'experienceIsRed !important';
}

function tileDisabled(dateArg) {
    return checkActiveDates(dateArg);
}

function onHeadcountChange(value, event) {
    console.log('Headcount Changed: ' + value);
}

function onExperienceDateChange(dateSelected, event) {
    console.log('Date Selected: ' + dateSelected);
}
```

**Comment by wojtekmaj** [comment]
Hi,
your `tileClassName` returns invalid class name. You are supposed to add `!important` to CSS properties, not to class names.

**Comment by searedahi** [comment]
Hi,
I removed the !important css attribute and the prop is still not working.  Thoughts and much appreciation!

function renderExperienceInfoAndAvail(experienceDetails) {

    /////////

    return (
                <section id="experienceDetailsCalendarSection">
                    <Calendar
                        tileClassName={tileClassName}
                        onChange={onExperienceDateChange}
                        value={todaysDate}
                        tileDisabled={tileDisabled}
                    />
                </section>
    );
}


function tileClassName(date, view ) {
    console.log('experienceIsRed');

    let classes = [];
    classes.push('experienceIsRed');
    return classes;
}

**Comment by wojtekmaj** [comment]
I ran your code and it works just fine. Well, arguments to tileClassName functions are wrong, so if you're giving me simplified version of your code, then maybe the function is crashing somewhere.

**Comment by jdewitt3** [comment]
I am having the same issue after updating to the latest release - I can't even specify a simple string as a tileClassName. Confirmed that reverting to version 2.17.5 causes tileClassName to work as intended.

**Comment by wojtekmaj** [comment]
@jdewitt3 That's odd, we have unit tests in place which are testing just that which haven't been touched for over a year, and my test suite also dynamically colors tiles just fine. Would you be so kind and create CodeSandbox with minimal reproduction example?
