### ISSUE TITLE
Showing two month at a time and month and year range selction

### ISSUE THREAD

**Issue by LahiruRajapaksha** [wojtekmaj/react-calendar#170]
Hi,
There is no option to add two month at a time like #82 and selecting month and year ranges. Will you gonna improve it?

**Comment by wojtekmaj** [comment]
Yes, there are plans to do it. I can't give you any dates at the moment, though.

Duplicate of #82

**Comment by wojtekmaj** [comment]
Duplicate of #82

**Comment by LahiruRajapaksha** [comment]
Thanks for the reply
