### ISSUE TITLE
Changing view prop externally does not update the view mode, only the navigation label

### ISSUE THREAD

**Issue by Serban-O-C-Temp** [wojtekmaj/react-calendar#171]
version: 2.18.1

Hi,

I'm attempting to externally switch view mode from e.g. 'year' to 'decade'. If I start out with either of those two values, the correct view mode is displayed. However, if I start off with 'year' and switch to 'decade' externally with setState, the re-render results in the navigation label being updated with the lowest year of the respective decade and the view still showing 'year' mode. Example:

```
  constructor(props) {
    super(props);
    this.state = {
      date: null,
      view: 'year'
    }
  }
...
  <Calendar 
     view={this.state.view}
     onChange={this.pickDate}
     value={this.state.date}    
   />
...
  selectView = (view: string) => {
    this.setState({view});
  }
  private pickDate = (date: any) => {
    this.setState({date});
  }
```

initial 'year' view:

![image](https://user-images.githubusercontent.com/46317186/52564210-78e7a900-2dfb-11e9-827e-af2e26cbfbea.png)

after switching to decade externally with
```
this.selectView('decade');
```
view mode becomes:
![image](https://user-images.githubusercontent.com/46317186/52564385-f3b0c400-2dfb-11e9-94ae-37ffcf37da30.png)

Is there any way to have view mode updated, or is there any other version I should switch to?

The application I'm working on uses React 16.3.2 and TypeScript 3.3.2.

**Comment by OsipovIgor** [comment]
I have the same problem

**Comment by stand1715** [comment]
It seems this prop would only affect the initial type of view.

**Comment by wojtekmaj** [comment]
Yes - as README states, `view` "Determines which calendar view shall be opened **initially**."

Otherwise we're getting a conflict between view in props and state. I hear you though and it will work differently in the next major version.
