### ISSUE TITLE
Tile `if` check causes issues when dynamically styling

### ISSUE THREAD

**Issue by hewsut** [wojtekmaj/react-calendar#172]
Hi there,

Just wanted to report upstream of us that the `if` over here: https://github.com/wojtekmaj/react-calendar/blob/9c601ddcc2f198453caa071db24c2f1629be17a6/src/Tile.jsx#L18

...causes issues if you are dynamically styling tiles with a function. The equality check is always true if `react-calendar` is passed a constant function which means it never fires again which is problematic if you use the prop to style selections dynamically.

We've worked around it for now by rebinding the function in the parent every time we update.

### Repro:

1. Write and supply a function to `tileClassName`.
2. Use range select.
3. Use the parameters that get passed to the `tileClassName` function to dynamically style selected date values.
4. Test out selecting multiple date ranges. You should see odd behavior as the styling initially applied "sticks" to the initial range.

**Comment by wojtekmaj** [comment]
Hi,
yeah, a good idea is to have the function referentially unequal every time we expect it to give a different output. So, for example, you `this.tileClassName = () => 'x'` and then when it's expected to give a different output, `this.tileClassName = () => 'y'`. This way you can then use `tileClassName={this.tileClassName}` in `render()` and it should work just fine.
