### ISSUE TITLE
Date in state is 1 day behind clicked date in calendar

### ISSUE THREAD

**Issue by Steakie** [wojtekmaj/react-calendar#174]
Let's say i start the app, and click the first of februry in 2019.
In this case. state.value is "Date: 2019-01-31T23:00:00.000Z"

My code:
```
class Events extends Component {

  state = {
    value: new Date(),
  }

  handleDayClicked() {
  }

  handleChange = date => {
    this.setState({ date });
    this.print(date);
  }

  print(x) {
    console.log(x);
  }

  render() {
    const { classes } = this.props;

    return (
      <div className={classes.root}>
        <TopBar title="Performance" backTarget="" />
        <Calendar
          onChange={this.handleChange}
          onClickDay={this.handleDayClicked}
          value={this.state.value}
        />
      </div>
    );
  }
}
```

**Comment by wojtekmaj** [comment]
Hi,
this is just how the date is represented by your browser. Seems like February 1st 2019 midnight at your location is January 31st 23:00:00 in UTC.

**Comment by pjg** [comment]
I had a similar issue. Date returned by the component would always be in the local timezone with hour being 0:00. While living in UTC+2h, my dates upon conversion to string using regular JS methods would always return the previous day.

Here's how I got around it using `Intl`:

```javascript
  const onChange = (newValue) => {
    const dateFormat = new Intl.DateTimeFormat('en-GB', { year: 'numeric', month: '2-digit', day: '2-digit' })
    const formattedDate = dateFormat.format(newValue).split('/').reverse().join('-')

    setValue(formattedDate)
  }
```
