### ISSUE TITLE
Handling two dates

### ISSUE THREAD

**Issue by ShokhsanamShirinkulova** [wojtekmaj/react-calendar#176]

**Comment by ShokhsanamShirinkulova** [comment]
Hello!
Thank you for your component.It works perfectly)
I wanted to ask that can active two dates one for today`s and another one is according to user selection active?
if it is possible it would be great!

**Comment by wojtekmaj** [comment]
React-Calendar can handle date ranges, but you can only pick one date/one date range. There are no plans of supporting more, and with current architecture I don't think that would be possible.

**Comment by ShokhsanamShirinkulova** [comment]
Thank you for response!

вс, 7 апр. 2019 г. в 20:56, Wojciech Maj <notifications@github.com>:
