### ISSUE TITLE
Only import calendar

### ISSUE THREAD

**Issue by andyfurniss4** [wojtekmaj/react-calendar#179]
I recently starting using this package because it appeared to be very small and provided me with what I needed - https://bundlephobia.com/result?p=react-calendar@2.18.1

However, having installed it, it seems it's much larger than I expected. Here's a screenshot of the code-split chunk it's in:

![image](https://user-images.githubusercontent.com/16683916/54703536-e2f91980-4b30-11e9-96c6-ea92ecb450da.png)

All I want is the calendar view really. I've disabled navigation because I have my own navigation so I don't need a lot of what's being imported. Is it possible to omit what I don't need? I started with 

`import Calendar from 'react-calendar';`

and then tried

`import Calendar from 'react-calendar/dist/Calendar';`

but they both import everything.

**Comment by wojtekmaj** [comment]
Hey,
I don't think that you actually "don't need a lot of what's being imported". Literally everything except for Navigation.js is necessary for the Calendar to run. It's just divided into smaller, manageable parts, but they are not removable.

`import Calendar from 'react-calendar';`

and 

`import Calendar from 'react-calendar/dist/Calendar'`

are equal.

You could, however, hack around and for example copy `Calendar.jsx` to your project, rename it to something like `CalendarWithoutNavigation.jsx` and modify to your liking, which would give you some savings. This is way beyond what is guaranteed by documentation so you must be aware that any update, even a minor one, could break this solution and you might need to update your file manually to get the newest updates.

Hope this helps!
