### ISSUE TITLE
Slow performance in formatLongDate

### ISSUE THREAD

**Issue by andrepcg** [wojtekmaj/react-calendar#180]
I'm noticing that when I open the calendar (it's behind a button click to open) there's a small delay. I've been trying to track the performance using the Chrome Dev Tools and found this (running React on production):

![image](https://user-images.githubusercontent.com/405387/55619692-27232580-5791-11e9-8607-5a14724df765.png)

`formatLongYear` is taking 116ms which is quite a bit. This happens rendering the Tile component.

Has this happened to anyone?

**Comment by bs85** [comment]
Same here, was doing some performance analysis and realized more than half of my (pretty heavy) app rendering was spent in those functions.

@wojtekmaj this looks like those functions are only used for aria purpose, could you confirm? If so, would you be ok to add a prop like `disableAria`? Tell me if you want a PR or if you'd like to do it yourself.

@andrepcg for now, dirty but works:

```
import * as DateFormatter from 'react-calendar/dist/shared/dateFormatter';
DateFormatter.formatLongDate = (_locale, date) => date.toISOString();
DateFormatter.formatMonthYear = (_locale, date) => date.toISOString();
DateFormatter.formatMonth = (_locale, date) => date.toISOString();
DateFormatter.formatWeekday = (_locale, date) => date.toISOString();
DateFormatter.formatShortWeekday = (_locale, date) => date.toISOString();
```

**Comment by wojtekmaj** [comment]
I tried to reproduce this and I can confirm that the performance of this function is poor. I'm not sure what we can do about this yet, but will experiment and let you know.

@bs85 Yes, at the moment they are used for accessibility purposes.

**Comment by andrepcg** [comment]
I only noticed this slowdown after upgrading our project dependencies last week.

No performance slowdown with packages:
- `"react": "^16.4.0"`
- `"react-calendar": "^2.16.1"`

Now I'm working with:
- `"react": "^16.8.6"`
- `"react-calendar": "^2.18.1"`

**Comment by hjyssg** [comment]
For my code, I just ignore formatLongDate when there is no locale.

```js
// ------------  Day.jsx

<Tile
    {...otherProps}
    classes={[
      ...classes,
      className,
      isWeekend(date, calendarType) ? `${className}--weekend` : null,
      neighboringMonth ? `${className}--neighboringMonth` : null,
    ]}
    date={date}
    formatAbbr={locale && formatLongDate}
```

**Comment by DrigerKhanh** [comment]
Hello, can you tell me how to use formatLongDate or any prop in React Calendar? i'm having trouble with returning exact date information

**Comment by wojtekmaj** [comment]
Okay, I think I've found the issue. Turns out, calling `date.toLocaleString(locale, options)` is significantly slower than calling `Intl.DateTimeFormat(locale, options).format(date)`, with format function cached.

Before:
```
Total JavaScript time: 3960ms
        dateFormatter: 1804ms (45%)
```

After:
```
Total JavaScript time: 1934ms
        dateFormatter:   91ms (4%)
```
