### ISSUE TITLE
onClickDay function day off issues

### ISSUE THREAD

**Issue by manjitha-teshara** [wojtekmaj/react-calendar#181]
if i click 29 get 28 as click same as all calendar numbers .how can fix this trouble.
![issues](https://user-images.githubusercontent.com/36306276/55680189-ed3e5480-5933-11e9-9394-690de56e5ce3.png)

**Comment by manjitha-teshara** [comment]
import React from "react";
import { MDBRow, MDBCol, MDBBtn } from "mdbreact";
import { MDBContainer } from "mdbreact";
import Calendar from "react-calendar";

 
class Calender extends React.Component {
    state = {
    date: new Date(),
    
  }
 
  onChange = date => this.setState({ date });
  
  callDay = (clikedDay) => { console.log(clikedDay)};//moment(day.dateString).format(_format)

  render() {
    return (
      <div>
        <Calendar
          onChange={this.onChange}
          value={this.state.date}
          onClickDay={this.callDay}
        />
      </div>
    );
  }
}


export default Calender;

**Comment by wojtekmaj** [comment]
Hi,
your browser displays `Date()` in GMT, and not in your local timezone. React-Calendar always uses local time, not GMT or any other timezone. The date is fine - check getMonth, getDate, getHours methods.
