### ISSUE TITLE
Feature proposal for CSS in JS users

### ISSUE THREAD

**Issue by trevordmiller** [wojtekmaj/react-calendar#182]
First off, thank you so much for wonderful lightweight, a11y, i18n components! They are fantastic.

I know there is the unstyled export that can be used from scratch which is great. What does everyone think about adding CSS in JS support for users who don't use .css? (styled-components, emotion etc).

**Comment by trevordmiller** [comment]
Looks like this is possible with the existing CSS classnames using styled-components: https://github.com/styled-components/styled-components/issues/728#issuecomment-312414854. Although having a declarative API would be nice, this works for me as a workaround.

**Comment by wojtekmaj** [comment]
Hmmm, I only have experience with styled-components from one project, but styled(ComponentName) seems to be a way to go to style React-Calendar as well. What improvements would you like to see?
