### ISSUE TITLE
DefaultDetail as a new prop

### ISSUE THREAD

**Issue by oliverdendis** [wojtekmaj/react-calendar#187]
Thanks for great calendar component 👍 

I really like the props `maxDetail` and `minDetail`. Sometimes, I really miss something like `defaultDetail`, in some cases like date of birth it is much better for users (we have tested it on UX tests) to set default detail to year, because user firstly chooses year then month and after that day, which can be annoying when user has days as default detail.

There are some solutions available which allow that feature (e.g air-datepicker) but only in jQuery. Generally, there is lack of react datepickers with it and it can be a really useful enhancement.

I would like to create a PR for that, what do you think about it @wojtekmaj ?

**Comment by wojtekmaj** [comment]
Investigated; we already have this, but it's called `view` and not `defaultView`. Just checked; definitely works :) Try e.g. `view="decade"`.
