### ISSUE TITLE
Type clash between react-calendar and react-date-picker

### ISSUE THREAD

**Issue by archer87pl** [wojtekmaj/react-calendar#19]
When two packages are installed then following type clash exists

Packages versions:
 "react-calendar": "^2.7.0",
 "react-date-picker": "^6.5.0"

Why aren't they declared inside module?

```ERROR in \node_modules\react-calendar\index.d.ts
(3,6): error TS2300: Duplicate identifier 'Detail'.

ERROR in \node_modules\react-calendar\index.d.ts
(4,6): error TS2300: Duplicate identifier 'DateCallback'.

ERROR in node_modules\react-date-picker\index.d.ts
(3,6): error TS2300: Duplicate identifier 'Detail'.

ERROR in \node_modules\react-date-picker\index.d.ts
(4,6): error TS2300: Duplicate identifier 'DateCallback'.

**Comment by wojtekmaj** [comment]
Hmmm... My apologies for this. I thought these identifiers would be local. So, I believe changing their names would be sufficient to fix this?

**Comment by archer87pl** [comment]
I think so. You can change names or put them inside module.

**Comment by wojtekmaj** [comment]
Thanks. I'll fix that today evening :)
