### ISSUE TITLE
Ability to add week row wrapper

### ISSUE THREAD

**Issue by kwokhou** [wojtekmaj/react-calendar#191]
Is there a way to wrap the whole week row with a wrapper? So that it's easier to highlight entire week.

![image](https://user-images.githubusercontent.com/136314/57830975-5db77b80-77e6-11e9-882a-5eb208b1242b.png)

**Comment by wojtekmaj** [comment]
No, there is no such possibility. I could add week number to arguments passed to `tileClassName`, but it's fairly complicated logic and not sure if it would help.

**Comment by kwokhou** [comment]
I tried the week number approached, but can't get the all siblings to highlight on `hover`, only the "after" siblings can be targeted.

**Comment by wojtekmaj** [comment]
Ah, highlight on hover! I don't see how I could be able to achieve this either. I thought you're speaking of highlighting based e.g. on external data.
