### ISSUE TITLE
Replace previous/next buttons

### ISSUE THREAD

**Issue by m4ttheweric** [wojtekmaj/react-calendar#193]
I am wanting to replace the default buttons being used for month navigation. I can pass them through as "label" but then you get ugly nested buttons in buttons.

Can you make an option for supplying React nodes to replace the UI buttons? This would be especially helpful when using a UI library in order to keep look/feel consistent by using a button that fits in with other pages.

**Comment by wojtekmaj** [comment]
You can supply any button content, but not buttons themselves. Replacing the buttons completely would likely break the styling and cause problems with navigation working. What are you trying to achieve by replacing the buttons entirely?

**Comment by m4ttheweric** [comment]
Well, I am using react-calendar within a material-ui project, and the navigation buttons don't conform to the styles/animations that are used throughout the project. I would like to be able to use a material-ui button instead. If I pass a material-ui button as button content, you get some strange nested button behaviors as well as some unwanted css. I could overwrite the css, and then live with the nested button situation, but it seems like passing in a React node could be easily implemented and any event listeners or built in behaviors could be spread onto the passed node.

**Comment by henryw4k** [comment]
I want to achieve the same thing that @m4ttheweric mentioned. I have a workaround, but definitely not ideal. Essentially I'm hiding the titlebar, pointing a ref to the calendar, and then controlling those buttons. Let me know what you guys think.



        //contructor
        this.myCalendar = React.createRef();
        
        
        <button onClick={()=>{
          const ref = this.myCalendar.current;
          ref.childNodes[0]?.childNodes[3]?.click()
        }}>Next Month</button>

        //CSS to hide the title bar    
        <Calendar
          className={reactCalendar}
          showNavigation={true}
          onChange={this.handleChange}
          value={value.toDate()}
          view="month"
          calendarType="US"
          inputRef={this.myCalendar}
          showFixedNumberOfWeeks={true}
        />

**Comment by daveteu** [comment]
by using activeStartDate props, you can set the current month/year. So you can make it a controlled component.

**Comment by henryw4k** [comment]
The next/prev buttons allow the user to jump to different months without having an active selection in the new month they are currently on. Correct me if I'm wrong, but I don't think you can replicate that by tinkering with the `activeStateDate` and `value`.
