### ISSUE TITLE
Prevent range selection with overlapping months from changing month view?

### ISSUE THREAD

**Issue by jakerainis** [wojtekmaj/react-calendar#199]
First off, thank you so much for all of your hard work. This has been an amazing addition to my project!

I have a scenario in which I'm showing neighboring month days and allowing a user to select a range. If they select a day-range where the days fall in two different months, the month view automatically switches to the month of the starting date in that range.

For example, if the active month is June, and the user selects a range of May 29th to June 8th, the active month switches to May. I'm assuming this is deliberate, but I was wondering if there was a way to _not_ switch the month of if some days from a neighboring month are selected? In my use-case, the switch isn't desirable and results in somewhat of a jarring experience.

I apologize if this has been addressed somewhere, but I'm combed the documentation and existing issues and I didn't come across anything related.

Thanks!
Jake

**Comment by wojtekmaj** [comment]
Hi,
the "auto switching" is is a result of the following logic:

1. If value is set, display whatever view that would contain the given value.
2. If there's no value, then try and display view based on `activeStartDate` prop.
3. If all else fails, just display whatever view that would contain today's date.

I don't think there would be an easy way to change this :(

**Comment by jakerainis** [comment]
Okay no worries, thank you for taking the time to reply! :)

**Comment by wojtekmaj** [comment]
Hi @jakerainis, I hope you will find changes described in #216 interesting.
