### ISSUE TITLE
Day labels

### ISSUE THREAD

**Issue by tuxd** [wojtekmaj/react-calendar#200]
Hi, is there an option to change the day labels from MON, TUE, WED to M, T, W etc?

**Comment by tuxd** [comment]
Sorry nevermind, I've figured it out now, using moment

**Comment by ArmandoAmador** [comment]
@tuxd Can you explain how you changed it to M, T, W?

**Comment by tuxd** [comment]
I just did a .toString().slice(0, 1) on the variable I passed to formatShortWeekday

**Comment by ArmandoAmador** [comment]
@tuxd thanks for the response. I ended up doing this

```
formatShortWeekday={(locale, date) => [ `S`, `M`, `T`, `W`, `T`, `F`, `S` ][date.getDay()]}
```

**Comment by tuxd** [comment]
Nice that's a bit more elegant than what I did :)

**Comment by zorfling** [comment]
You could also do it like this using [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString):
`formatShortWeekday={(locale, date) => date.toLocaleString(locale, { weekday: 'narrow' })}`
