### ISSUE TITLE
How should I set title from sunday when I use the Chinese locale

### ISSUE THREAD

**Issue by xwjla** [wojtekmaj/react-calendar#210]
Now it start from Monday, 
and can I use '一' instead of '周一'?
Looking forward to your answer, thank you!
![image](https://user-images.githubusercontent.com/21350855/61508414-4c743080-aa1c-11e9-9971-beeef9f2edd1.png)

**Comment by wojtekmaj** [comment]
Doesn't that mean "one" and not "Monday"? 🤔 

Anyways, you can use `formatShortWeekday` prop to overwrite default behavior, which is determined automatically using [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat). More on that on README.

Happy coding!
