### ISSUE TITLE
Navigating (jumping) to specific date

### ISSUE THREAD

**Issue by mmiocevic** [wojtekmaj/react-calendar#211]
I was wondering is there possibility to do something like this:
(Let's imagine that custom footer is added below react-calendar component with "Today" button which selects today's date)
User opens calendar (used as picker e.g.), drills to year view, then decade view and then century view and now user clicks "Today" button and goes to month view with today's date being currently selected.

I could not find solution to this when using value and activeStartDate props.

Thanks :)

**Comment by wojtekmaj** [comment]
There's no such possibility now if a date is selected. With that in mind, I think we should go with implementing `defaultActiveStartDate`/`activeStartDate`, `defaultValue`/`value` to make it possible to use React-Calendar as a controlled element.

**Comment by wojtekmaj** [comment]
Hmm, you could change `view` and `activeStartDate` props on "Today" button click, but it's a little tricky with React-Calendar 2.x, since the value in React-Calendar's state is only updated when props change.

Look for #216 👀

**Comment by mmiocevic** [comment]
Thank you for your answer.

I did this (maybe not happiest solution but it works and only month and year views are used):
`
onToday = () => {
      ...
      this.navigateToCurrentDate(today);
   };

   navigateToCurrentDate = (today) => {
      const calendarReference = this.calendarReference;
      // this part below for changing it if you are on month view
      calendarReference.setActiveStartDate(this.getFirstDayOfCurrentMonth(today));

      if (this.state.currentView === 'year') {
         // literally clicking current month to open view with dates
         ReactDOM.findDOMNode(calendarReference)
            .getElementsByClassName(this.MONTH_TILE_CLASS_NAME)[today.monthValue() - 1]
            .click();
      }
   };
`

Everyone please have in mind that this snippet is different than actual implementation (and simplified).

**Comment by jgreen7773** [comment]
The fix would be to make another attribute that has the exact same function as `activeStartDate`, yet it doesn't disable month navigation, and can be used in conjunction with `value` and `onChange`. Just name it like `monthlyNavigationFollowsValue`, so the month that pops back up as you click on the calendar, is the same month where the value is set. Just messing with the activeStartDate functionality with value, and onChange causes black and white functionality where you either have it with one, or you don't with the other. It's too bad. I'm all over this issue and I haven't found a work around yet.
