### ISSUE TITLE
Disable sundays?

### ISSUE THREAD

**Issue by Mawaheb** [wojtekmaj/react-calendar#213]
Hi,

Is it possible to disable Sundays in the calendar?

**Comment by wojtekmaj** [comment]
Use `tileDisabled` prop and write a function that given Sunday (use `date.getDay()`) returns `true`.

**Comment by Mawaheb** [comment]
Thanks for the reply.

What i meant, is more like, every Sunday, or every weekend is disabled.

**Comment by wojtekmaj** [comment]
`tileDisabled` function is called for every tile being rendered, so you have the possibility of disabling any tile you want.

**Comment by vivek25constants** [comment]
I'm doing some like `tileDisabled={({ date }) => date.getDay('Sunday')}` it greys out every other day other than sunday, how do I do the opposite?

**Comment by wojtekmaj** [comment]
`date.getDay()` returns current day index starting with Sunday. You want to do `date.getDay() === 0` instead.

**Comment by darshantogadiya** [comment]
> I'm doing some like `tileDisabled={({ date }) => date.getDay('Sunday')}` it greys out every other day other than sunday, how do I do the opposite?

You can do `tileDisabled={({ date }) => !date.getDay('Sunday')}` so it's disable all sunday

**Comment by kdudhat** [comment]
> I'm doing some like `tileDisabled={({ date }) => date.getDay('Sunday')}` it greys out every other day other than sunday, how do I do the opposite?

You can do tileDisabled={({ date }) => !date.getDay('Sunday')} so it's disable all sunday.
