### ISSUE TITLE
Select weeks by clicking on week numbers?

### ISSUE THREAD

**Issue by jordaofranca** [wojtekmaj/react-calendar#215]
Nice job with the react-calendar!

I was trying it and had some thoughts about being able to click on week numbers, and maybe select a week range.

Keep doing this amazing job.

**Comment by wojtekmaj** [comment]
There's already `onClickWeekNumber` function, so you might play around with it to select a given week based on the data being passed (`weekNumber`, `date` of the start of the week`).
