### ISSUE TITLE
Published version has old version of dist

### ISSUE THREAD

**Issue by felixmosh** [wojtekmaj/react-calendar#220]
Hi, 
First of all thank you for this awesome lib!

I've encountered with some weird issue, I wanted to render divs instead of buttons, saw in the [source code](https://github.com/wojtekmaj/react-calendar/blob/master/src/MonthView/WeekNumber.jsx) that in (v2.19.0) if there is no click callback it renders `div`s.

I've rendered the `MonthView`  and got buttons, looked at the source code, and it is different.
![image](https://user-images.githubusercontent.com/9304194/62058629-70a8ec00-b22a-11e9-8756-84ec3db56da7.png)

Can you republish a correct version :]

**Comment by wojtekmaj** [comment]
That looks like a correct source to me.
You can't use `div` with `onClick`. This would be inaccessible.

**Comment by felixmosh** [comment]
Opss, Looks like I missed it... closing, irrelevant.
