### ISSUE TITLE
wrong inline style calculation with RTL layout

### ISSUE THREAD

**Issue by felixmosh** [wojtekmaj/react-calendar#222]
Hi, 

When the layout is based on RTL (right-to-left) & `showNeighboringMonth={false}` the calculation of `margin` of the first item is hard coded to **left**, this makes the calendar looks like:

![image](https://user-images.githubusercontent.com/9304194/62117715-16a93480-b2c5-11e9-8ee9-cdaa64745bb0.png)

instead of that it should be `margin-right`.

**Comment by felixmosh** [comment]
I've found that with css grid it can be solved with css!
https://zellwk.com/blog/calendar-with-css-grid/

**Comment by felixmosh** [comment]
Any updates on this?

**Comment by wojtekmaj** [comment]
I think we could use margin-block-start to fix this. But margin-left would need to stay for compatibility reasons, so margin-block-end would need to reset it.

**Comment by felixmosh** [comment]
Why not css grid? 🙂

**Comment by wojtekmaj** [comment]
Fixed via #841
