### ISSUE TITLE
What is the final minified size of react-calendar?

### ISSUE THREAD

**Issue by Hubro** [wojtekmaj/react-calendar#225]
I'm considering switching from bulma-calendar to react-calendar in my app, as bulma-calendar is by far the largest component in my application (588K, 236K after minification).

I can't find any information about what size I can expect react-calendar to be after bundling and minification, so I'm hesitant to switch, as it could be a lot of wasted effort.

Could you add some information to README about how much one should expect react-calendar to affect the size of the final bundle? (I assume it depends on how many locales should be bundled etc.)

**Comment by wojtekmaj** [comment]
Hi,
currently unminified `dist` folder (the only one that contains any files that may end up in your bundle) is 121 594 bytes. I don't have time to do any tests but with the same minification rate as the one you stated (60%) you should be looking at something around 48 803 bytes after minification.

I won't add that info to README as this changes with every build (although I'm making efforts to make it _smaller_, not larger), but I hope you'll find this information helpful.

We will be switching to React Hooks soon, which will make React-Calendar even smaller, follow #216 for updates.

**Comment by Hubro** [comment]
@wojtekmaj Very nice, thanks!

I still think you should add *some* information about size though, even if it's just approximate. If the average developer is anything like me, the size impact of the final bundle(s) is a big part of choosing libraries, and having some information in the README is super convenient.

**Comment by wojtekmaj** [comment]
I will add bundlephobia badge, but they don't seem to measure the bundle size well as of now. Perhaps that's because we only ship CommonJS modules as of now. So this may change with React-Calendar 3.x :)
