### ISSUE TITLE
How to get the hover date

### ISSUE THREAD

**Issue by mikeyyyzhao** [wojtekmaj/react-calendar#229]
I've read the documentation and still confused about the purpose of hover and how we should use it. If I want to access the date over which the user is hovering over, how would I do that? 

I already tried accessing the calendar's state through ref but there's no hover in state. I've also tried calling a function through the hover prop. The documentation isn't clear on how it's supposed to be used. Since I'm trying to detect the current date that the user is hovering on, is that possible through hover? If so, could someone provide a code sample? Thanks in advance!

**Comment by mikeyyyzhao** [comment]
Got this working by passing in onMouseEnter through tileContent

**Comment by jaskirat1120** [comment]
@mikeyyyzhao Can you help me out here I want to change some text in different span when I hover in date.
