### ISSUE TITLE
[Question] How to show the calendar inline (always in the open state)?

### ISSUE THREAD

**Issue by christiankaindl** [wojtekmaj/react-calendar#230]
I looked into the docs, but didn't find anything related.

Is it possible to display the calendar in it's open state without it closing when the user clicks somewhere else?

**Comment by wojtekmaj** [comment]
The calendar doesn't close, maybe you mean some other package that may use React-Calendar and close it on clicking outside?

**Comment by christiankaindl** [comment]
Oh, I see. You're right, the question is actually related to react-datetimerange-picker. I'll re-raise the question there. Thanks!
