### ISSUE TITLE
Version 2.19.1 breaks IE11

### ISSUE THREAD

**Issue by montogeek** [wojtekmaj/react-calendar#232]
Hello!
After updating to version 2.19.1 from version 2.19.0. I got the following error in IE11:

![image](https://user-images.githubusercontent.com/1002461/63927047-3a3ed680-ca4d-11e9-9c71-75e5dbe05d5e.png)

This function is used by `TileGroup` component.

![image](https://user-images.githubusercontent.com/1002461/63927073-4c207980-ca4d-11e9-88c5-cb9afd963489.png)

But I know that this isn't your code, it is code by Babel transformation, so it seems related to your change log entry "Syntax optimizations to make Babel output smaller.".

While checking [changes](https://github.com/wojtekmaj/react-calendar/compare/v2.19.0...v2.19.1) between these 2 versions you update Babel related libraries.

This function implementation is really different between these 2 versions:
![image](https://user-images.githubusercontent.com/1002461/63927687-7d4d7980-ca4e-11e9-8e27-645f9d18ac32.png) and incompatible with IE11.

Do you think it is possible to revert this change or would you say to don't support IE11?

**Comment by montogeek** [comment]
I have good news, this was fixed already in:
https://github.com/babel/babel/pull/10171 and released in https://github.com/babel/babel/releases/tag/v7.5.2

So, Could you please upgrade to that Babel version?

**Comment by montogeek** [comment]
According to [this](https://github.com/babel/babel/issues/10166#issuecomment-509765164) comment, it seems better to update to 7.5.4

**Comment by wojtekmaj** [comment]
Thanks for letting me know about this problem. I'm on it.

**Comment by wojtekmaj** [comment]
v2.19.2 is out and should have this issue fixed. Sorry for the trouble.

**Comment by montogeek** [comment]
@wojtekmaj Thank you!
