### ISSUE TITLE
Past date class

### ISSUE THREAD

**Issue by glenn-allen** [wojtekmaj/react-calendar#234]
I'd love to be able to style past dates differently, but still allow past dates to be selected (so I can't use `minDate` to solve this use case).

I'm wondering if you'd consider adding a class like "react-calendar__tile--past" for any past date?

Thanks for the great library!

**Comment by wojtekmaj** [comment]
Hi,
use `tileClassName` for that. Something like:

```js
tileClassName={({ date }) => {
  if (isDateInThePast(date)) {
    return 'react-calendar__tile--past';
  }
  return null;
}}

**Comment by glenn-allen** [comment]
Oh wow, pretty embarrassed I missed that, sorry for wasting your time but thanks for the response and again, thanks for the fantastic library!
