### ISSUE TITLE
Property 'ref' does not exist on type

### ISSUE THREAD

**Issue by JosephNK** [wojtekmaj/react-calendar#235]
![스크린샷 2019-09-06 오후 8 58 24](https://user-images.githubusercontent.com/1622085/64426329-3cf29900-d0e9-11e9-899c-e02eb2a0d0f2.png)

FYI I am using typescript.

I think 'ref' is not defined.

**Comment by wojtekmaj** [comment]
Closed because of #273

**Comment by wojtekmaj** [comment]
FYI, React-Calendar is now natively in TypeScript, as of #785, coming to npm very soon.
