### ISSUE TITLE
Locale didn't change years A.D to Buddhist Era (BE).

### ISSUE THREAD

**Issue by X1ZERO** [wojtekmaj/react-calendar#238]
<img width="273" alt="2019-09-13_11h25_06" src="https://user-images.githubusercontent.com/49974310/64837532-2aacb980-d619-11e9-8dcd-18ffc4782c65.png">

I use locale for Thailand.

it use Buddhist Era.

this is my code:
`<Calendar
              locale='th-Th'
              calendarType="US"
            />`

<img width="274" alt="2019-09-13_11h23_55" src="https://user-images.githubusercontent.com/49974310/64837611-8bd48d00-d619-11e9-9eab-d4d29d3e1fe5.png">

And in the month view, it change to Buddhist Era (BE), but in year view, decade view and century view, it didn't change.

<img width="274" alt="2019-09-13_11h24_09" src="https://user-images.githubusercontent.com/49974310/64837634-a9095b80-d619-11e9-91a4-911505fae54b.png">

<img width="273" alt="2019-09-13_11h24_26" src="https://user-images.githubusercontent.com/49974310/64837639-ad357900-d619-11e9-818f-ac9a33a968d3.png">

**Comment by l2el3er** [comment]
god bless !!
i have this problem too ._.

**Comment by wojtekmaj** [comment]
Wow! I've learned so much about world calendars when working on this project. Now there's another thing :)

I'll be happy to fix that.
