### ISSUE TITLE
Unablr to resolve module Calendar.css error

### ISSUE THREAD

**Issue by fithaN** [wojtekmaj/react-calendar#24]
Hi ,
I am getting below error when trying to use Calender.

<img width="295" alt="screen shot 2018-01-08 at 7 19 38 pm" src="https://user-images.githubusercontent.com/33620488/34663080-f3c27b92-f4a8-11e7-8d0e-336477541e2c.png">

**Comment by wojtekmaj** [comment]
Hi @fithaN,
If you are using LESS/SASS or other styling methods that is not raw CSS, your bundler config may not include handling CSS files.

Is that React Native am I seeing?) If so, I'd love to know more about your experience with React-Calendar.

**Comment by fithaN** [comment]
yes .its react native

**Comment by wojtekmaj** [comment]
Hmm. I'm afraid that react-calendar was not made with React Native in mind, so while you can do some research on your own, or perhaps a fork, it's unlikely that you would get React-Calendar working. It relies on web technologies a lot.
