### ISSUE TITLE
Full Yearly View to Print the Yearly calendar

### ISSUE THREAD

**Issue by Venmathi2510** [wojtekmaj/react-calendar#240]
Is there a way we can show the calendar like a full view of an year with all month with week numbers in detail on it. PFA. 
![image](https://user-images.githubusercontent.com/40182461/65269502-e882ec80-dade-11e9-8561-0e035cdd03c6.png)

Please help me how we can achieve that behaviour and if not available will it be possible to do so .

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-calendar/wiki/Upgrade-guide-for-React-Calendar-1.x-users#displaying-multiple-months
