### ISSUE TITLE
How to display only current month and disable all clickables(year,month, next, prev...etc) except day?

### ISSUE THREAD

**Issue by srikanthpathlavath** [wojtekmaj/react-calendar#242]

**Comment by harish137** [comment]
You can achieve this using the following props :

```
<Calendar
minDetail="month"
maxDetail="month"
defaultView="month"
showNavigation = {false}
/>

```
Then you will be able to see only current month dates.

**Comment by giacomocerquone** [comment]
I think this issue can be closed then :) @wojtekmaj anyway if you're looking for maintainers that can help, I can help managing the issues. Hit me up in case!

**Comment by wojtekmaj** [comment]
@giacomocerquone I do have issues finding free time to address the issues lately, so any community support is highly appreciated :) Thanks!

**Comment by giacomocerquone** [comment]
Nice. Sadly not being a contributor yet doesn't allow me to put labels on issues, but still I'm going to review some of them

**Comment by sushmitg** [comment]
I added `minDetail="month"` so that it doesn't drill up but I also want the click callback. how do I do that?
