### ISSUE TITLE
Wrong date selected if zero before month

### ISSUE THREAD

**Issue by madroneropaulo** [wojtekmaj/react-calendar#244]
Say I set a new date "2019-09-24" the selected date is by 1 day wrong, and it shows 23. But if I set the value as "2019-9-24" (note the missing zero before 9) Everything works fine. Is something I'm doing wrong?

I'm using the latest 2.19.2 version.

**Comment by wojtekmaj** [comment]
Browsers interpret the date `"2019-09-24"` as ISO (rightfully so), and `"2019-9-24" as a local date in not-really-ISO-but-ISO-like format. ISO dates are, by definition, in UTC+0:00 timezone, while non-ISO dates are, by definition, in your local timezone. 

Please note that "2019-9-24" is not really a valid date format and browsers will interpret it differently; Firefox will treat is like ISO, Chrome will show it with a time difference you described.

**Comment by madroneropaulo** [comment]
Thank you @wojtekmaj but this does not solve my issue. I still getting the wrong selected date in the calendar. I pass "2019-09-24" as the date value, but it shows 2019-09-23
![Screenshot from 2019-09-26 07-44-56](https://user-images.githubusercontent.com/4364107/65689049-ca167700-e031-11e9-83f6-01b9f1f38ed6.png)

**Comment by wojtekmaj** [comment]
Judging by this behavior, you're in UTC-xx:xx timezone, somewhere in America :) Date you're providing is interpreted as 2019-08-04 00:00 UTC which happens to still be "yesterday" at your place. I suggest you to parse the date yourself to a local date before passing it to React-Calendar or using React-Date-Picker which uses React-Calendar under the hood :)
