### ISSUE TITLE
Typo in className

### ISSUE THREAD

**Issue by DDDDDanica** [wojtekmaj/react-calendar#245]
Hey there,
Thanks for the amazing work on this library and whole project.
I found a small typo and it will be easy to fix.
https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less
Line 92:  `&__tile` => `&__title`.
Thanks a lot. ❤️

**Comment by wojtekmaj** [comment]
Hey,
I don't think that's a typo. `.react_calendar__tile` refers to tiles on month view, year view and so on. For example, January month view has 31 tiles, with numbers 1-31 :)

**Comment by DDDDDanica** [comment]
Thanks ! It's such an unusual name.
