### ISSUE TITLE
Customize styling for range select

### ISSUE THREAD

**Issue by DDDDDanica** [wojtekmaj/react-calendar#246]
Thanks for the amazing library. 
I am struggling a bit to change the styles when comes to date-range mode, aka when `selectRange` is set as true.
Eg: I want to have 

- a different hover color for hovering end dates
- a different hover color for days between start & end date when hovering

So i found out all the hovered date has `.tile--hover` class, can you make a different classes for them?

Or maybe I missed some tricks to target them.
Thanks for your help in advance :)

**Comment by wojtekmaj** [comment]
> a different hover color for hovering end dates

Range end dates get `.react-calendar__tile--rangeEnd` class, so you can style `.react-calendar__tile--rangeEnd:hover`.

> a different hover color for days between start & end date when hovering

Range start & end dates get `.react-calendar__tile--rangeBothEnds` class, so you can style `.react-calendar__tile:not(.react-calendar__tile--rangeBothEnds):hover`.

**Comment by DDDDDanica** [comment]
Thanks a lot,
I found out using the following selectors could do the trick：
```
"&.react-calendar__tile--rangeStart:not(.react-calendar__tile--rangeBothEnds), &.react-calendar__tile--rangeEnd:not(.react-calendar__tile--rangeBothEnds)
```

and 
```
& .react-calendar__tile--rangeStart:not(.react-calendar__tile--rangeEnd), & .react-calendar__tile--rangeEnd:not(.react-calendar__tile--rangeStart)```

Thanks for your help :)
