### ISSUE TITLE
Problem with activeStartDate and value

### ISSUE THREAD

**Issue by DevAndreyBilchenko** [wojtekmaj/react-calendar#250]
If I using 'value' and 'activeStartDate' together, 'value' controll displaing month permanently, and calendar ignore any values in activeStartDate.
I'm try realize combined calendars like in Worksection reports (2 calendar has one value and different view area), this problem stuck my work. Please help 

```
<Calendar
  value={calendarTo}
  activeStartDate={displayTo}
  nextLabel={''}
  prevLabel={''}
  showNeighboringMonth={false}
  locale={'en-EN'}
  formatShortWeekday={(locale, date) => format(date, 'eeeee')}
  returnValue={'range'}
  selectRange
/>
```

**Comment by wojtekmaj** [comment]
This is a limitation of React-Calendar 2.0 and this will be resolved in an upcoming release.

**Comment by DruceCss** [comment]
> This is a limitation of React-Calendar 2.0 and this will be resolved in an upcoming release.

Thank for fast answer
