### ISSUE TITLE
[Question] Can we use Appointment App with React-calendar (two features needed to confirm)?

### ISSUE THREAD

**Issue by syang** [wojtekmaj/react-calendar#252]
We wanted to embed an appointment scheduling page in our webapp. I envision that it will be very similar to what calendly appointment page looks and feels (but [Calendly](www.calendly.com) only provides integration of Iframe, which I feel very hard to make the seamless integration that I expected here).

So I came to react-calendar, and I wanted to:

1. Make the front-end component to talk to a calendar API backend, such as Google Calendar API, my question for this item is 'is there an example that I can start with'?

1. make the front-end component to have the weekly view (instead of monthly view) so that the default view can show the time slots in the hour bases for each day.

I'd appreciate if anyone who is familiar with this library to chime in and help to answer.

**Comment by wojtekmaj** [comment]
Component won't "talk" to any external calendar APIs, but you can implement it by yourself and use tileContent to populate the tiles with whatever you need.

No, there's no weekly view (tracked: #70). Sorry!
