### ISSUE TITLE
Controllable hover event 

### ISSUE THREAD

**Issue by DDDDDanica** [wojtekmaj/react-calendar#254]
Hey,
Thanks for the amazing work and quick response again.
I'm trying to do some keyboard control like [this](https://www.flightnetwork.com/) from my own input. 
Just wonder if there's an exposed function to allow us to control `hovered classes` for tile by any chance?
Thanks a lot in advance.

**Comment by wojtekmaj** [comment]
Did you figure it out? Why it's closed?

**Comment by DDDDDanica** [comment]
Hey @wojtekmaj I managed to do something like this to add additional class to day that's selected by keyboard :)

```
let keyboardAbbr = ReactDOM.findDOMNode(calendarRef.current).querySelector(
      `[aria-label="${keyboardSelectedAbbr}"]`
    );
    if (keyboardAbbr) {
      keyboardAbbr.parentNode.className += " keyboardSelected";
    }
```
