### ISSUE TITLE
Select all dates that match particular weekday of the month by clicking on week day (monday, tueday) 

### ISSUE THREAD

**Issue by TargiX** [wojtekmaj/react-calendar#255]
So I need to select all dates that match particular weekday of the month by clicking on week day (Monday, Tuesday) on the top of calendar .  I this possible to make in some more or less simple way?  Thanks.
![calendar](https://user-images.githubusercontent.com/17446822/66479750-eea53100-eabe-11e9-8885-e07b7c05c989.jpg)

**Comment by giacomocerquone** [comment]
As you can see here https://github.com/wojtekmaj/react-calendar/blob/e226402678123e1006242d5f4268077d83af7da3/src/MonthView/Weekdays.jsx#L40 those elements have no event handler attached and it's not even a clickable element.

One weird and horrifying solution could be to add a click event handler on the calendar and check if the clicked element has the className defined by this lib and then somehow pass an array of those dates as value.

@wojtekmaj correct me if I'm wrong. In that case, we could provide a click handler or a custom rendered component for the element and this issue would be marked as an enhancement.
