### ISSUE TITLE
Fixed height

### ISSUE THREAD

**Issue by nuthinking** [wojtekmaj/react-calendar#262]
Is there a way to fix the height of the whole calendar? I could see in #119 that the padding should be used to do that, but I would need also to know if the current month has 4, 5 or 6 rows. **react-calendar__month-view__days** doesn't add class names which could help. Ideas? Thanks!

**Comment by nuthinking** [comment]
Adding class names like **react-calendar__month-view__days--4weeks** or **react-calendar__month-view__days--5weeks** or **react-calendar__month-view__days--6weeks** would solve the issue I guess.

**Comment by nuthinking** [comment]
Too hackish? https://github.com/wojtekmaj/react-calendar/pull/263

**Comment by nuthinking** [comment]
Too hackish?

**Comment by wojtekmaj** [comment]
Hmmm, you can simply use `height` in CSS to do that, no? Simply measure the tile you have and multiply it by the number of rows you're trying to enforce. Also, mind `showFixedNumberOfWeeks` prop.

**Comment by nuthinking** [comment]
Oh, `showFixedNumberOfWeeks` is a good one! Thanks!

**Comment by shokhrukh1212** [comment]
I haven't found any ideal solution, but setting a big `font-size` property makes a text and a whole calendar look bigger
