### ISSUE TITLE
Is 2.19.2 published correctly?

### ISSUE THREAD

**Issue by mmiocevic** [wojtekmaj/react-calendar#264]
Hello,

when version 2.19.2 is cloned, it has got correct files (like showDoubleView feature).
When same version is installed via npm, then e.g. showDoubleView feature is not available.

How can I get version which has double view?

Thanks.

**Comment by mattirizarry** [comment]
I second this it would be really great to get this in the NPM version!

**Comment by wojtekmaj** [comment]
Newest version on GitHub is NOT 2.19.2. It's work-in-progress 3.0. That's why you see new features that are not published yet.
