### ISSUE TITLE
Calendar days position bug

### ISSUE THREAD

**Issue by Blaumaus** [wojtekmaj/react-calendar#268]
Sometimes days in the calendar are mixed up and become unusable (if I click on day, it switches month and so on).
This bug can be represented with the following code:
```
const Days = () => {
  const [date, setDate] = useState(null)

  return (
    <Calendar 
      onChange={setDate}
      // value={date}
    />
  )
}
```
![Screenshot](https://user-images.githubusercontent.com/35810911/68133488-62005e00-ff18-11e9-94df-1e519a6bd615.png)

**Comment by wojtekmaj** [comment]
Hey,
what was the issue? Can you share?

**Comment by Blaumaus** [comment]
Sorry for closing issue without bug explanation
The calendar was displayed like this when I spoofed my timezone
