### ISSUE TITLE
Is it possible to mark a whole week as active tile if selected a day in the calendar?

### ISSUE THREAD

**Issue by golditz** [wojtekmaj/react-calendar#27]
Hi, 
I am wondering if it is possible to mark a whole week as selected (like the date range) when I am selecting a day? 

The idea is to get a range from the start of the week to the end of the week when a user selected a day in the calendar.

Thanks in advanced,
Isaac

**Comment by wojtekmaj** [comment]
Hey @golditz,
this is quite specific use case so you would need to handle it by yourself. Perhaps something like this?

```js
onChange={clickedDate => {
    const beginWeek = getBeginOfWeek(clickedDate);
    const endWeek = getEndOfWeek(clickedDate);
    this.setState({ value: [beginWeek, endWeek] });
}}
```

Hint: methods for getting week start and end are available in react-calendar and aren't going anywhere soon, you can get it from my code source.

**Comment by golditz** [comment]
Fantastic answer ... TBH, I found this solution just 10 minutes before you submitted yours... :)))

However, when I click again on the selected day, the selected view is changed. 
Is there any idea why it is happening?

**Comment by wojtekmaj** [comment]
I'm sorry, I'm not sure what you mean. Could you elaborate?

**Comment by wojtekmaj** [comment]
Ah, thank you. I could reproduce this and this has to be fixed on my side; expect a fix soon. 

If you're interested, here's what happens:

* You click the date
* React-Calendar sets its value to the date clicked.
* Your onChange overwrites it with a week range.
* React-Calendar sets its value from props.
* You click the date once again
* React-Calendar sets its value to the date clicked.
* Your onChange gets the same dates again
* React-Calendar does not detect the change in props and thus does not update the value.

**Comment by wojtekmaj** [comment]
I have created a separate ticket for this error, please refer to it if you still have issues. Closing this discussion as I hope we have achieved what we wanted ;)

**Comment by wojtekmaj** [comment]
One final tip: Make sure to use showNeighboringMonth flag to, well, show neighboring month. This way it will always be clear that the whole week gets selected, and not only the days of the week in a given month.

**Comment by golditz** [comment]
Hi,

Did you make the update in the library?

Thanks in advanced,
Isaac

**Comment by wojtekmaj** [comment]
Yes, check out [v2.11.2](https://github.com/wojtekmaj/react-calendar/releases/tag/v2.11.2).

**Comment by golditz** [comment]
GREAT!!!

Thank you so much!
