### ISSUE TITLE
Move Typings to DefinitelyTyped

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#273]
React-Calendar 3.0 will not include TypeScript typings by default. This is because TypeScript popularity is still relatively low comparing to JavaScript community, and it became a major slowdown for React-Calendar's development. I'll be happy to see typings created in DefinitelyTyped.

Last tree with typings for reference: https://github.com/wojtekmaj/react-calendar/tree/6905e6998f66b1d976eec99d5369374390106208

**Comment by Guymestef** [comment]
PR created on DefinitelyTyped: [#43540](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43540)

**Comment by wojtekmaj** [comment]
Wooohooo! You're a hero!

**Comment by wojtekmaj** [comment]
PR got merged - thank you once again @Guymestef!

**Comment by Enfield-Li** [comment]
`npm i @types/react-calendar`

**Comment by wojtekmaj** [comment]
FYI, React-Calendar is now natively in TypeScript, as of #785, coming to npm very soon. As typings are now NOT manually created on the side, this is now helping, not slowing the project down. :)
