### ISSUE TITLE
Label for week numbers

### ISSUE THREAD

**Issue by bedakb** [wojtekmaj/react-calendar#274]
First of all, I want to say thanks for this nice calendar component.

I was wondering is there support for giving a label to the week numbers column, just next to day labels in the MonthView?

If not, is there a plan to add a feature like that? I'm open to help with implementation If needed, just let me know how API should look like.

Thanks in advance.

**Comment by wojtekmaj** [comment]
You mean something like this?

![obraz](https://user-images.githubusercontent.com/5426427/68991428-242bff80-085f-11ea-8221-463d081e1489.png)

I like this idea, shouldn't be too complicated to implement :)

**Comment by bedakb** [comment]
@wojtekmaj yes, that's exactly the thing I was asking for.

Thanks a lot 🙏

**Comment by andiCR** [comment]
I want to be able to select a week. There is an 'onClickWeekNumber' but I can't seem to get it to fire.

**Comment by Dodobrat** [comment]
Seems this feature is no longer available. Can it be added back by any chance?

**Comment by wojtekmaj** [comment]
It's actually just not merged yet. Need to write the tests.

**Comment by Dodobrat** [comment]
My bad. Thanks for the quick response.

**Comment by carestra** [comment]
Any plans to merge this enhancement into master?
