### ISSUE TITLE
Legacy docs link points to react-pdf

### ISSUE THREAD

**Issue by eternaldoctorwho** [wojtekmaj/react-calendar#279]
The link in the "Before You Continue" section of the README points to the wrong project.

It currently is:
`* [v2.x](https://github.com/wojtekmaj/react-pdf/blob/v2.x/README.md)`

It should be:
`* [v2.x](https://github.com/wojtekmaj/react-calendar/blob/v2.x/README.md)`

**Comment by wojtekmaj** [comment]
Oh, thank you! Fixed.
