### ISSUE TITLE
"ReferenceError: window is not defined" when rendering server side

### ISSUE THREAD

**Issue by darkbercislaw** [wojtekmaj/react-calendar#28]
Hi,

in the src/shared/locales.js the method getDefaultLocales assumes that window object is in scope, which is not true when rendering the component server side. Would it be possible to add an extra check for window object existence or solve it differently, so that there are no errors when rendering this awesome component server-side?

Thanks,
Robert

**Comment by wojtekmaj** [comment]
Thanks @darkbercislaw for the report! The issue has been fixed in version 2.11.1. Should you have any other issues or the fix didn't resolve the issue, let me know!
