### ISSUE TITLE
Unable to keep the selected date highlighted when the modal was closed

### ISSUE THREAD

**Issue by enarddpascua** [wojtekmaj/react-calendar#280]
Hi I attached the react-calendar to a modal, I think the modal shouldn't affect the Calendar. However, when I opened the modal and selected a date, then I closed it, then I opened it again, the calendar was back to the current date, and the highlighted date was gone. Please help. Is there a way I can maintain the selected date, whenever I close the modal?

 //showModalCalendar && (
   //     <>
     //     <MiniModal className="open-modal">
       //     <CalendarComponent setStartDate={setStartDate} id={id} startDate={startDate} /> //React-calendar
        //    <div className=" time-container">
          //</MiniModal>
       // </>

here is the react-calendar:
return <Calendar calendarType="US" locale="English" onClickDay={setStartDate} onChange={setEndDate} id={id} nextLabel="→" prevLabel="←" />

**Comment by Shubham-DK** [comment]
Any one looking into this issue??
