### ISSUE TITLE
Unable to clear selected range

### ISSUE THREAD

**Issue by Frankoloko** [wojtekmaj/react-calendar#281]
It is not possible to clear the selected range, or am I missing something?

```
dateRangeSelected = selectedDateRange => {
    this.setState({ selectedDateRange: null });
}

<Calendar
    onChange={this.dateRangeSelected}
    value={this.state.selectedDateRange}
    selectRange={true}
/>
```

This doesn't clear the selection

**Comment by wojtekmaj** [comment]
Hi,
have you tried using React-Calendar 3.0 beta as a controlled component? It should have this issue resolved.

**Comment by snikitina** [comment]
I have the same issue - I have the calendar with no initial selection (the 'Custom period' in the gif), but once I start interacting with it the `value` can never be reset to `null`. I'm using `react-calendar@3.0.0-beta.4`.

My simplified code looks similar to the above:

```
<FilterButton onClick={() => setDateRange(null)}>
  Custom period
</FilterButton>
<Calendar
  value={dateRange}
  onChange={value => setDateRange(value)}
  selectRange
  doubleView
/>
```

![range-reset](https://user-images.githubusercontent.com/3908566/70673974-8b12cc00-1cd8-11ea-9c91-054ecf2e2c97.gif)

**Comment by ifightcrime** [comment]
I know this is super old, but I figured it out! You need to pass an empty array to clear the dates. null or undefined wont cut it.

**Comment by arrmani88** [comment]
same here as @longlostnick 
any solution ?
