### ISSUE TITLE
How to show  a calendar with shorten Month names? 

### ISSUE THREAD

**Issue by akhilaudable** [wojtekmaj/react-calendar#292]
So far I am not able to figure out how to display short month names?  Like December -> Dec

![Screenshot from 2019-12-13 11-45-15](https://user-images.githubusercontent.com/17010730/70773732-418cb480-1d9e-11ea-9114-6b74c1ccefdb.png)

This is my code exaple

        formatMonth = () => {
          return (locale, date) => { month: 'short' }
        }

       render() {
        return (
          <CalendarInput
            value=''
            returnValue="range"
            calendarType="US"
            className={classes.calendar}
            onChange={() => {
              // Need to implement
            }}
            formatMonth={this.formatMonth}
          />
        );
       }

What am I missing?

**Comment by wojtekmaj** [comment]
That function is formatting month and year, so you're looking for `formatMonthYear`.

**Comment by akhilaudable** [comment]
Okay. Thank you. Can you tell me how to implement that with the same code above?

**Comment by wojtekmaj** [comment]
Probably something like

```js
formatMonthYear={(locale, date) => date.toLocaleString(locale, { month: 'short', year: 'numeric' )}
```

would suffice.
