### ISSUE TITLE
What event is fired on the click of the navigation bar (next2-button/prev2-button)?

### ISSUE THREAD

**Issue by syedmoulaali** [wojtekmaj/react-calendar#293]
It will be good to know which event is fired on the click of next and prev buttons

**Comment by syedmoulaali** [comment]
What i am trying to achieve here is we have onClickDay event which will happen on the click on day..I am interested in the next and prev button of the navigation bar

**Comment by wojtekmaj** [comment]
It's onActiveStartDateChange.
