### ISSUE TITLE
having multiple days highlighted

### ISSUE THREAD

**Issue by SocialCycle** [wojtekmaj/react-calendar#295]
I'm using the calendar to create custom sequences on different days of the week, but right now as far as I can tell you can only have 1 day highlighted at a time. I've tried passing in an array of dates to the value prop but that highlights days in between and eventually throws errors. I think having the ability to have multiple dates in the value prop each highlighted separately would be awesome. Thanks!!

**Comment by MentalN** [comment]
Having the same issue. Have tried disabling SelectRange, but it didn't work.

**Comment by wojtekmaj** [comment]
You can't technically select multiple days. You can select one or a range of days (or months, years, decades). However, you could keep track of selections on your own and use tileClassName to style selected days as you wish.
