### ISSUE TITLE
onActiveStartDateChange no longer called on Month view

### ISSUE THREAD

**Issue by echappen** [wojtekmaj/react-calendar#296]
It appears `onActiveStartDateChange` is no longer called when clicking previous/next arrows. We are using this on a Month view. 

Versions:
"react": "16.12.0",
"react-calendar": "2.19.2"

Otherwise we're really enjoying this calendar tool!

**Comment by echappen** [comment]
Bump

**Comment by Plaskullic** [comment]
It works after I updated to 3.0.0-beta

**Comment by echappen** [comment]
Thanks!

**Comment by jaymathew** [comment]
If onActiveDateChange doesn't work with 2.19.2, how do I update to beta 3.0 ?

**Comment by wojtekmaj** [comment]
onActiveStartDateChange is 3.x only thing. Look at 2.x docs if you need to know how 2.x would work :)
