### ISSUE TITLE
only get date and time, but not required timeZone

### ISSUE THREAD

**Issue by HarshilSolanki** [wojtekmaj/react-calendar#299]
Hii, i m used used this package and working properly but i was required only date and time but Timezone is bot require, so can you give me datetime string feature without timezone?? i was send the screen shot, what exactly getting from output when i was using dateRange 
![Screenshot from 2019-12-24 12-00-46](https://user-images.githubusercontent.com/47355993/71398159-88ec2e00-2645-11ea-8784-93192a31e325.png)
Example: "Fri Dec 20 2019 00:00:00 GMT+0530 (India Standard Time)" ==> Getting this string
and what i was need from you
Example: "Fri Dec 20 2019 00:00:00 GMT+0530"

**Comment by wojtekmaj** [comment]
What you're looking at is a human readable representation of Date() object, done by your browser. React-Calendar does not add any timezones on its own - it simply uses the local one.

Try `console.log(new Date())` in your browser.

**Comment by HarshilSolanki** [comment]
Hii my question for react-dateRange by mistake write on react-calender and
I want date in string but in new Date () I reacive full date string like
('standard time asia')
