### ISSUE TITLE
Select range and being notified every start/end date change, not only both

### ISSUE THREAD

**Issue by IceTrooper** [wojtekmaj/react-calendar#307]
Hi, is it possible to be notified every start or end date change when "selectRange" is true?
I want to update some components when user first clicks on startDate and update again when user clicks on endDate to select a range.

Example:
![obraz](https://user-images.githubusercontent.com/51023959/72818217-63b20600-3c6b-11ea-86f8-4e5d6e55948e.png)

1. Calendar without selected dates shows different number in the red circle for every tile/day. It says how many departures are on that day.
2. User clicks start date (departure date).
3. I call API, update some components and refresh numbers in the red circle for every tile in the calendar (now it shows how many returns are on this day).
4. User clicks end date (return date).
5. I call API again and that's it.

Is it possible to achieve this? How to do this?

**Comment by IceTrooper** [comment]
I worked out this problem with onClickDay event.

**Comment by wojtekmaj** [comment]
Nice! Can you share your solution with others? Sadly, React-Calendar does not support "work in progress" onChange for range selection.
