### ISSUE TITLE
Unclear whether Calendar is a controlled component or not

### ISSUE THREAD

**Issue by ksoldau** [wojtekmaj/react-calendar#308]
[The "Usage" example](https://www.npmjs.com/package/react-calendar#usage) makes it appear as though Calendar is a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) (where you have to pass an updated "value" through for the selected calendar day to change). However, the day seems to change even if I keep the "value" constant. 

Example setup where value stays constant, but the selected date still changes on click:
```
const date = new Date()
<Calendar
  minDetail="month"
  maxDetail="month"
  calendarType="US" // week starts on Sunday
  minDate={date}
  value={date} 
  onChange={handleChange}
/>
```

Is Calendar supposed to be a fully controlled component? Is the example incorrect? 

Thanks in advance for the clarification 😄

**Comment by wojtekmaj** [comment]
Hi,
this is one of the biggest confusions we've had with React-Calendar 2.x. We're fixing it with 3.x.

2.x is uncontrolled.
3.x can be both controlled and uncontrolled.

**Comment by ksoldau** [comment]
Thanks for the info!
