### ISSUE TITLE
Question: Clicking on days from a neighboring month doesn't render that month?

### ISSUE THREAD

**Issue by prina92** [wojtekmaj/react-calendar#31]
Hello,
first of all, thank you for this library.
I'm using it to create a small app like a schedule or agenda with learning purposes.
I've noticed that in your online demo when you click a day that belongs to another month (previous or next) it will take you to that month.
However I can't achieve this. I've looked at your sample and it's code and I've done the same but for some reason it doesn't work. The day gets selected but I have to manually change to the month from the navigation component.
I've checked the list of props and I didn't find one that changes that. Am I missing something here?
Here's my code so far:
```
import React from 'react';
import Calendar from 'react-calendar/dist/entry.nostyle';
import 'styles/calendarStyle.css';

export default class HomePage extends React.Component {
  state = {
    value: new Date(),
  }

  onChange = (value) => {
    this.setState({ value });
  }

  render() {
    const { value } = this.state;
    return (
      <div>
        <Calendar
          locale="es"
          onChange={this.onChange}
          value={value}
        />
      </div>
    );
  }
}
```
Thank you for this library and for your time!

**Comment by wojtekmaj** [comment]
You are doing everything right. Days from neighboring months are displayed, and they behave like all the other days, so they are active tiles and will not navigate you to previous/next months. This is by design. I'm not saying the design is right, just saying it was designed this way ;) Good catch, though. I'll see what we can do about it.

**Comment by prina92** [comment]
Oh I see
I still don't quite understand why is it working on the online demo though. If it weren't for that I wouldn't even asked.
Thank you for the quick reply!

**Comment by wojtekmaj** [comment]
Oh, you are right. Please forget about my last comment, which was *technically* right but not practically. I was able to reproduce your issue.

So what should be happening here is:

# You select a tile normally
# The value is updated in your component
# New value is being passed to the calendar
# The calendar realizes that the value has changed and it doesn't show the month on which a new value is
# The calendar switches to the next month

I'll fix this asap.

**Comment by wojtekmaj** [comment]
Hey @prina92, the new version with the fix, v2.12.0, just got out. Let me know what you think!

**Comment by nguyenkhoi2806** [comment]
Sorry @wojtekmaj  but in my version it's still bug

**Comment by wojtekmaj** [comment]
And which version are you using? How is the calendar implemented? It works in the current [test suite](http://projects.wojtekmaj.pl/react-calendar/test/).
