### ISSUE TITLE
What type should be value prop when selecting range

### ISSUE THREAD

**Issue by IceTrooper** [wojtekmaj/react-calendar#310]
In relation with #308 it's unclear what value should be passed to `value` prop when using `selectRange={true}`.
For now, I set value once as date object (when user select first date), then I set as an array of 2 date objects (when user select range). When clearing selection I set null.

Is it a good approach to change the type of the variable used as a value in Calendar component?

**Comment by wojtekmaj** [comment]
If value is a single value and selectRange prop was passed, this value will be treated as "date from" in unfinished range selection, I think.
