### ISSUE TITLE
Can i show react-calendar as a pop up ?

### ISSUE THREAD

**Issue by goxr3plus** [wojtekmaj/react-calendar#311]
Currently it is shown like that :

![image](https://user-images.githubusercontent.com/20374208/73163512-d2261680-40f8-11ea-810d-12b2b65d02af.png)

But i would like it to have a button which i have to click in order calendar to be shown as a pop up . I mean https://codepen.io/simeg/pen/mEmQmP

**Comment by wojtekmaj** [comment]
Of course you can. This package just shows the calendar itself, but you can put it in a popup if you want.

By the way, that's exactly what [React-Date-Picker](https://github.com/wojtekmaj/react-date-picker) is doing.

**Comment by goxr3plus** [comment]
@wojtekmaj  The problem is i just need React-Calendar  and not all the dependencies of React-Date-Picker :) .

Also React-date-picker doesn't have a property to just show the calendar . It also shows some extra stuff. 

It would be nice if react-calendar had a property called ( `showInPopUp`) .

By the way how i can do it by my self?

![2020-01-27_13-21-44](https://user-images.githubusercontent.com/20374208/73170806-00f7b900-4108-11ea-895c-bbe553c7c200.gif)

**Comment by wojtekmaj** [comment]
React-Calendar aims to do one thing and to do it right. There are tons of solutions, both custom and reusable, that helps you build a pop-up. Putting React-Calendar in this pop-up should be no different from putting an image of a potato inside. ;)

I'm sorry, I wish I could, but I can't code everything for everyone.

**Comment by goxr3plus** [comment]
@wojtekmaj  Understood :) , but in the same logic `React-Date-Picker` shouldn't be shown in popup ....

**Comment by goxr3plus** [comment]
If i make a pull-request will you consider it ? :)

**Comment by wojtekmaj** [comment]
React-Date-Picker shows a pop-up with React-Calendar.

What do you want to make a PR for?

**Comment by goxr3plus** [comment]
http://projects.wojtekmaj.pl/react-date-picker/ Oups now i see , this fits me , i think i was drunk and didn't show it correctly before :)

I was trying to show only calendar in http://projects.wojtekmaj.pl/react-datetime-picker/

:) Have a nice day
