### ISSUE TITLE
Weekly calendar view

### ISSUE THREAD

**Issue by rchavezj** [wojtekmaj/react-calendar#314]
Question. Do you have  a weekly calendar view instead of the whole month?

**Comment by jdmswong** [comment]
👍  I need this too, a datepicker which supports viewing a single week

**Comment by jdmswong** [comment]
so I went ahead and wrote this in, check it out @wojtekmaj 
https://github.com/wojtekmaj/react-calendar/pull/330

**Comment by freshlySqueezedBananas** [comment]
One more for this! A week view would be extremely useful as a sneak peek in an agenda environment. Please consider this
