### ISSUE TITLE
tileDisabled

### ISSUE THREAD

**Issue by AndreVizosodaCruz** [wojtekmaj/react-calendar#319]
Hello
I receive from the server the days that are blocked in an array formated like 'YYYY-MM-DD' , there is a way to pass this days and it appear blocked in the calendar. Thanks

**Comment by wojtekmaj** [comment]
That's ISO format, should work just fine. I can't quite understand the issue you're facing.

**Comment by AndreVizosodaCruz** [comment]
Sorry my mistake don't attach the code 
`({date}) => {
                              let available;
                              for (let i = 0; i < monthAvailability.length; i++) {
                                available = moment(date).format('YYYY-MM-DD') == monthAvailability[i].data
                              }
                              return available;
                            }`
it works but only disable the last day not the others

**Comment by wojtekmaj** [comment]
Aaaah. So you have an array which *months* are available, not *dates*. In this case, just compare months only...

```js
available = moment(date).format('YYYY-MM') == moment(monthAvailability[i].data).format('YYYY-MM')
```

or something like that.

**Comment by brunorcajo** [comment]
When Can I use it for disabling dates? Witch one property?
