### ISSUE TITLE
The component is taking time in account when minDate/maxDate is used somehow inconsistently

### ISSUE THREAD

**Issue by bessgeor** [wojtekmaj/react-calendar#32]
# Simple Repro

```
/*lib references*/

const calendar1Container = document.getElementById( "calendar1" ),
   calendar2Container = document.getElementById( "calendar2" );

ReactDom.render( <Calendar maxDetail="month" minDate={new Date()} onChange={date=>alert(date.getLocaleString())} />, calendar1Container);

ReactDom.render( <Calendar maxDetail="month" minDate={new Date()} onChange={dateRange=>alert(dateRange[0].getLocaleString())} selectRange />, calendar2Container);
```

Date in callback on the first calendar will include component render time.
Date in callback on the first calendar will have time of 00.00.00.

**Comment by wojtekmaj** [comment]
Hey @bessgeor,
it doesn't seem to be an issue on versions I checked - 2.12.0 and 2.10.0. Would you please ensure you have the newest version possible?

**Comment by PriyankaRBT** [comment]
Hey,
I am using  react: 16.8.2, react-calendar: 2.19.0, react-date-picker: 7.5.1 and seem to have the same issue- displays time along with date at times, unsure on when exactly this happens. Is there some flag that can be used to disable displaying time?

**Comment by wojtekmaj** [comment]
@PriyankaRBT can you give me an example of this happening?

**Comment by wojtekmaj** [comment]
Closed, can't reproduce. @PriyankaRBT's case may be caused by other packages, React-Date-Picker is likely.
