### ISSUE TITLE
how can i use selectRange between months

### ISSUE THREAD

**Issue by zhaofeihao** [wojtekmaj/react-calendar#326]
![image](https://user-images.githubusercontent.com/33317030/75760329-1351bc00-5d72-11ea-9946-884644b31149.png)

I have complete the selectRange in the same month tab currently,
but I need to select range dates between month tabs, 
does there any solution to fix it , because it seems now different tab doesn't share the same date value

**Comment by wojtekmaj** [comment]
I don't understand what your problem is. You can select any date range, of course!

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/5426427/76194174-ea07b480-61e5-11ea-82e8-efbcfea14c12.gif)
