### ISSUE TITLE
Cannot open calendar without initial value

### ISSUE THREAD

**Issue by Stas-Buzunko** [wojtekmaj/react-calendar#328]
I'm sure I'm missing something because it can't be like this

How do i use this calendar without default/initial date?

I've tried empty array / array with null. It only works if i pass today's value
but it's super strange. in my use case user cannot proceed until they select a date, but if i have initial date they can proceed, the only way i see right now is to write to state whether date has been changed, but it's weird.

So how do I open calendar without value?

**Comment by wojtekmaj** [comment]
I don't see what the problem is, I'm able to render calendar without any value perfectly. null, undefined, they all work 🤔 

https://codesandbox.io/s/react-calendar-without-value-0gpbd
