### ISSUE TITLE
Docs are misleading about value prop

### ISSUE THREAD

**Issue by Stas-Buzunko** [wojtekmaj/react-calendar#329]
docs say: **"An array of dates"**
but it **must be** specified that no more than 2 values

i've spent around 30 minutes before finding out in other issues that only 2 values can be passed.

please, specify this in docs in order to prevent such situations.

**Comment by wojtekmaj** [comment]
Good point! Thanks for this, fixed for 2.x and 3.x branches.

**Comment by virgincodes** [comment]
cant we load an array of dates more than two, am trying to load dates, into th ecalendar view

**Comment by wojtekmaj** [comment]
No, we cannot. React-Calendar supports a single date or a single date range limited by two dates.
