### ISSUE TITLE
The typings are not fetched for entry.nostyle

### ISSUE THREAD

**Issue by bessgeor** [wojtekmaj/react-calendar#33]
May be fixed by creating `entry.nostyle.d.ts` ether copypasting `index.d.ts` or importing it and exporting each of it's own exports.

**Comment by wojtekmaj** [comment]
Hey @bessgeor,
that would be neat.

I don't call myself an expert in TypeScript, so I'm relying on community in TypeScript-related stuff though, so I'd need someone to volunteer a pull request. 

I'd like to avoid code duplication so importing and reexporting it would be great.
