### ISSUE TITLE
Named ranges

### ISSUE THREAD

**Issue by I-Lotus** [wojtekmaj/react-calendar#332]
Does this component support named ranges? I mean I want to see on left side from calendar list with names like "Last Week", "Today" and etc. After click on one of them calendar should select range. Or maybe you could suggest some workaround to implement it?

**Comment by wojtekmaj** [comment]
Sounds like you need a separate component, independent from the calendar, which hits the same onChange as the Calendar.

**Comment by I-Lotus** [comment]
Okay. Thanks
