### ISSUE TITLE
programmatic reset (question)

### ISSUE THREAD

**Issue by zigotica** [wojtekmaj/react-calendar#335]
Hi

Using v3.0.0

Is there a way to reset the value or range programmatically? Meaning, removing the selection/s, associated tile classes, etc

Thank you

**Comment by wojtekmaj** [comment]
v3.0.0 can be both controlled and uncontrolled. If you need to control the value from the outside, controlled would be the best approach. Then it's as easy as clearing value prop.

**Comment by zigotica** [comment]
Hi,

Is there documentation and / or examples of what "controlled would be the best approach" means? 

Thank you

**Comment by zigotica** [comment]
To be more specific, I used `value={rangeValue}` and change it onClickDay and onChange, that works, but if I programmatically set `rangeValue=null` is doesn't remove the tile classes, so it all looks as selected.

**Comment by zigotica** [comment]
Sorry, my fault, using the following just works:

`const [rangeValue, setRangeValue] = useState(null);`

Thank you again
