### ISSUE TITLE
Set the default preselected date as last 7 days.

### ISSUE THREAD

**Issue by Shubham-DK** [wojtekmaj/react-calendar#337]
Business Requirement --
In date range selector calendar by default last 7 days should be selected

As per the props examples given , when i use them getting the below error

can you please improve the examples, as they are not much clear.

![image](https://user-images.githubusercontent.com/58040775/76708952-39c11100-66fb-11ea-9029-76297cd7031a.png)

![image](https://user-images.githubusercontent.com/58040775/76708952-39c11100-66fb-11ea-9029-76297cd7031a.png)
![image](https://user-images.githubusercontent.com/58040775/76708968-552c1c00-66fb-11ea-80bf-a0993c0bbbe6.png)

**Comment by wojtekmaj** [comment]
First of all, that's not a valid date, that's some date-like string.

```diff
-    activeStartDate="new Date(2020, 02, 11)"
+    activeStartDate={new Date(2020, 1, 11)}
```

mind that second argument of `Date` is month index, not number.

Secondly, activeStartDate is to mark the date of from which a given view should begin, eg. if you want to display Feb 2020, you use `activeStartDate={new Date(2020, 1, 0)}`. To have values "selected", use `value` prop.
