### ISSUE TITLE
Calendar does not close

### ISSUE THREAD

**Issue by ershumi** [wojtekmaj/react-calendar#338]
On selecting date Calendar is not getting closed. Also when I click outside the calendar it still remains open.

**Comment by wojtekmaj** [comment]
Any technical details? On which OS, browser(s)?

**Comment by ershumi** [comment]
Tried it on Ubuntu 18.04 and Google Chrome, Windows 8.

**Comment by wojtekmaj** [comment]
Sorry, misread the ticket. React-Calendar is a standalone widget that does not have any open/close functionality. You must have intended to file this against some other repository that may be using React-Calendar instead.

**Comment by cocodrino** [comment]
hi @wojtekmaj sorry if it's not correct to reopen this close issue, but I think that would be great if I could pass a ref to the calendar component, so I can use for instance 
https://usehooks.com/useOnClickOutside/

and handle the click outside the component, I think that this would not require so many changes and would be a solution for those who need to collapse the calendar when clicking outside
