### ISSUE TITLE
More explicit documentation on how to override formatting

### ISSUE THREAD

**Issue by hansmodo** [wojtekmaj/react-calendar#34]
For example it's not clear how to use 'formatShortWeekday' .

example is currently: (value) => formatDate(value, 'dd')

But when supplying my own formatting function as in the example I get an error complaining about calling incorrectly calling .replace() in the source code. Questions I have would be - is 'value' passed to the custom function supposed to be a date? Are we supposed to perform some native js date operation and return a value? A fully working example would be even better. thx

**Comment by wojtekmaj** [comment]
Yes, your assumptions are correct. I'll make sure to make documentation clearer :) Thanks for suggestion.

**Comment by nikolas** [comment]
Same problem here, I'm just trying to make the day names display as the first letter rather than the first three, and this is unclear from the documentation. Ideally, I'd just be able to do something like: `formatShortWeekday="d"`.

**Comment by wojtekmaj** [comment]
@nikolas formatShortWeekday should be the way to go. The easiest solution in your case would be something like
`formatShortWeekday={value => ['S', 'M', 'T', 'W', 'T', 'F', 'S'][value.getDay()]}`

**Comment by nikolas** [comment]
thanks, i got it! ^_^

**Comment by Alek-S** [comment]
Hey, I got a related question. I'm doing 
```js
formatShortWeekday = { value => ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'][value.getDay()]}
```
but it gets formatted into all caps to `MO TU WE TH FR SA SU`

is there a way to get it to retain capitalization fed in with `formatShortWeekday`?

**Comment by wojtekmaj** [comment]
Sure. They [are capitalized by CSS](https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less#L50) only, so you just have to overwrite the default styling.

**Comment by abhisheknayak09** [comment]
<Calendar
            tileClassName={tileClassName}
            formatShortWeekday={value => ['S', 'M', 'T', 'W', 'T', 'F', 'S'][value.getDay()]}
          />

I am getting the following error: TypeError: Cannot read property 'getDay' of undefined

**Comment by Chusynuk** [comment]
Hi, I have a doubt about `formatShortWeekday` also. Idk why but all languages are working nicely, but Portuguese is the only language which shows the whole `weekday` word , trying this

`() => new Intl.DateTimeFormat(localeLang, { weekday: 'short' }).format(date).substring(0, 3)`

`localeLang` is a dynamic variable

but not success. Any ideas?


<img width="466" alt="Screenshot 2019-11-25 at 16 40 59" src="https://user-images.githubusercontent.com/4323435/69555113-f3f10900-0fa2-11ea-8f19-367b4b7b66e9.png">

**Comment by akhilaudable** [comment]
> @nikolas formatShortWeekday should be the way to go. The easiest solution in your case would be something like
> `formatShortWeekday={value => ['S', 'M', 'T', 'W', 'T', 'F', 'S'][value.getDay()]}`

How to use it in the <Calendar /> ?
