### ISSUE TITLE
Unable to use in React TypeScript Project.

### ISSUE THREAD

**Issue by dhanukaperera** [wojtekmaj/react-calendar#340]
I am working on React Type script project. I want to use React Calendar but I am unable to use it because `@types/react-calendar` are not found in the npm registry. Is there any way I can you this is a React Typescript project?

**Comment by dhanukaperera** [comment]
able to resolve by declaring type in .d.ts file. More info : [https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/](https://www.detroitlabs.com/blog/2018/02/28/adding-custom-type-definitions-to-a-third-party-library/)

**Comment by wojtekmaj** [comment]
Typings are yet to be moved. Waiting for community contributions: #273

**Comment by Enfield-Li** [comment]
`npm i @types/react-calendar`
