### ISSUE TITLE
onActiveStartDateChange gets Triggered after onClickDay since 3.x

### ISSUE THREAD

**Issue by juspky** [wojtekmaj/react-calendar#343]
onActiveStartDateChange
`Function called when the user navigates from one view to another using previous/next button.`

After updating to 3.x we started getting the issue that onActiveStartDateChange is called even if you just click on a day in month view.

This issue is blocking us from upgrading to 3.x

**Comment by tingus** [comment]
Has this been fixed yet.

**Comment by wojtekmaj** [comment]
Clearly not since it's open. Check #344.

**Comment by wojtekmaj** [comment]
v3.0.1 containing the fix out.
