### ISSUE TITLE
Calendar is wrong when using activeStartDate with date other than beginning of the month

### ISSUE THREAD

**Issue by renchap** [wojtekmaj/react-calendar#345]
When I set `activeStartDate` (or `defaultActiveStartDate`), the calendar is wrong.

Reproduction: https://codesandbox.io/s/react-calendar-active-start-date-bug-6x299

You can see that the 1st of march is displayed as a Tuesday when loading the calendar. If you select a day, the calendar updates and becomes correct with the 1st of march beeing a Sunday

Video:
![Screen Recording 2020-03-26 at 12 57 44 2020-03-26 12_59_12](https://user-images.githubusercontent.com/42070/77644669-a80a9c80-6f61-11ea-8f2a-cb44f0d45852.gif)

This did not happen with version 2.

**Comment by wojtekmaj** [comment]
Note that your activeStartDate is not valid - it's not the beginning of month/year/decade/century. It's the 10th of March. Set it to Match 1 and you're golden.

**Comment by renchap** [comment]
Ho thanks, I did miss this from the docs.
Also it used to work fine in react-calendar 2, might be worth it to add it to the changelog.

**Comment by wojtekmaj** [comment]
Since I never specified how activeStartDate is supposed to work exactly I'll treat this as a bug.
