### ISSUE TITLE
import 'react-calendar/dist/Calendar.css';

### ISSUE THREAD

**Issue by jtlivio** [wojtekmaj/react-calendar#346]
Hi, when reference:
**import 'react-calendar/dist/Calendar.css';**

Dosn't reflect when shipping, calendar still have no styling, only in localhost works.

Any help?
Thanks

**Comment by miyucy** [comment]
We have same issue.
But we solved  this issue by change webpack settings.
    Add  sideEffect true to css-loader. see https://webpack.js.org/configuration/module/#rulesideeffects

**Comment by miyucy** [comment]
https://webpack.js.org/configuration/module/#rulesideeffects
so i guess we need sideEffects  prop to package.json.

**Comment by jtlivio** [comment]
Thanks
