### ISSUE TITLE
How to set active month to date range end?

### ISSUE THREAD

**Issue by benasleng** [wojtekmaj/react-calendar#347]
Hey, i a currently having this issue where if I select two separate dates (startDate and endDate) from outer elements, and pass those values to Calendar as `[startDate, endDate]`, the range shown in the calendar always has the startDate focused, for example if startDate month is June and endDate month is december (same year) the focused month in the calendar will be June. Is there any way to make it so the focused month would be the one from `endDate`? I am using 2.x.x version

**Comment by wojtekmaj** [comment]
You can set `activeStartDate` to [`getMonthStart`](https://github.com/wojtekmaj/date-utils/blob/master/README.md#getmonthstart)`(endDate)`. But you'll have A TON of more control if you upgrade to React-Calendar 3.x :)

**Comment by benasleng** [comment]
Thank you for the answer. After submitting the question I managed to solve it myself by setting activeStartDate with endate's first day
