### ISSUE TITLE
Tooltip on tileContent. Event on onClick event.

### ISSUE THREAD

**Issue by andreguilhon** [wojtekmaj/react-calendar#352]
Hello I'd like to render a custom Tooltip once mouse is over a day (in month view). I know that I can use tileContent to render additional content in the tile, and there I could put a <Tooltip> component wrapping my tile, but that is not what I want to achieve. I'd like to have the whole tile rendering my tooltip. 
I get that this is not possible as of now, as you mentioned in #209 , unless I use CSS. 
I also would like to have the event in the onClick event, so that I can pass it the Popover I'm trying to build. 
Can you give me a hint on how I could achieve those things?
Thanks

**Comment by iamacoderguy** [comment]
In our project, we also need an event to determine the position of the tile when clicking on it.

We customized this one https://github.com/wix/react-native-calendars to achieve it for our mobile app. Maybe, we have to do the same for the web app.

**Comment by subhayanghosh** [comment]
@andreguilhon I am facing the same issue. I want to show a tooltip when the mouse hovers over a day. Is it possible? I know event is now added to onChange but how can I set it to hover?
