### ISSUE TITLE
Impossible to remove dash from NavigationLabel in showDoubleView mode

### ISSUE THREAD

**Issue by ValeryStatinov** [wojtekmaj/react-calendar#355]
Hello, @wojtekmaj!
I am using `Calendar` in `showDoubleView` mode. I want to customize navigation bar through `navigationLabel` prop. Unfortunately, according to the source code, there is no chance to get rid of this [dash](https://github.com/wojtekmaj/react-calendar/blob/8e610bca7d123982f3f93f513a1dd36cc6785842/src/Calendar/Navigation.jsx#L162) between labels. Is it possible to add a feature to remove dash?

**Comment by ValeryStatinov** [comment]
Found a [Pull request](https://github.com/wojtekmaj/react-calendar/pull/333) that solves the problem

**Comment by giacomocerquone** [comment]
@ValeryStatinov @wojtekmaj this should be closed!

**Comment by wojtekmaj** [comment]
Correct, thanks

**Comment by HammadCT** [comment]
.react-calendar__navigation__label__divider{
  visibility: hidden;
}
