### ISSUE TITLE
How to use tileClassName with a range of dates

### ISSUE THREAD

**Issue by mikexavier** [wojtekmaj/react-calendar#359]
Hey, I'm looking to use the calendar as a read-only availability calendar. I am currently pulling in booked dates from an external data source, and have a from and to date for each booking formatted as "2020-04-16"

I see that tileClassName can be used with a function, I'm just not experienced enough to know how to get it done, and hoping someone might be able to point me in the right direction?

thanks!

**Comment by wojtekmaj** [comment]
What I would do is I'd change the dates to Date() first:

```js
new Date('2020-04-16');
```

please be aware that this format will be read to 2020-04-16 UTC midnight. If you use

```js
new Date('2020-04-16T00:00');
```

you'll get a local midnight.

After you have your dates as Date() objects, you can simply compare them as if they were numbers.

```js
> new Date('2020-04-16') < new Date('2020-04-17')
< true
```

So at this point, checking if a date is within a given range shouldn't be a big deal.

**Comment by mikexavier** [comment]
Hey, thanks for your reply... I've been at it all day, and really struggling to wrap my head around it.

I can get an array of dates as Date() objects by doing:

```
const bookingDates = items.map(({ ArrivalDate, DepartureDate }) => {
      const arrivalDates = new Date(ArrivalDate + "T00:00")
      const departureDates = new Date(DepartureDate + "T00:00")
    })
```

However, if I run this inside a tileClassName function, it runs it 35 times (for April for eg). 

If I try and single out arrivals and departures like:

```
const arrivalDates = items.map(({ ArrivalDate }) => {
      return new Date(ArrivalDate + "T00:00")
    })
```

I get a an array which looks like:
![Screenshot 2020-04-17 at 21 03 36](https://user-images.githubusercontent.com/17153194/79604764-fccbae00-80ee-11ea-9d8d-ce73f476ec89.png)

I'm not sure how to compare the new array of dates to the calendar dates, let alone add a class to each date with the arrival to departure range.

I realise I need to learn more, and I'm at the point where I'm not even sure what I should be learning to achieve this.

Thanks again!

Mike

**Comment by wojtekmaj** [comment]
* Dates are nothing but wrappers over Unix timestamp. use date.getTime() to get the Unix timestamp, and then you have the numbers you can easily compare.

If there's a match in `tileClassName` between the date from function arguments and any of the dates in your array, return a string from this function. The tile this date was connected to, will now have this string as an additional class name.
