### ISSUE TITLE
Is there any way to disable the << and >> icons?

### ISSUE THREAD

**Issue by FriendlyUser** [wojtekmaj/react-calendar#363]
![image](https://user-images.githubusercontent.com/13860264/80042530-22bcce00-84b4-11ea-8d93-2f1b3ed848bc.png)

Hi, thanks for the great calendar component, I was wondering if there was any way for me to disable the << and >> options in a calendar.

**Comment by valtism** [comment]
You can disable them by setting the `next2Label` and `prev2Label` to null.
