### ISSUE TITLE
V3 bundle size is larger?

### ISSUE THREAD

**Issue by felixmosh** [wojtekmaj/react-calendar#366]
Hi,

I've considered to update to latest version but since the latest version is 49k minified (v2 was 2k), it looks like some mistake.
It this number is true?
![image](https://user-images.githubusercontent.com/9304194/80304470-b0ebc980-87be-11ea-8d4e-d77e0b6a96c4.png)

**Comment by wojtekmaj** [comment]
It isn't larger - it's actually smaller, as we now support ES modules (and consequently, tree shaking). It's a bug in bundlephobia. :)
