### ISSUE TITLE
How disable auto set activeStartDate after click on day in next month with double view? 

### ISSUE THREAD

**Issue by ilyanikulin** [wojtekmaj/react-calendar#367]

**Comment by ilyanikulin** [comment]
There isn't comfortable when change month range after click...

**Comment by wojtekmaj** [comment]
In React-Calendar 3.0, unlike in 2.x, activeStartDate is a fully controlled prop. You can choose to ignore onActiveStartDateChange call.

**Comment by betCG** [comment]
> In React-Calendar 3.0, unlike in 2.x, activeStartDate is a fully controlled prop. You can choose to ignore onActiveStartDateChange call.

How can i do that? I'm learning react so i'm kinda a newbie in web programming

**Comment by wojtekmaj** [comment]
You have two options: use React-Calendar as an uncontrolled component, or a controlled one.

Uncontrolled: use `defaultValue`, optionally `defaultActiveStartDate`. You don't wanna do this.

Controlled: use `value`, optionally `activeStartDate`, and `onChange`, `onActiveStartDateChange` to control the change. In `onActiveStartDateChange`, change `activeStartDate` prop only when you want it to be changed.

However, I don't know if you'll have all the information you need to implement this. If you come up with something and you will need more information from any callback, just let me know and I'll add it.

**Comment by mriot** [comment]
I have noticed, that when you click on a day of another month while being in month view, `onClickDay` as well as `onActiveStartDateChange` will fire. 
In `onActiveStartDateChange` however, I don't see a way how to differentiate arrow navigation and a click on another months day. 

Maybe a dedicated onArrowClick (or something) could be a solution.

**Comment by wojtekmaj** [comment]
in v3.5.0, `action` was added to `onActiveStartDateChange` and other callbacks. See https://github.com/wojtekmaj/react-calendar/issues/474 for more details.
