### ISSUE TITLE
in select range onChange function is triggering after picking start date and end date.how to get value on both clicks

### ISSUE THREAD

**Issue by kumargugloth** [wojtekmaj/react-calendar#370]
clicking on  start date(valueFrom)  how to get value of it and same goes for end date (valueTo)

**Comment by Haaguitos** [comment]
Having the same problem here! I saw that wojtekmaj commited a support for allowPartialRange, but it isn't working for me. :/

**Comment by rosczja** [comment]
I have the same requirement. Where can I find info about allowPartialRange?

**Comment by Haaguitos** [comment]
> I have the same requirement. Where can I find info about allowPartialRange?

https://github.com/wojtekmaj/react-calendar/pull/351

**Comment by kumargugloth** [comment]
> > I have the same requirement. Where can I find info about allowPartialRange?
> 
> #351

is this applied in react-calendar package?

**Comment by Haaguitos** [comment]
> > > I have the same requirement. Where can I find info about allowPartialRange?
> > 
> > 
> > #351
> 
> is this change has been updated in react-calendar package?

Nope! Don't really know why, but it is just a pull request at the moment I'm sending that.

**Comment by wojtekmaj** [comment]
#351 (#331) was merged - will be out with the next release.
