### ISSUE TITLE
Control the dimension of the selected date background circle.

### ISSUE THREAD

**Issue by OlegMoshkovich** [wojtekmaj/react-calendar#371]
Hello!
The tile width and height seem to be calculated based on the dimensions of the overall calendar. Is it possible to have a background container around the date that is independently controlled?

<img width="400" alt="Screen Shot 2020-05-07 at 8 43 51 AM" src="https://user-images.githubusercontent.com/3433606/81295721-dd190d00-903e-11ea-8c2f-5968c9892128.png">

**Comment by OlegMoshkovich** [comment]
Thank you so much in advance?

**Comment by wojtekmaj** [comment]
You could:

* Use an image background (svg?) and use background-position + background-size
* Use :before, :after pseudoelements to get an extra element to style

**Comment by OlegMoshkovich** [comment]
Thank you Wojciech!!!
