### ISSUE TITLE
Set calendar view

### ISSUE THREAD

**Issue by guydewinton** [wojtekmaj/react-calendar#375]
Hello

Many thanks for creating this wonderful tool. 

I have implemented a date range selector with two drop down calendars, the first to select the start date and the second to select the end date. My problem is that both calendars open on the month of the start date. Is it possible to set the second calendar to open on the month of end date?

Thanks again!

**Comment by giacomocerquone** [comment]
@guydewinton Hi! Yes this package is a wonderful tool indeed!

Can you show us some code?
Do you have two react-calendars instantiated in a component? In that case you could simply set two different activeStartDates

**Comment by wojtekmaj** [comment]
It's a little hard without the code sample, but there are several possible implementations you could have done:

* Passing first `value` to the both calendars - in this case all you need is simply fix it to pass the second one to it :)
* Passing `[startValue, endValue]` to both calendars - in this case you will need to add `activeStartDate` to the second calendar to force it to display 2nd calendar. Be careful though, this causes Calendar's `activeStartDate` to be completely controlled and you will need to handle `onActiveStartDateChange` callback as well.
* Calculating `activeStartDate` once and passing it to both calendars - in this case you'd need to calculate it separately for both calendars.

**Comment by guydewinton** [comment]
Thank you for your reply. I am just working on another part of the project. Will return and edit this response.
