### ISSUE TITLE
Disable Click of Label in Navigation Bar

### ISSUE THREAD

**Issue by mikeyharris89** [wojtekmaj/react-calendar#377]
Is there a way to disable the functionality when you click the label within the navigation bar? I want to be able to use next and previous buttons, but have nothing happen when the label is clicked. 

I'm using double month view, and when i click the label (ie May 2020 - June 2020) it changes to year view. I've stopped this by explicitly setting `view="month"` but now on click of this, it resets the calendar to the beginning of the year.

**Comment by giacomocerquone** [comment]
@mikeyharris89 as per this other issue https://github.com/wojtekmaj/react-calendar/issues/242 you just need to set maxDetail and minDetail

**Comment by wojtekmaj** [comment]
Thanks @giacomocerquone!

**Comment by mikeyharris89** [comment]
Awesome! Yeah it doesn't really indicate that anywhere in the docs so thanks for the quick response

**Comment by oseisaac** [comment]
> @mikeyharris89 as per this other issue #242 you just need to set maxDetail, minDetail and view and if you want you can even disable the navigation bar

@giacomocerquone how do I disable the controls ?

**Comment by seanred360** [comment]
> > @mikeyharris89 as per this other issue #242 you just need to set maxDetail, minDetail and view and if you want you can even disable the navigation bar
> 
> @giacomocerquone how do I disable the controls ?

Because this is the top result in Google and not answered, use the prop showNavigation={yourbooleanhere}
