### ISSUE TITLE
Prevent auto-switching when selecting date in next month

### ISSUE THREAD

**Issue by mikeyharris89** [wojtekmaj/react-calendar#378]
Hey i saw this issue https://github.com/wojtekmaj/react-calendar/issues/199 which was asking the same thing, which was marked as resolved because at the time there wasn't an option.

Any updates on this? Ideally on click of a day in the second month (when selecting multiple dates), the months wouldn't switch. I'm guessing it would involve preventing the activeStartDate from changing, but i'm not sure how to do that.

**Comment by wojtekmaj** [comment]
You can use React-Calendar 3.0 as a controlled component. If you provide `activeStartDate`, it will take the priority over what's the default behavior.

**Comment by mikeyharris89** [comment]
Right, but i want to disable the switch onClickDay, but not on the next or previous button clicks. Is there a way to hook into the navbar clicks? onActiveStartDateChange fires for both.

**Comment by wojtekmaj** [comment]
Hmmmm, I suppose you could be able to filter that out if I added `value` (being next value) to `onActiveStartDateChange` callback. This way you could only accept activeStartDate change if `value` is about to change, by comparing it with the value you hold. How does that sound?

**Comment by mikeyharris89** [comment]
I found a fix, but it would be nice if there was a way to differentiate between a day click and a navclick. Either an event prop in activeStartDateChange or if the onChange event actually had an event defined (onChange that is fired from clicking passes undefined for event).

**Comment by wojtekmaj** [comment]
Mind sharing your fix with us? :)

**Comment by mikeyharris89** [comment]
Sure it's kind of hacky and i don't love it. I think the ideal solution would be to have a callback for clicking the nav buttons. But anyway. I'm setting `startDate` in local state as today's date for the initial value for activeStartDate. Then `onActiveStartDateChange` i `setState` to set `startDate` to be the `activeStartDate` prop passed to the callback. As I said this isn't great because it fires on both by clicking the nav buttons and by clicking on a day. So this works well for clicking the prev/next buttons. To prevent day click from changing the start date, I'm also listening for `onChange`, which gets fired after `onActiveStartDateChange`, but both callbacks are fired before the local state can update, and since onChange only fires on day click, i can just override the initial state change, and just reset `startDate` to be what is currently saved in local state. Make sense? I told you, it was hacky lol

**Comment by wojtekmaj** [comment]
Makes sense :D I think merging #379 will make your hack unnecessary :)

**Comment by ChadH28** [comment]
Heres how you do it:
//make state variable
 const [today, setToday] = useState(new Date())

// calendar component
 activeStartDate={today}      // pass in state var in activeStartDate      
onActiveStartDateChange={({ value, activeStartDate, action }) => {
              if (action === 'next') {
                setToday(new Date(activeStartDate))
              }
              if (action === 'prev') {
                setToday(new Date(activeStartDate))
              }
            }}
