### ISSUE TITLE
Setting value prop to 'undefined' doesn't reset the selected tile

### ISSUE THREAD

**Issue by aramperes** [wojtekmaj/react-calendar#380]
I'm passing the current `value` down from a parent component. If the property being passed down is `undefined`, the calendar will not re-render and the selected tile will remain selected.

I've tried a few techniques to force a refresh of the calendar (updating other props to force a refresh), but the state of the calendar doesn't appear to refresh.

From a bit of digging, it seems this is an explicit behavior:

https://github.com/wojtekmaj/react-calendar/blob/e226402678123e1006242d5f4268077d83af7da3/src/Calendar.jsx#L175-L185

If the value is set to `undefined`, it appears to keep whatever is in the current state. If this is intentional, is there a way to programmatically un-select a date?

version `3.1.0`

**Comment by aramperes** [comment]
I found a possible workaround: use `null` instead of `undefined`.

Unfortunately the TypeScript definition doesn't allow it (`value` must be `Date | Date[] | undefined`), but you can set `value={null as unknown as undefined}` to force it.

**Comment by giacomocerquone** [comment]
Agree, though I think it's needed just for the value prop and not for the defaultValue one.

Opened PR on definitely typed, feel free to comment there.

**Comment by giacomocerquone** [comment]
well cool, I suppose this can be closed now :D
