### ISSUE TITLE
Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by itskaizad** [wojtekmaj/react-calendar#382]
Hello,
I pretty much created a new react-native app and tried using react-calendar, and get this error. 

**Error: Text strings must be rendered within a <Text> component.
This error is located at:
  in button (created by Navigation)
  in div(created by Navigation)
  in Navigation (created by Calendar)**

<img width="454" alt="Screen Shot 2020-05-30 at 8 47 01 PM" src="https://user-images.githubusercontent.com/6906507/83341920-b99c5780-a2b6-11ea-9330-4aa18b9bf266.png">
My dependencies are as such:
```
{
  "name": "ppreact",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-calendar": "^3.1.0",
    "react-dom": "^16.13.1",
    "react-native": "0.62.2",
    "react-native-safe-area-context": "^2.0.3"
  },
  "devDependencies": {
    "@babel/core": "7.10.0",
    "@babel/runtime": "7.10.0",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "^6.8.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Seems like a common issue past react-native ~0.54. Any recommendations?

**Comment by wojtekmaj** [comment]
That's calendar for React, not React Native. Unfortunately you can't really build a component that renders in both.
