### ISSUE TITLE
Pass a ref to the calendar component

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#384]
hi @wojtekmaj sorry if it's not correct to reopen this close issue, but I think that would be great if I could pass a ref to the calendar component, so I can use for instance 
https://usehooks.com/useOnClickOutside/

and handle the click outside the component, I think that this would not require so many changes and would be a solution for those who need to collapse the calendar when clicking outside

_Originally posted by @cocodrino in https://github.com/wojtekmaj/react-calendar/issues/338#issuecomment-635616386_

**Comment by Jiish** [comment]
+ 1 to this. Now there seems to be no easy way to manually close a calendar residing inside a function component

**Comment by wojtekmaj** [comment]
Will be out with the next release.

**Comment by pierpo** [comment]
Can't wait for this to be published. Do you have an ETA for the release ? :blush:

**Comment by wojtekmaj** [comment]
Completely forgot about it, sorry. Released in v3.2.0.

**Comment by pierpo** [comment]
Thank you, that was super fast! :hugs:
