### ISSUE TITLE
How can I reset the value in the middle of a range selection?

### ISSUE THREAD

**Issue by sergioadimedia** [wojtekmaj/react-calendar#385]
Hello!

In this example, here's what I'm trying to do:
 - First, I open the calendar and select one week (15JUN to 21JUN) and the text in the dropdown updates with this value.
 - Then, I open the calendar again and start selecting another range, but quit before finishing; so the value (and therefore the text in the dropdown) does not change.
 - When I reopen the calendar, it appears like I'm still selecting that previous range. But actually, I would like the calendar to show the current value (15JUN to 21JUN).

![captured](https://user-images.githubusercontent.com/53001197/83493863-b4592b80-a4b5-11ea-8129-5083a4e2b001.gif)

I haven't found any way of doing this, since the value `state` prevails over the value from `props`.

https://github.com/wojtekmaj/react-calendar/blob/e226402678123e1006242d5f4268077d83af7da3/src/Calendar.jsx#L179-L182

Thanks in advance!

**Comment by wojtekmaj** [comment]
For this, you'd need to cause the Calendar to remount by changing its `key`. Nothing else comes to my mind.

**Comment by sergioadimedia** [comment]
It worked!

Thank you for the fast response, I really appreciate it.
