### ISSUE TITLE
How to select only startDate or endDate if one is already selected

### ISSUE THREAD

**Issue by rubenesda** [wojtekmaj/react-calendar#387]
How to select range days without begins with the present today? When I put the prop 'selectRange' in the component I want to begin to do click on a day different to current today, instead of to begin the range with the present today, i.e Today June 10, the range start there and only rest to do another click in the finish range date. I want to do two clicks, one to choose the first date and another to choose the finish date of range.

I don't know if I'm missing other props or this is an enhancement to the future. 
Thanks,

**Comment by wojtekmaj** [comment]
This will work:

```
function Test() {
  const [value, onChange] = useState([new Date()]);
  const startDateOrRange = value.length === 1 ? value[0] : value;

  return (
    <Calendar
      selectRange
      minDate={value[0]}
      onChange={onChange}
      value={startDateOrRange}
    />
  );
}
```

Unfortunately, after you select the range once, we're back to default experience, so the user can select another range freely. I'm afraid nothing more can be done with this package. Too much of an edge case.

**Comment by wojtekmaj** [comment]
Related to https://github.com/wojtekmaj/react-daterange-picker/issues/69
