### ISSUE TITLE
Selected date from another month doesn't update focus correctly

### ISSUE THREAD

**Issue by saulf** [wojtekmaj/react-calendar#39]
**Steps**
1. Go to http://projekty.wojtekmaj.pl/react-calendar/ 
2. On the calendar select the month of february 2018
3. Click on the last row the number 2 (For march 2nd)

**The problem:**
The month / date changes to March 2nd, but the button / element that has focus is March 30 and has a gray background. 

**Expected**
The element with focus is March 2nd ( or none? )

**Comment by wojtekmaj** [comment]
Hi @sauld, thanks for the report and well written steps to reproduce :) I'll take care of this after work.

**Comment by sauld** [comment]
@wojtekmaj   I think you got the wrong Saul.   You wanted @saulf   :)

**Comment by wojtekmaj** [comment]
Haha, sorry! I was writing fast :)

**Comment by wojtekmaj** [comment]
Hi @saulf,
the issue has been fixed and will be public in v2.13.2 which I'm releasing as I speak. Let me know if you have any further issues!

**Comment by saulf** [comment]
Awesome, thank! will check it out
