### ISSUE TITLE
show my selected days

### ISSUE THREAD

**Issue by aolose** [wojtekmaj/react-calendar#391]
```
 <Calendar value={val} .../>
```
Q1: when I change the val to another mouth or year ,how to make the view show my selected?

```
<Calendar  selectRange={true} value=[start,end] .../>
```
Q2: If I use the range, how to jump to the start or end if they are not in current view?

**Comment by HARIKSREEE** [comment]
Hi @aolose 
Could you provide bit more information like how you are updating `val`?
So that I can try to provide a better answer.

**Comment by aolose** [comment]
![aaaa](https://user-images.githubusercontent.com/7620293/84909083-d4a8fd00-b0e7-11ea-8ac7-8b69d4542b38.jpg)

`val` will updating when I click the button under the calendar.

```
const [val, setVal] = useState(date);
<Calendar  value={val} onChange={setVal}/>
<button  onClick={()=>setVal(xx)}>30 day ago</button>
```

if I set `activeStartDate={xx}` , then I cant't select other month .

**Comment by HARIKSREEE** [comment]
Okay , I tried that now. We have one prop `onActiveStartDateChange`. We can use this change event to set the `activeStartDate`. Could you try the below ?


`const handleDateChange = (value:Date)=>{
setDateValue(value:Date);
setActiveDateStart(value);
}`

`const handleActiveStartDateChange = (values: any) => {
      setActiveStartDate(new Date(values.activeStartDate));
   }`

`<Calendar  onChange={(value) => handleDateChange(value)} value={dateValue} activeStartDate={activeStartDate} onActiveStartDateChange={handleActiveStartDateChange}></Calendar>`

**Comment by aolose** [comment]
> Okay , I tried that now. We have one prop `onActiveStartDateChange`. We can use this change event to set the `activeStartDate`. Could you try the below ?
> 
> `const handleDateChange = (value:Date)=>{ setDateValue(value:Date); setActiveDateStart(value); }`
> 
> `const handleActiveStartDateChange = (values: any) => { setActiveStartDate(new Date(values.activeStartDate)); }`
> 
> `<Calendar onChange={(value) => handleDateChange(value)} value={dateValue} activeStartDate={activeStartDate} onActiveStartDateChange={handleActiveStartDateChange}></Calendar>`

It works! Thank you.
