### ISSUE TITLE
How can I prevent the list of months being shown on clicking the month name?

### ISSUE THREAD

**Issue by SharonGilmore** [wojtekmaj/react-calendar#392]
I'm using this plugin within a date picker component.  I want the user to be able to navigate back and forth between dates, BUT I don't want them to be able to click the Month ('June 2020') in the navigation bar.  I think it will be confusing for my users if they click that and the months appear.

Is there a way to disable this functionality?

**Comment by HARIKSREEE** [comment]
HI @SharonGilmore 
You can try adding `pointer-events:none` to the `class="react-calendar__navigation__label"`.
Anyway you will be making some style changes to the calendar. There is an option to provide our own class name to the calendar wrapper. So we can override the styles using that.

The style would look like :
Note: you need to do this within your custom class to avoid style bleeding.

`
button.react-calendar__navigation__label{
pointer-events: none;
}
`

**Comment by SharonGilmore** [comment]
Thank you!  That worked!

**Comment by wojtekmaj** [comment]
You can use [`minDetail` and `maxDetail` props](https://github.com/wojtekmaj/react-calendar#props) to limit the views the users can navigate through.

**Comment by SharonGilmore** [comment]
Oh, brilliant, thank you!

**Comment by hjrobinson** [comment]
The CSS pointer events solution didn't work for me. You can still tab on to the button and click enter to open it. Also AFAIK you can't set maxDetail to "day" so the month calendar can still be opened. I love this calendar but I'm thinking the ability to open the month calendar might be confusing to vision impaired users.  If I'm missing something please let me know.

**Comment by hjrobinson** [comment]
I found a hacky solution to this problem using CSS below:

```
button.react-calendar__navigation__label {
  visibility: hidden;
}

.react-date-picker, .react-date-picker *, .react-date-picker *:before, .react-date-picker *:after {
  visibility: visible;
}
```

If there are any problems with this or anyone knows a better solution let me know.
