### ISSUE TITLE
Circle styling instead of squared/rectangle

### ISSUE THREAD

**Issue by mathieupelletier** [wojtekmaj/react-calendar#393]
When trying to style the tile in being a circle to appear when the tile is clicked (using border-radius:50%), it appears as an ovale instead if the calendar is full page. How do we make it so it always appears as a circle?

**Comment by wojtekmaj** [comment]
Use styling to ensure tiles are squares, then you'll have perfect circles. 

General CSS question - I'm not going to keep it open.

**Comment by LouiseReid** [comment]
I'm having the same issue. It comes from the flex basis being set so the width is overridden and so the circles appear as an oval

**Comment by wojtekmaj** [comment]
Can't get any easier than that.

```css

.react-calendar__tile {
  aspect-ratio: 1;
  border-radius: 50%;
}
```

https://codesandbox.io/s/react-calendar-circles-zykocu

**Comment by LouiseReid** [comment]
I ended up changing the display to css grid which also prevents the rows not remaining consistent when the screen resizes
