### ISSUE TITLE
Prevent onViewChange?

### ISSUE THREAD

**Issue by Spring3** [wojtekmaj/react-calendar#396]
Hi! I used this calendar in one of the projects, but I haven't found a way to block the call to onViewChange() as a result of clicking on a calendar's navigation button. Is there a way to prevent it?

This is the way I set up a calendar

```jsx
  const [date, setDate] = useState(new Date());

  const onChange = (date: Date | Date[]) => {
    setDate(date as Date);
  }

  return (
    <Calendar
      showDoubleView={true}
      selectRange={false}
      calendarType="US"
      view="month"
      defaultView="month"
      defaultValue={new Date()}
      value={date}
      onChange={onChange}
    />
  );
```

I'm using v3 of the component

I only need the user to navigate between the months, but for now if they click on the navigation, it jumps to the beginning of the current year. 

Is there a way to prevent a click on navigation? Or at least to have it jump to current date instead?
Maybe something like `e.preventDefault()` inside the `onViewChange()`?

**Comment by syntaxbliss** [comment]
I'm facing the exact same issue. I came up with the following workaround:

```
.react-calendar__navigation button:nth-child(X) {
    pointer-events: none;
}
```

...whereas ```X``` is the child number of the button used to change the view. Hope it helps!

**Comment by wojtekmaj** [comment]
In your code, you opted for `defaultView`. This means that `view` is uncontrolled. If you used `view` prop instead, and ignored `onViewChange` in certain situations, the view would not change. 

This is exactly like in inputs: you can either use `defaultValue` or `value` + `onChange`. If you used `value` prop and ignored `onChange` in certain situations, the input value would not change.

**Comment by sushmitg** [comment]
this seemed to have worked for me.

```

function App() {
  const [value, onChange] = useState(new Date());
  const [showCalendar, setShowCalendar] = useState(true);


  const onViewChange = ({ action, activeStartDate, value, view }) => {
    if (action === "drillUp") {
      onChange(value)
    }
  }

  const onDrillUp = () => setShowCalendar(prev => !prev)

  return (
    <div className="App">
      <Calendar
        className={showCalendar ? "" : "hide"}
        view='month'
        onChange={onChange}
        value={value}
        activeStartDate={value}
        onActiveStartDateChange={({ activeStartDate }) => onChange(activeStartDate)}
        onDrillUp={onDrillUp}
        onViewChange={onViewChange}
      />
    </div>
  );
}

export default App;
```

but it would pe better if we had something like `onDrillUp = (e) => e.preventDefault();`
