### ISSUE TITLE
MonthView Support

### ISSUE THREAD

**Issue by lemmingapex** [wojtekmaj/react-calendar#4]
Wojciech,

First, thank you for continuing to develop and support this product.  I was confused and disappointed to see that zippyui and Radu Brehar (https://github.com/radubrehar) seemed to completely disappear and abandon the react-date-picker.  I think this collection of date utilities is one of the best around.  I am excited to see that you are keeping it up with the latest versions of react.

I am using the MonthView from react-date-picker 5.3.28.  I see that you have migrated some of the components (like MonthView, YearView, and DecadeView) to this library.  I've noticed that some functionality is no longer supported in MonthView.
Specifically, the following props:
```
weekNumbers
highlightRangeOnMouseMove
defaultRange
viewDate
constrainViewDate
range
onViewDateChange
onActiveDateChange
onRangeChange
```

What are your plans for supporting these?  Most important to me are weekNumbers, range, onViewDateChange, onActiveDateChange, and onRangeChange.  I am very willing to help.  I was able to get a copy of the original 5.X code before it went away: https://github.com/lemmingapex/react-date-picker

I don't know if that is at all helpful to you.  Please let me know what your thoughts are and how I can help.  Thanks!

**Comment by wojtekmaj** [comment]
Hey @lemmingapex,
thanks for the kind words!

Sadly, the documentation to react-date-picker 4.x and below is severely lacking.

Straight to the point:

* `weekNumbers` is supported, but it's now called `showWeekNumbers`. You can pass it to `<Calendar>` and `<MonthView>` components.
* `range` probably will work a little differently than before but it's certainly on my list for react-date-picker!
* `onViewDateChange` - Do I understand correctly, that you would like to be informed if the user jumps between decade/year/month views? If so, what info would you like to see?
* `onActiveDateChange` - Is "active date" simply a date telling you which period the user currently has displayed on the screen? For example, for October 2017 you would like to get `[Date 2017-10-01T00:00:00.000Z, Date 2017-10-30T23:59:59.999Z], 'month'`?
* `onRangeChange` sounds like just it would simply be handled by onChange, once ranges are implemented...

**Comment by mweibel** [comment]
Came here to add my +1 on the range. I use the datepicker in MonthView for a range on [rokka-dashboard](https://github.com/rokka-io/rokka-dashboard) and another project (not public) and I'm currently looking for alternatives. None yet fulfilled my need, that's why I started yesterday [with upgrading my copy of react-date-picker](https://github.com/mweibel/react-date-picker/pull/3) but there's quite some work to do in order to get rid of some of the packages it depends on and aren't react 16 compatible yet (and by the same author). 

Anyway, for me the range is most important too. Is there anything I can do to help?

**Comment by wojtekmaj** [comment]
Hey @lemmingapex and @mweibel,
I have good news! Starting with React-Calendar 2.10.0 selecting date ranges is supported. Hope you enjoy it! Let me know if you have any further comments or suggestions.
