### ISSUE TITLE
react-calendar doesn't support in Internet Explorer

### ISSUE THREAD

**Issue by web223dev** [wojtekmaj/react-calendar#40]
It works another browsers. But It's not work in IE11. The error is as follow.

"TypeError: Object doesn't support property or method 'isNaN'.

bundle.js
...
if (Number.isNaN(valueFromDate.getTime())) {
     throw new Error('Invalid date: ' + value);
}
...

**Comment by wojtekmaj** [comment]
Hello @web223dev,
found that pretty critical so I released version 2.13.1 fixing this. Thank you!
