### ISSUE TITLE
Disable specific dates

### ISSUE THREAD

**Issue by andymj** [wojtekmaj/react-calendar#400]
Hi!, I would like to disable specific dates passing an array of the dates to a prop, see the example below. Any advice on where or how to accomplish this? 

```javascript
const disabledDates = ['08/04/2020', '08/08/2020', '08/15/2020'];

<Calendar 
  ...props, 
  disabledDates={disabledDates}
/> 
```

Thanks!

**Comment by wojtekmaj** [comment]
Check out tileDisabled prop. That's exactly what you want, but in order for more flexibility, you'll need to write this function yourself so that it would return true for matching dates.

**Comment by andymj** [comment]
Thanks for your reply @wojtekmaj , I was able to implement the callback to disable/enable specific dates. Are there gonna be any updates to the component in the future to support a prop like the one I described? or it will be the way you mentioned with passing a callback to tileDisable prop?

**Comment by wojtekmaj** [comment]
I'm not planning to introduce a second prop that does roughly the same thing. I understand the need for simplicity, but adding a second prop would make it all more confusing. What if both are given? 😅

If I was to make it simpler, I would rather come up with something like react-calendar-utils which would be a separate library that makes it easier to make these kinds of functions using provided helpers: disableDates, disableBefore, disableAfter, disableAllExcluding, etc. :)

**Comment by zamiramiludin** [comment]
> I'm not planning to introduce a second prop that does roughly the same thing. I understand the need for simplicity, but adding a second prop would make it all more confusing. What if both are given? 😅
> 
> If I was to make it simpler, I would rather come up with something like react-calendar-utils which would be a separate library that makes it easier to make these kinds of functions using provided helpers: disableDates, disableBefore, disableAfter, disableAllExcluding, etc. :)

Do you have the code? Can you share it. I need help

**Comment by zamiramiludin** [comment]
> Thanks for your reply @wojtekmaj , I was able to implement the callback to disable/enable specific dates. Are there gonna be any updates to the component in the future to support a prop like the one I described? or it will be the way you mentioned with passing a callback to tileDisable prop?

I really hope if you can share your code. it really helps. Thank you.

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-disable-tiles

**Comment by VladTzaru** [comment]
Siema, Wojtek. do you perhaps have a useCallback implementation example? I have some dynamic data and I'd like to memoize the callback, I tried something like this:

```
  const tileDisabled = useCallback(
    ({ date }: CalendarTileProperties) => {
      if (apiData)
        return apiData.excludedDates.some((dDate) => isSameDay(dDate, date));
    },
    [apiData]
  );
```
`apiData ` is an object that includes excludedDates: `[date1, date2, date3....].`
Does not seem to work. I understand that this isn't a Calendar-specific issue, I am just curious how would you implement it.  
Thanks a lot for the amazing Calendar and your attention to this matter.

**Comment by wojtekmaj** [comment]
@VladTzaru What do you mean by "doesn't work"? Do you think you could make a code sandbox to have a look at a (not so) working example?

**Comment by VladTzaru** [comment]
@wojtekmaj Tile disabling works like a charm, I was referring to this particular `useCallback` implementation. It does not seem to memoize the function correctly. So it's affecting the performance a bit. Nothing to do with the Calendar, rather my implementation of the `useCallback()`. That's why I was curious about your implementation. I will do my best to make a sandbox for your review.

Thanks for your suggestions/help!

**Comment by VladTzaru** [comment]
@wojtekmaj Hi again, just to let you know I've resolved it. Forgot to use `React.memo()`. Oops. :) 

In any case, thanks for the great work! Take care!
