### ISSUE TITLE
Albanian locale

### ISSUE THREAD

**Issue by Albimeri** [wojtekmaj/react-calendar#403]
I am happy to inform you that for quite some time I've been using this package in a project that I am currently working and it performs incredibly good, nevertheless, I now have a need for internationalization in 3 languages as start. One of those languages happens to be Albanian. I tried using the prop 'locale' as you stated in documentation of 'react-calendar', but it doesn't seem to work. 
The options I tried: 'sq', 'al', 'sq-al', 'al-sq', 'sq-sq', 'al-al'.
I am looking forward to hearing from you. 
Sincerely Alb.

**Comment by wojtekmaj** [comment]
sq-AL seems to work just fine :) 

![obraz](https://user-images.githubusercontent.com/5426427/87442538-b48c3100-c5f4-11ea-8110-539a9ab8826e.png)

**Comment by Albimeri** [comment]
![image](https://user-images.githubusercontent.com/14825806/87443971-7abc2a00-c5f6-11ea-9565-016f515b21e3.png)

this is the code,

![image](https://user-images.githubusercontent.com/14825806/87444013-86a7ec00-c5f6-11ea-8bc3-c43328be8e6f.png)

but doesn't seem to do that work

**Comment by wojtekmaj** [comment]
Looks like the browser you're developing on has limited support for this particular locale then. React-Calendar relies on browser implementation of Intl. On both of my machines sq-AL works just fine.

**Comment by Albimeri** [comment]
Yes indeed, that is the case. I tried Chrome, Edge and Firefox and it works only on Firefox.

**Comment by wojtekmaj** [comment]
Unfortunately since React-Calendar i18n depends entirely on browser's support for Intl, there's nothing I can personally do.
However, note that in our [README](https://github.com/wojtekmaj/react-calendar/) there's Intl polyfill mentioned, and this polyfill [actually supports sq-AL locale](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/sq-AL.json).
