### ISSUE TITLE
Add specific class to future dates

### ISSUE THREAD

**Issue by acontreras89** [wojtekmaj/react-calendar#408]
It would be handy to have a specific class applied to tiles for future dates (e.g. `react-calendar__tile--future`).

**Comment by acontreras89** [comment]
I still think this would be a very nice-to-have feature. Please, don't close it @github-actions 😅

**Comment by acontreras89** [comment]
Again, this could be very useful to have.

**Comment by wojtekmaj** [comment]
That's too much functionality one could easily add in a few lines. Basically:

```js
function tileClassName({ date }) {
  if (isDateInTheFuture(date)) {
    return 'react-calendar__tile--future';
  }
}
```

https://codesandbox.io/s/react-calendar-future-classname-jcc1p

**Comment by acontreras89** [comment]
👍  didn't know about `tileClassName`, my bad
