### ISSUE TITLE
Prevent switching back to starting date when selecting a range

### ISSUE THREAD

**Issue by dudovcic** [wojtekmaj/react-calendar#409]
Any way to do this atm or is there a WIP for such a props option perhaps ?
I'd like to prevent the calendar from switching back to the starting date's month, ie. if you select a range where starting date is in July and end date in September it goes back to July instead of staying on September.

**Comment by dudovcic** [comment]
Resolved, if for anyone wondering the same...

Something along the lines of:

calendarRef.current.setState({
   activeStartDate: calendarRef.current.state.value[1], // value[1] being endDate
});

**Comment by ZeroCho** [comment]
https://github.com/wojtekmaj/react-calendar/issues/378#issuecomment-1307259443

this is how you can resolve this problem
