### ISSUE TITLE
Disable specific weekdays

### ISSUE THREAD

**Issue by bruno-barros** [wojtekmaj/react-calendar#411]
Is it possible to disable specific weekdays?
Ex: User can't selec any day on saturday and sunday.
Thanks

**Comment by HARIKSREEE** [comment]
There is prop called 'tileDisabled' where you can pass a function. Within that function, you can determine which date to be diabled.

**Comment by Herting** [comment]
Ye, if you want to disable specific weekdays you should use the tileDisabled function.

```
private tileDisabled = ({date }: CalendarTileProperties & {activeStartDate: Date}) =>
{
   if(!isWeekday(date))
   {
      return true;
   }

   return false;
}
<Calendar tileDisabled={this.tileDisabled} />
```

Then it's dependent of what kind of date you have, use date.getDay() to make sure it's not a saturday or sunday or use another library like "moment-business" to determine it weekday or not.

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-disable-tiles
