### ISSUE TITLE
CSS issue in production

### ISSUE THREAD

**Issue by PK3364** [wojtekmaj/react-calendar#414]
Hi am unable to load the css in production i tried all the ways but still it's the same, works in locally but not in production.
tried all ways of webpack and etc .. can share webpack as well

![Screenshot 2020-07-23 at 6 53 28 PM](https://user-images.githubusercontent.com/68710625/88331916-5c1f0700-cd4b-11ea-95b5-f0d2da4dc767.png)

**Comment by wojtekmaj** [comment]
Fixed by #402. Fix will be live in next release.
