### ISSUE TITLE
Typescript type definitions lacks of allowPartialRange

### ISSUE THREAD

**Issue by ssukienn** [wojtekmaj/react-calendar#415]
As in title. Is it right place to open this issue or rather in DenitelyTyped repo?

**Comment by wojtekmaj** [comment]
Hi, typings are something I don't have a control over and are not in this repository, so I think it's best to raise it in DefinitelyTyped.

**Comment by ssukienn** [comment]
PR for this was merged in DefinitelyTyped repo some time ago. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46384

I am closing. Thanks.
