### ISSUE TITLE
Can't find dependent @wojtekmaj/fdate-utils

### ISSUE THREAD

**Issue by seetoml** [wojtekmaj/react-calendar#417]
Having the issue of installing react-calendar. It returns 404 error.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@wojtekmaj%2fdate-utils - Not found   
npm ERR! 404
npm ERR! 404  '@wojtekmaj/date-utils@^1.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-calendar'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Is the dependent being removed? Will there be any update on react-calendar? Please assist.

**Comment by Tusky** [comment]
Same issue with Yarn, but it seems to me it's an NPM issue, as https://www.npmjs.com/package/@wojtekmaj/date-utils it does exist, and has that version, but NPM randomly throws Internal Service Errors, and ESOCKETTIMEOUTS at the moment.

**Comment by wojtekmaj** [comment]
npm outage indeed.
