### ISSUE TITLE
Calendar not Displaying Properly

### ISSUE THREAD

**Issue by AnkitBagaria24** [wojtekmaj/react-calendar#418]
I am attaching a screenshot in order to show how the calendar is displaying. I am using the latest version of Firefox. Also pasting the code. Please help this doesnot look elegant.
```

...
const MarkAttendance = function ({ businessid, fyid }) {
    let date = new Date();
    let redirect = (newdate) => {
        date = newdate; 
        alert(date);
    }
    let [isOpen, setIsOpen] = useState(false);
    let toggle = () => setIsOpen((!isOpen));
    return (
        <div className="d-flex justify-content-center mt-4">
            <div className="col-12 col-md-4">
                <Button className="btn-sm mb-1 mt-1 col-md-12 btn-danger" onClick={toggle}>Mark Attendance</Button>
                <Collapse isOpen={isOpen}>
                    <div className="row">
                        <Calendar onChange={redirect} value = {date}/>
                    </div>
                </Collapse>
            </div>
        </div>);
}
...
```

![Screenshot from 2020-08-09 17-19-29](https://user-images.githubusercontent.com/62637739/89731441-a818be00-da64-11ea-98aa-0f76401a6ca8.png)

**Comment by AnkitBagaria24** [comment]
It will be helpful if the need to include css file via **import 'react-calendar/dist/Calendar.css** can be included in the documentation.

**Comment by wojtekmaj** [comment]
Usually it's not required. Webpack and Parcel pick the import up correctly.
