### ISSUE TITLE
Center the Calendar on the page 

### ISSUE THREAD

**Issue by SrAMyrick** [wojtekmaj/react-calendar#419]
Hello, I've got a bit of a silly question. However, I can't figure out how to center the Calendar on the page.
Anyone have any idea?

**Comment by HARIKSREEE** [comment]
The calendar container will be an absolute element. You might need ti make it fixed and apply the top and left to 50%. So this will make your calendar adjust relative to viewport

**Comment by skizzo** [comment]
You can achieve this by adding **`margin: 0 auto;`** to the css, so it looks like:

```
.react-calendar {
  width: 350px;
  max-width: 100%;
  background: white;
  border: 1px solid #a0a096;
  font-family: Arial, Helvetica, sans-serif;
  line-height: 1.125em;
  margin: 0 auto; // <-- there you go
}
```
