### ISSUE TITLE
Unable to use US calendar

### ISSUE THREAD

**Issue by davidkhayutin** [wojtekmaj/react-calendar#422]
Hey guys

I have the following props passed into my cal

  locale="en-US"
  calendarType="US"

but my calendar always displays monday => Sunday.. when i want it to be Sunday => Saturday(normal - what is displayed on demos for this package)

Can someone let me know what I am doing wrong?

thanks!

**Comment by wojtekmaj** [comment]
`calendarType` is picked automatically based on `locale`, so in this case you should not need to even pass `calendarType` at all.

Does that not work for you?

https://codesandbox.io/s/react-calendar-us-calendar-zrdxy

**Comment by davidkhayutin** [comment]
No

I was originally not passing it all and the calendar was the same. Nothing
has changed since I started passing the two props

**Comment by wojtekmaj** [comment]
That's odd, all browsers I tested on Windows and macOS work properly on the example I provided above. Can you share technical details of your test environment, and try other browsers too?

**Comment by ifightcrime** [comment]
I'm running into this problem as well. `calendarType` does nothing... leaving it off does nothing.
