### ISSUE TITLE
showDoubleView on mobile

### ISSUE THREAD

**Issue by fredshevek** [wojtekmaj/react-calendar#424]
Hi,

Is there an option to vertically stack months on `showDoubleView` set to true? Ideally in a responsive way.

**Comment by TeChn4K** [comment]
It is doable from css!

This example overrides default styles:
```
.react-calendar--doubleView .react-calendar__viewContainer {
    display: flex;
    flex-direction: column;
}
.react-calendar--doubleView .react-calendar__viewContainer > * {
    width: auto;
}
```

**Comment by dovigz** [comment]
Heres what I did by stacking tweo calendars and manipulating logic and css

`import React, { useRef, useState } from "react";
import { useDispatch } from "react-redux";
import Calendar from "react-calendar";
import { setDateRange } from "@/redux/slices/travelInfoSlice";
import "react-calendar/dist/Calendar.css";

const CalendarContainer = ({ tripType, dateRange, setShowUpdateButton }) => {
  const dispatch = useDispatch();

  const [startDate, setStartDate] = useState(new Date(dateRange[0] || null));
  const [endDate, setEndDate] = useState(new Date(dateRange[1]) || null);

  const [activeStartDate, setActiveStartDate] = useState(new Date(dateRange[0] || new Date()));

  // Handle date clicks based on tripType
  const handleDateClick = (value) => {
    if (tripType === "One-way") {
      // Single date logic
      setStartDate(new Date(value));
      setEndDate(null);
      dispatch(setDateRange([value, null]));
      setShowUpdateButton(true);
    } else {
      // Range selection logic
      if (startDate && endDate) {
        setStartDate(new Date(value));
        setEndDate(null);
      } else if (!startDate) {
        setStartDate(new Date(value));
      } else if (startDate && value >= startDate) {
        setEndDate(new Date(value));
        dispatch(setDateRange([startDate, value]));
        setShowUpdateButton(true);
      } else {
        setStartDate(new Date(value));
        setEndDate(null);
      }
    }
  };

  // Handle active month navigation (skip by two months)
  const handleActiveStartDateChange = ({ action }) => {
    const newDate = new Date(activeStartDate);
    if (action === "next") {
      newDate.setMonth(newDate.getMonth() + 2);
    } else if (action === "prev") {
      newDate.setMonth(newDate.getMonth() - 2);
    }
    setActiveStartDate(newDate);
  };

  const nextMonth = new Date(activeStartDate);
  nextMonth.setMonth(activeStartDate.getMonth() + 1);

  // Highlight tiles conditionally
  const tileClassName = ({ date }) => {
    if (startDate && date.toDateString() === startDate.toDateString()) {
      return "start-date";
    }
    if (endDate && date.toDateString() === endDate.toDateString()) {
      return "end-date";
    }
    if (tripType !== "One-way" && startDate && endDate && date > startDate && date < endDate) {
      return "in-range";
    }
    return null;
  };

  return (
    <div style={{ display: "flex", flexDirection: "column" }}>
      <Calendar
        onClickDay={handleDateClick}
        calendarType="gregory"
        activeStartDate={activeStartDate}
        onActiveStartDateChange={handleActiveStartDateChange}
        tileClassName={tileClassName}
        showNeighboringMonth={false}
        selectRange={tripType !== "One-way"}
        prev2Label={null}
        next2Label={null}
        minDate={new Date()}
      />

      <Calendar
        onClickDay={handleDateClick}
        calendarType="gregory"
        activeStartDate={nextMonth}
        tileClassName={tileClassName}
        showNeighboringMonth={false}
        selectRange={tripType !== "One-way"}
        prevLabel={null}
        nextLabel={null}
        prev2Label={null}
        next2Label={null}
        minDate={new Date()}
      />
    </div>
  );
};

export default CalendarContainer;
`

`/* react date style */
.react-calendar {
  width: 100% !important;
  border: none !important;
  background: transparent !important;
  margin-bottom: 30px !important;
}

.react-calendar__month-view__weekdays__weekday abbr {
  text-decoration: none !important;
}
.react-calendar__tile--rangeStart,
.react-calendar__tile--rangeEnd,
.react-calendar__tile--rangeBothEnds,
.react-calendar__tile--active {
  background: none !important;
  color: inherit !important;
  border: none !important;
  box-shadow: none !important;
}

/* Custom styles for selected tiles */
.react-calendar__tile.start-date {
  background: #76baff !important;
  color: white !important;
}

.react-calendar__tile.end-date {
  background: #76baff !important;
  color: white !important;
}

.react-calendar__tile.in-range {
  background: #006edc !important;
  color: white !important;
}

.react-calendar__tile:focus {
  outline: none !important; /* Remove focus outline */
}


/* Disable interaction on the navigation label */
.react-calendar__navigation__label {
  pointer-events: none !important; /* Block all clicks */
  cursor: default !important;      /* Remove pointer cursor */
}`
