### ISSUE TITLE
disable dates before current date

### ISSUE THREAD

**Issue by dumkanki** [wojtekmaj/react-calendar#425]
hello @all 
please help me to find the solution as i want to disable the dates that are before current date.

Thnaks!

**Comment by Herting** [comment]
You could use minDate and pass in todays date to disable all dates before todays date. You could also use tileDisabled.

`<Calendar
 minDate={new Date()}
/>`

Or

```
private tileDisabled = ({date }: CalendarTileProperties & {activeStartDate: Date}) =>
{
   if(date.valueOf() < todaysDate.valueOf()) {
      return true;
   }
}

<Calendar tileDisabled={this.tileDisabled} />
```

**Comment by wojtekmaj** [comment]
In general, `minDate` is the best to disable **all** dates before a certain date. `tileDisabled` is best when you want to disable select dates. So in this case, `minDate` is the way.

**Comment by dumkanki** [comment]
thanks @Herting @wojtekmaj
