### ISSUE TITLE
show selected dates by daefault.

### ISSUE THREAD

**Issue by dumkanki** [wojtekmaj/react-calendar#426]
Hello,
Is this possible in react-calendar let say i have some dates and i want these dates should be in diferent color . for eg-
![Capture](https://user-images.githubusercontent.com/38756726/91468798-215f4000-e8b0-11ea-9f0f-a6615a9a1b9a.PNG).

In this image you can see that 28 and 31 are in a different view.
So it is possible to implement this . Looking for the help.

Thanks!

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-calendar/issues?q=is%3Aissue+tileClassName :)
