### ISSUE TITLE
tileClassName not working properly

### ISSUE THREAD

**Issue by dumkanki** [wojtekmaj/react-calendar#428]
Hello

 as i am using tileClassName in this way .

```js
<Calendar
  tileClassName={({ date }) => {
    this.checkdates.forEach((data, index) => {
      let datedata = new Date(data)
      let dateOne = moment(date).format('L');
      let datetwo = moment(datedata).format('L');
      if (dateOne === datetwo) {
        return "testdata";
      } else {
        return null;
      }
    })                             
  }}
  minDate={new Date()}
  tileDisabled={this.disableddate}
  onChange={this.ondateChange}
  value={this.state.date}
/>
```

and in css file i have made the class name testdata

```css
.testdata {
  background-color: blue;
  color: red !important; 
}
```

but the change i can't see in calendar dates even though the condition is matched . Please help

**Comment by wojtekmaj** [comment]
The reason your code doesn't work is because you return nothing from tileClassName.

Modify your code so that tileClassName function returns the class name. It'll work.

Example solution: https://codesandbox.io/s/react-calendar-tile-class-name-dumkanki-lppn0

**Comment by dumkanki** [comment]
thank you so much for your help.

Thanks & regards
Ankit Dumka

**Comment by LeandroFrazao** [comment]
Hello,
I am trying to apply tileClassName to my react native project, but it doesnt work.
Is there any way I can use stylesheet instead of css file?

**Comment by wojtekmaj** [comment]
I think you're in a wrong repository @LeandroFrazao. This is not a package intended for React Native.
