### ISSUE TITLE
Saturday appears two times on Safari

### ISSUE THREAD

**Issue by mvegaxx** [wojtekmaj/react-calendar#429]
hello i have a problem with weekday, in my calendar Saturday appear two times, this problem show in spanish version 

![image](https://user-images.githubusercontent.com/29684669/92745313-dd584a80-f347-11ea-9120-cd7c02ffe3ec.png)

![image2](https://user-images.githubusercontent.com/29684669/92745462-04168100-f348-11ea-9f81-298236502ecd.png)

**Comment by mvegaxx** [comment]
update: this issue only appear on safari

**Comment by aqarain** [comment]
have you fixed it?

**Comment by mvegaxx** [comment]
the problem continues, do you have the same problem?

**Comment by aqarain** [comment]
@mvegaxx no I dont have that issue. Just checked!

**Comment by wojtekmaj** [comment]
Couldn't reproduce this either, on Safari 14...

**Comment by mvegaxx** [comment]
Thanks for your answer, the version where the error appears is in 13.1.2, but some of my colleagues cannot reproduce the error either

**Comment by wojtekmaj** [comment]
Closing this for now, unless a more-or-less reliable way to reproduce this can be figured out.
