### ISSUE TITLE
Change month name / placeholder

### ISSUE THREAD

**Issue by maticwi** [wojtekmaj/react-calendar#437]
Hey, is it possible to change month names? I want to use Mo, Th, Fr instead of MON, THU, FRI.

I tried many ways to change placeholder, i guess the best option is to change range divider to own text and manipulate it when user pick date, but there is a problem with "/" separator - how can i remove it? Or maybe there is another way to put placeholder with text instead of --/--/---- ?

Have a nice day for everyone who read it!

**Comment by wojtekmaj** [comment]
You're looking for `formatShortWeekday`. See README for details.
