### ISSUE TITLE
 How to customize multiple styles？

### ISSUE THREAD

**Issue by mayday7** [wojtekmaj/react-calendar#439]
![image](https://user-images.githubusercontent.com/17946590/94542447-67c30880-027b-11eb-8c61-d9e4cf8f1df0.png)

how to customize multiple styles？
use tileClassName？

**Comment by wojtekmaj** [comment]
Yes, tileClassName is a good choice. You can pass multiple class names to given tiles using tileClassName either by returning `'foo bar'` or `['foo', 'bar']` from said function.
