### ISSUE TITLE
Selection multiple dates instead of range

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [wojtekmaj/react-calendar#441]
Hello everyone. I use react-calendar in my project. I need to select several different days, but I can't do it. Is there possibility to do it?  I've found only range of dates selection in documentation.

This question asked [here](https://stackoverflow.com/questions/56952474/display-multiple-dates-on-react-calendar), but nobody answered it.

**Comment by wojtekmaj** [comment]
Duplicate of https://github.com/wojtekmaj/react-calendar/issues/136

See also:

https://github.com/wojtekmaj/react-calendar/issues/372#issuecomment-626765879

https://github.com/wojtekmaj/react-calendar/issues/295#issuecomment-576028778
