### ISSUE TITLE
How to change the background of selected date dynamically?

### ISSUE THREAD

**Issue by aqarain** [wojtekmaj/react-calendar#443]
How can I change the background color of selected date when a condition is fulfilled?
For e.g. I selected a date and a method fires and checks a condition and if that condition is true, I want its background to be red.

**Comment by wojtekmaj** [comment]
You would probably like to use `tileClassName` function for that. Make sure to memoize the function so that it doesn't change with every render, but rather whenever its dependency gets updated. Use useCallback if you can.
