### ISSUE TITLE
Customizing the style

### ISSUE THREAD

**Issue by 70Ni** [wojtekmaj/react-calendar#446]
Imported the styling css file to App.js using import 'react-calendar/dist/Calendar.css';

However i can edit the less and  css file. But it is not updating in the browser. Does it need any special editing?

**Comment by mriot** [comment]
You shouldn't edit the less/css file within the package itself. Instead, create a custom stylesheet and modify the styles you want to change.

**Comment by chaitanya005** [comment]
I created a custom stylesheet but not able the modifying the styles

**Comment by wojtekmaj** [comment]
The correct way is to either:

* copy the original CSS into your repository
* import it instead of the original CSS

or:

* keep the original CSS
* create a new CSS file in your repository and add your custom overrides
