### ISSUE TITLE
Unable to clear selection when switching selectRange

### ISSUE THREAD

**Issue by totobest** [wojtekmaj/react-calendar#447]
Kind of similar to #427 . I made a simple example to show case the issue: 
https://codesandbox.io/s/nameless-pine-me89d?file=/src/App.js

**Steps to reproduce :**

1. Have selectRange to **false**
2. Pick a date
3. Reset the calendar (Set value to **null**)
4. Set selectRange to **true**
5.  Pick a date

**Expected outcome :**

The calendar is ready to accept the first date of the range

**Result outsome :**

The first date is already chosen (taken from step 2) and the calendar is showing a range.

react-calendar version 3.1.0

**Comment by wojtekmaj** [comment]
You could use key prop trick to reset Calendar internal state. I know it's not perfect but should do the job!
