### ISSUE TITLE
[Question] Go to today

### ISSUE THREAD

**Issue by misshu1** [wojtekmaj/react-calendar#453]
I just upgraded to v3 from v2, and I see that if I navigate to another month and change the calendar value to "today" it will not change the view back, like in v2.

Ex: Today 06 Nov 2020, navigate to 06 Jan 2021, change the calendar value to 06 Nov 2020, the calendar still shows me the Jan 2021 month.

**Comment by wojtekmaj** [comment]
For this to work you will also need to control `activeStartDate` by `onActiveStartDateChange`. Otherwise, once changed from the default, calendar will keep its internal value for active start date.
