### ISSUE TITLE
tileClassName / tileContent

### ISSUE THREAD

**Issue by tylersiskar** [wojtekmaj/react-calendar#455]
I am attempting to use the tileClassName and tileContent properties, and have not been able to reach the **date** and **view** parameters with a function, as illustrated in the documentation.

Also, when I pass content into tileContent, I can see in React Developer Tools that the Tile is receiving that value, but it is not rendering with that content in the DOM. 

Any tips/examples on how to use the props successfully would be greatly appreciated!

**Comment by wojtekmaj** [comment]
You could use `console.log(arguments)` to debug what arguments `tileContent`/`tileClassName` functions are getting.
