### ISSUE TITLE
Is there correct version of Calendar 3.2.0 in `dist` folder of the npm package?

### ISSUE THREAD

**Issue by Jiish** [wojtekmaj/react-calendar#457]
I noticed that after `npm install react-calendar@3.2.0` I still could not access the Calendar's `ref` with the new prop `inputRef`, although it was stated that the feature was added in 3.2.0
https://github.com/wojtekmaj/react-calendar/issues/384#issuecomment-722305279

After inspecting the contents of the `dist` folder, I noticed that the Calendar component file was missing the `inputRef`:
https://npm.runkit.com/react-calendar/dist/esm/Calendar.js?t=1605527616460
https://npm.runkit.com/react-calendar/dist/umd/Calendar.js?t=1605527616460

although the file in `src` does contain the newly added  `inputRef` prop:
https://npm.runkit.com/react-calendar/src/Calendar.jsx?t=1605527616460

am I missing something here, or does the `dist` folder contain a different version of the calendar, than the `src` ?

**Comment by wojtekmaj** [comment]
Hi, thanks for reporting. That is indeed the case. Apologies for the inconvenience.

**Comment by wojtekmaj** [comment]
Released v3.2.1 with necessary fix.
