### ISSUE TITLE
Warning: Failed prop type: Invalid prop supplied to

### ISSUE THREAD

**Issue by MilesMickelson** [wojtekmaj/react-calendar#459]
Receive several error messages at the same time when clicking on any future date but when using just new Date(), I don't get any.
1. Warning: Failed prop type: Invalid prop `value` supplied to `Days`.
2. Warning: Failed prop type: Invalid prop `value` supplied to `TileGroup`.
3. Uncaught Error: Failed to get year from date: Wed Oct 26 2022 00:00:00 GMT-0400 (Eastern Daylight Time).
4. The above error occurred in the <TileGroup> component:

Any help or feedback would be appreciated, thank you

**Comment by wojtekmaj** [comment]
So what value exactly are you providing to React-Calendar?

**Comment by leomendizabal** [comment]
If you want to have no default date selected just provide null instead of an empty string
