### ISSUE TITLE
showNeighboringMonth = false doesn't seem to work when coupled with showDoubleView

### ISSUE THREAD

**Issue by LeoLozes** [wojtekmaj/react-calendar#462]
First of all, thanks for the great component you've made!

I was doing some testing with these parameters, and the `showNeighboringMonth` parameter works as intended:
```
      <Calendar
        minDate={new Date()}
        selectRange={true}
        showNeighboringMonth={false}
        locale={"es"}
      />
```
![image](https://user-images.githubusercontent.com/11133817/100864656-91282c80-3496-11eb-8bdf-c5dcd48f16ca.png)

However when coupling with `showDoubleView`, it doesn't seem to work:
```
      <Calendar
        minDate={new Date()}
        selectRange={true}
        showDoubleView={true}
        showNeighboringMonth={false}
        locale={"es"}
      />
```
![image](https://user-images.githubusercontent.com/11133817/100864864-e5cba780-3496-11eb-8809-a3753b438cc9.png)

Am I doing something wrong on my end?

Edit: found a workaround, by adding a css rule:

```
.react-calendar__month-view__days__day--neighboringMonth {
  display: none;
}
```

**Comment by lauterry** [comment]
Hi

I have the same issue as @LeoLozes 

Thx for the workaround

**Comment by lauterry** [comment]
Hi

The documentation explains well why showNeighboringMonth = false doesn't seem to work when coupled with showDoubleView.

`showDoubleView = true` forces  `showFixedNumberOfWeeks = true` which forces `showNeighboringMonth = true`

<img width="674" alt="Capture d’écran 2021-01-26 à 15 06 09" src="https://user-images.githubusercontent.com/1374238/105855197-1ab43080-5fe8-11eb-9509-3032e42083da.png">

**Comment by LeoLozes** [comment]
You are right! 
However I don't really see why this is enforced since the calendar seems to work fine with the css rule applied, and I think is what makes most sense. You don't really want to see the next month in the first calendar when you have just besides it. 

I'd say is how most of the biggest websites work (and it's why I need it to be that way as well):

<img width="440" alt="AirBNB" src="https://user-images.githubusercontent.com/11133817/105856228-47b51300-5fe9-11eb-9cc2-b820d5f1cfe6.PNG">

<img width="513" alt="Trivago" src="https://user-images.githubusercontent.com/11133817/105856254-50a5e480-5fe9-11eb-91a4-b4efbaa316a3.PNG">

<img width="367" alt="Momondo" src="https://user-images.githubusercontent.com/11133817/105856242-4d125d80-5fe9-11eb-98a2-4e5d46ed673e.PNG">

<img width="327" alt="Booking" src="https://user-images.githubusercontent.com/11133817/105856290-5d2a3d00-5fe9-11eb-8036-ebc8570e88a9.PNG">

**Comment by lauterry** [comment]
Hi @LeoLozes 

I'm totally agree with you.

Maybe the mainteners can explain why `showNeighboringMonth ` is enforced to true when `showDoubleView ` = true ?

Best regards !

**Comment by lauterry** [comment]
@LeoLozes 

BTW, have you encountered the issue explained here https://github.com/wojtekmaj/react-calendar/issues/339 with the DoubleView Calendar ?

If so, how have you solved the pb ?

**Comment by lauterry** [comment]
Hi @LeoLozes 

Your workaround is not totally right and caused this issue : https://github.com/wojtekmaj/react-calendar/issues/482

The correct workaround is : 

```
.react-calendar__month-view__days__day--neighboringMonth {
  visibility: hidden;
}
```

Best regards

**Comment by ivanvanderbyl** [comment]
It'd be great to have a non-css workaround for this, since the css workaround causes other styling issues:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/24278/172739764-e8be7e01-6da1-423e-9f56-470c4415a183.png">

**Comment by J0914** [comment]
Can we come back to this please, this calendar is so great, but this one issue is very frustrating and I don't want to have to spend an hour trying to figure out a workaround, that's why I installed a package lolol this is the ONLY issue I have with this calendar.

**Comment by kyle-ssg** [comment]
I can see why this would be desirable, but not at the end of month a and start of b. This is indeed a really frustrating issue and I echo that the lib is perfect except this.

I'm going to look for a way to patch this but messaging here in case anyone found a solution, hiding the dates in css is obviously flawed since you have a whole row of invisible days on some months.
