### ISSUE TITLE
isWeekend control capability

### ISSUE THREAD

**Issue by SashaDeviaten** [wojtekmaj/react-calendar#464]
Hello! There was a need to implement a calendar of working days. Is it possible to add the isWeekend property to the library so that the developer can define weekends / holidays himself? It would be very cool. As far as I understand, this feature is hardcoded at the moment. Thanks in advance!

**Comment by wojtekmaj** [comment]
Weekends are indeed hardcoded, but you can add your own class names to days using any rule you can imagine by using `tileClassName`.
