### ISSUE TITLE
Disabling default onClick handler completely

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#466]
This change is a hack, too.

In our project, we don't care about the current value of the calendar. However, to "Prevent auto-switching when selecting a date in next month", we must observe the current value which is not useful for our project.

Could we have an option to disable the default onClick handler completely? (We also want to remove the highlight on tiles when clicking)

_Originally posted by @iamacoderguy in https://github.com/wojtekmaj/react-calendar/issues/379#issuecomment-740355330_

**Comment by wojtekmaj** [comment]
@iamacoderguy You can't do that at the moment, but you can use Calendar as controlled component effectively disabling all interaction you require.

**Comment by Pingviinituutti** [comment]
Hi!

How would you actually implement this? I currently have the uncontrolled implementation of the `Calendar` ([Link](https://github.com/Pingviinituutti/turnip-stalk-manager/blob/158d061e9819eeb650837097ee3502bf033d226d/src/components/turnipManager.tsx#L145)), but trying this with a controlled implementation (as below) does not seem to work? I also tried an `onChange` function that would only where I compared the new and old date's month and only updated the month (with `setValue`) if they were the same, but that didn't stop the month from switching either.

```
export const CustomCalendar = () => {
  const [ value, setValue ] = React.useState(new Date());
  ...
  return (
    <Calendar
      value={value}
      onClickDay={() => {}}
      onChange={() => {}}
    />
  )
}
```

Thanks for any answers in advance!

Best regards,
Henrik
