### ISSUE TITLE
Help for achieving infinite scroll on mobile

### ISSUE THREAD

**Issue by fredshevek** [wojtekmaj/react-calendar#467]
Hi,

I was wondering if you could provide any help on how to implement infinite scroll on mobile viewports for a vertical layout?

Are there any examples you could point me to?

Thanks

**Comment by wojtekmaj** [comment]
Is this the right repository? There's nothing to scroll in React-Calendar.

**Comment by fredshevek** [comment]
Hi @wojtekmaj 

Maybe it's a stretch but I was thinking, on mobile, a scroll could be achieved, displaying months one below the other as the user scrolls?

**Comment by wojtekmaj** [comment]
Ah, I see. I don't think that would be possible, unfortunately. Some React-Calendar components could help you building such a thing, though; CenturyView, DecadeView, YearView, and MonthView are exported.
