### ISSUE TITLE
Error: Failed to get year from date: Wed Dec 23 2020

### ISSUE THREAD

**Issue by PrinceJelly** [wojtekmaj/react-calendar#469]
I have a question... I've been trying to get the calendar to it's output to simply give me the date within the array and not the timestamp that's included. 
I am also using luxon with this to match the output to what I have in my database.  

I've tried changing locale, I've tried changing the calendarType... However nothing seems to work. 
I've even tried to change `new Date()` format to `DateTime.locale().toRFC2822();`

Is this an issue or is there a way around this? If anyone can please help! Please do. 👍 

Here's my code below: 
```
  let newDate = new Date();

  const [selectedValue, setSelectedValue] = useState(newDate.toDateString(), []);
  console.log(selectedValue);
```
```
      <Calendar
        onClickDay={() => {
          onClickDay();
          openModal();
        }}
        minDetail={"decade"}
        calendarType={"ISO 8601"}
        onChange={setSelectedValue}
        value={selectedValue}
        selectRange={true}
        maxDate={new Date()}
        minDate={new Date(2019, 11, 31)}
        next2Label={null}
        prev2Label={null}
        prevLabel={arrowLeft}
        nextLabel={arrowRight}
      />
```

**Comment by PrinceJelly** [comment]
Looked through the code in the library as well, I noticed that there's a prop that says
`export const formatDate = getSafeFormatter(formatDateOptions);` &
`const formatDateOptions = { day: 'numeric', month: 'numeric', year: 'numeric' };`

I thought then, I'd be able to get my output from my console.log to simply be the formatted date. 

Here's the code I tried below: 

```
import { formatDate } from "react-calendar/src/shared/dateFormatter";

export default function Calender() {
  let newDate = new Date();
  const formatDateOptions = { day: "numeric", month: "numeric", year: "numeric" };
  const formattedDate = formatDate("en-US", newDate);
  console.log(formattedDate);
  const [selectedValue, setSelectedValue] = useState(formattedDate, []);
```

The console.log is right, but the calendar is throwing me an error. 
`output // 12/23/2020`

_```
Error : 
Warning: Failed prop type: Invalid prop `value` supplied to `Days`.
Warning: Failed prop type: Invalid prop `value` supplied to `TileGroup`.
index.js:64 Uncaught Error: Failed to get month from date: 12/23/2020.
```_

**Comment by LucasBoscariole** [comment]
For me, it was that was turning the date into a string and trying to pass to the `value` prop.

The problem is that the `value` has the types `Date | [Date | null, Date | null] | null | undefined`. 

The solution was to verify the type of the value and if it's a `string`, turn into a `Date` type. I needed as a string so I implemented a solution on the value.

From:
`value={calendarValue}`

To:
`value={typeof calendarValue === "string" ? new Date(calendarValue) : calendarValue}`

I hope this can help!
