### ISSUE TITLE
Make react-calendar compatible with redux-form

### ISSUE THREAD

**Issue by BrunitaFernandes** [wojtekmaj/react-calendar#47]
I can't integrate the component on redux form, I tried but the values like onChange is not passed...

**Comment by wojtekmaj** [comment]
Hey Brunita,
if you've been on React 15.x, updating to 2.13.4 may help you. Please let me know if it did; if not we'll see what we can do :)

**Comment by wojtekmaj** [comment]
Hi @BrunitaFernandes, if you still have some issues let me know, I'll be happy to reopen and discuss. Thanks!
