### ISSUE TITLE
how can I add tooltip on selected date.

### ISSUE THREAD

**Issue by bhoomiagrawal** [wojtekmaj/react-calendar#470]

**Comment by lauterry** [comment]
Hi

I used `tileContent` props to add a `<PopoverButton` component.

Here is an example : 

<img width="450" alt="Capture d’écran 2021-01-26 à 14 51 28" src="https://user-images.githubusercontent.com/1374238/105853452-01aa8000-5fe6-11eb-91d1-3ef8c8276271.png">


Best Regards

**Comment by subhayanghosh** [comment]
@lauterry  Can you please share your code? Also is it possible to show the tooltip on hover instead of click?
