### ISSUE TITLE
Disabling weekends

### ISSUE THREAD

**Issue by Ark20** [wojtekmaj/react-calendar#471]
Is there a calendar type or setting that only shows mon-fri?

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-calendar/issues/438

**Comment by Ark20** [comment]
Thanks @wojtekmaj ! How would I target the weekend tiles?

**Comment by wojtekmaj** [comment]
All the code for your specific scenario is in the ticket linked above.
