### ISSUE TITLE
Is there a way to select a date before 1000 ?

### ISSUE THREAD

**Issue by ppprevost** [wojtekmaj/react-calendar#472]
I just need to find select a date for exemple 435 but the app disable the button when you arrive to 1000.

I saw in the code that if <1000 (years ) it disables the calendar ? 

Why ? 

Thank you for helping :)

**Comment by wojtekmaj** [comment]
Heh, it used to be a problem to handle these dates, but now it's not thanks to [date-utils](/wojtekmaj/date-utils) - I'll drop a fix for that.

**Comment by wojtekmaj** [comment]
Released in v3.3.0.

**Comment by ppprevost** [comment]
Oh thank you very much :) it's very helpfull for me !!! :)
