### ISSUE TITLE
react-calendar differently handle edges of the range

### ISSUE THREAD

**Issue by krzysiek1507** [wojtekmaj/react-calendar#48]
Should these 2 tests pass? First doesn't pass but second does.

```js
  it('returns hasActive flag set to true when passed date is start day of the value array', () => {
    const result = getTileClasses({
      value: [new Date(2017, 0, 1), new Date(2017, 0, 31)],
      date: new Date(2017, 0, 1),
      dateType: 'day',
    });

    expect(result.includes('react-calendar__tile--active')).toBe(false);
    expect(result.includes('react-calendar__tile--hasActive')).toBe(true);
    expect(result.includes('react-calendar__tile--hover')).toBe(false);
  });

  it('returns hasActive flag set to true when passed date is end day of the value array', () => {
    const result = getTileClasses({
      value: [new Date(2017, 0, 1), new Date(2017, 0, 31)],
      date: new Date(2017, 0, 31),
      dateType: 'day',
    });

    expect(result.includes('react-calendar__tile--active')).toBe(false);
    expect(result.includes('react-calendar__tile--hasActive')).toBe(true);
    expect(result.includes('react-calendar__tile--hover')).toBe(false);
  });
```

**Comment by wojtekmaj** [comment]
Hi!
That's a very specific internals question ;) Let me explain what's going on under the hood.

## Questions
The questions on which getTileClasses answers by returning CSS classes, are:

- Should the tile be completely selected ie. is value completely overlapping my tile representing 1 day?
- Should the tile be completely selected ie. is value partially overlapping my tile representing 1 day?
- Should the tile be highlighted?

## Your input
### Example 1
You are saying: I have a calendar tile representing a day starting on January 1. Currently selected value is the period from January 1, 00:00 to January 31, 00:00.

The answer to your 1st question is `true` as January 1 clearly is within the range January 1 - January 30 you have selected.
The answer to your 2nd question is `false` as January 1 is *completely*, not *partially* within given range.

### Example 2
You are saying: I have a calendar tile representing a day starting on January 31. Currently selected value is the period from January 1, 00:00 to January 31, 00:00. 

The answer to your 1st question is `false` as January 31 starts on the very same millisecond your `value` ends. It does not overlap the value at all.
The answer to your 2nd question is also `false` as January 31, as we already know, does not overlap the value at all.

So edges are actually treated equal, but in your first example, `date` is touching the `value` boundaries from the inside, in your second example it's touching `value` boundaries from the outside.

Please mind that a day is not represented by `[new Date(2017, 0, 1), new Date(2017, 0, 1)]` or `[new Date(2017, 0, 1), new Date(2017, 0, 2)]`. The day is from the first to the last millisecond of a given day, so `[new Date(2017, 0, 1), new Date(2017, 0, 1, 23, 59, 59, 999)]` (or `[new Date(2017, 0, 1), new Date(2017, 0, 2, 0, 0, 00, -1)]`, same thing). Same rule applies to months, years, decades...

**Comment by krzysiek1507** [comment]
I'm not sure if it makes sense but day is day so there is no difference if it is 8 am or 2 pm. When you use `date` as a value, everything between `00:00:00` and `23:59:59:9999` is the same date. If you want to select specific time, then it makes sense to check it like that. When I want to pick a range of years, then it doesn't matter for visualization if it is `2018-2020`, `2018-01-01 - 2020-01-01` or `2018-01-01 00:00:00 - 2020-12-31 23:59:59:9999` so `2020` shouldn't be marked as `partially`.

Is there any way to display edges differently? Using different color. The only way is to use `tileClassName` with function?

**Comment by wojtekmaj** [comment]
Day indeed is a day, so if you change `date` value to any point in a given day the output should stay the same :) This is not the case for `value` though, which is treated "as is" if provided as an array. If you wanted to check January 1st against January, you should have called

```js
getTileClasses({
  value: new Date(2018, 0, 1),
  valueType: 'month',
  date: new Date(2018, 0, 1),
  dateType: 'day',
})
```

Regarding the case with the years, it's not as easy as it sounds. I wish it was!

If you provide `[new Date(2017, 0, 1), new Date(2017, 0, 31)]`, that's precisely what the value you are going to have visualized.

If you provide `[new Date(2017, 0, 1), new Date(2017, 0, 31, 12, 0, 0)]` then January 31 is going to be partially selected.

`[new Date(2017, 0, 1), new Date(2017, 0, 31, 23, 59, 59, 999)]` - you've selected it all and it will be marked as such.

The logic behind React-Calendar also supports cases like providing specific time (yes, you can select half a day). Even if you don't want React-Calendar to return values smaller than 1 day, you can still provide them. That being said, I can't simply round everything to midnight.

**Comment by krzysiek1507** [comment]
Thank you for the explanation! Time is always hard to handle so maybe it should be a way to round everything?

I see that I wanted to use this `hasActive` in a way that it wasn't designed (it looked like it showed edges). I think we can close this issue!

**Comment by wojtekmaj** [comment]
Regarding your second question, that's not currently supported out of the box, but `tileClassName` prop should come to the rescue :)
