### ISSUE TITLE
Fake date range or Decoupled showDoubleView

### ISSUE THREAD

**Issue by afridley** [wojtekmaj/react-calendar#481]
I have two seperate calendars that I would like to display a range on.

The first is the start calendar which starts 3months before the end calendar. I would like to specify an end range that would only be used to display the range visually between the the date and the rangeDate passed in.

For the second calendar I would like the range to go back to the start calendars date.

I was hoping to just use showDoubleView. But this seems to couple the title xdate - xdate. Where for layout purposes I would like the 2 calendars to be independent outside the dates being selected. So clicking on the month on the right calendar would zoom out to the year view but only for that calendar.

showDoubleView also only seems to show the next month even if a range is in place. and not the endDate on the right and the startDate on the left.

I currently have everything working other then the range styling between the 2 dates on separate calendars. Which I was hoping to fake.

I was wondering if anyone has run into this problem or has a workaround.

**Comment by wojtekmaj** [comment]
If you know start date and end date, you can use tileClassName to implement your own algorithm to add classes to tiles that fall between given start/end dates.
