### ISSUE TITLE
Wrong week number in the end of the year (year which starts not from the Monday)

### ISSUE THREAD

**Issue by pink-bunny** [wojtekmaj/react-calendar#484]
There is a trouble with week number at the end of the years (year which starts not from the Monday).
I suppose the last week number in 2020 should be equal to 53.

[Example on codesandbox](https://t1cv2.csb.app/)

**Comment by oliverdendis** [comment]
@pink-bunny 
 * In ISO 8601, Arabic and Hebrew week 1 is the one with January 4.
 * In US calendar week 1 is the one with January 1.
