### ISSUE TITLE
[Question] Disable navigation label functionality 

### ISSUE THREAD

**Issue by lorenzocorallo** [wojtekmaj/react-calendar#488]
Hello developers. I would like to maintain the navigation, but to permit using only the arrows to move between the months, 'cause I don't need to go far more than a year. So I would like to know if there is the method to disable navigation label button click function or if needs to be implemented.
In case it needs to be implemented,  could you? Or maybe you can give me the method to disable it via props or something like that.

Thanks and cheers

**Comment by wojtekmaj** [comment]
Use minDetail and maxDetail props to control how far you can "dive in" and "out" on the calendar.
