### ISSUE TITLE
Timezone not displaying correctly

### ISSUE THREAD

**Issue by nharchitecture** [wojtekmaj/react-calendar#492]
Hi,
Firstly, let me say this web part is beautiful. 
Our only issue is that the times are being displayed incorrectly.  It appears that its not recognising daylight savings time.  We are currently in DST in Melbourne Australia, and its not showing it.
How can this be fixed / enabled?
Thanks

**Comment by wojtekmaj** [comment]
Can you give me an example of how would this affect the calendar?

**Comment by nharchitecture** [comment]
When someone books something in the calendar, it shows the wrong time.

For example, if someone has booked an event for 9am, it will show the event as 8am.

Thanks

Alexis Spencer​

IT Manager
She/Her/Hers

[NH Architecture]<http://www.nharchitecture.net/>
t +61 3 9654 4955
|
d +61 3 9491 9090<tel:+61%203%209491%209090>
|
m +61 482 014 113



Level 7, Cannons House
​12‑20 Flinders Lane,
​Melbourne 3000

www.nharchitecture.net<http://www.nharchitecture.net/>
[Instagram]<http://instagram/nharchitecture>
[LinkedIn]<https://www.linkedin.com/company/nharchitecture>
[Facebook]<https://www.facebook.com/NHArchitecture1>



[cid:image005.png@01D70EB8.2269CF50]
NH Architecture is proud to acknowledge the Traditional Custodians of the land on which our studio and projects are situated. We pay our respects to their Elders, past, present and emerging.
Please consider the environment before printing this email.
Disclaimer: This message contains privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message, you are hereby notified that you must not disseminate, copy, or take action in reliance on it. If you have received this email in error please notify NH Architecture immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the view of NH Architecture.

**Comment by wojtekmaj** [comment]
React-Calendar always uses midnight local time midnight for building Date object. This is how Date in JavaScript works.

If you have issues with 8AM/9AM, then the issue is certainly elsewhere than React-Calendar.

One thing worth noting is that if the user is in another timezone, or doesn't have their clock set properly, or has other clock-related issue, it's gonna use _their_ midnight local time, not _yours_, because the browser has no way of knowing that you would want some other timezone to be used. You'll have to convert the values to adjust the clock yourself.

**Comment by nharchitecture** [comment]
Thanks for this info.

The issue only appears when using React calendar..  If we look at the calendar in the non-modern interface, the time is correct.  If we look at the calendar in Outlook, the time is correct.  But in React Calender, the time is wrong.  We are all in the same timezone.

Cheers

Alexis Spencer​

IT Manager
She/Her/Hers

[NH Architecture]<http://www.nharchitecture.net/>
t +61 3 9654 4955
|
d +61 3 9491 9090<tel:+61%203%209491%209090>
|
m +61 482 014 113



Level 7, Cannons House
​12‑20 Flinders Lane,
​Melbourne 3000

www.nharchitecture.net<http://www.nharchitecture.net/>
[Instagram]<http://instagram/nharchitecture>
[LinkedIn]<https://www.linkedin.com/company/nharchitecture>
[Facebook]<https://www.facebook.com/NHArchitecture1>



[cid:image005.png@01D70F4A.1240C470]
NH Architecture is proud to acknowledge the Traditional Custodians of the land on which our studio and projects are situated. We pay our respects to their Elders, past, present and emerging.
Please consider the environment before printing this email.
Disclaimer: This message contains privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message, you are hereby notified that you must not disseminate, copy, or take action in reliance on it. If you have received this email in error please notify NH Architecture immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the view of NH Architecture.

**Comment by nharchitecture** [comment]
As an example..

Here is the ACTUAL calendar entry directly from the SharePoint online list:
[cid:image001.jpg@01D70F67.0C263E40]

Here’s what React is displaying:
[cid:image002.jpg@01D70F67.0C263E40]


Alexis Spencer​

IT Manager
She/Her/Hers

[NH Architecture]<http://www.nharchitecture.net/>
t +61 3 9654 4955
|
d +61 3 9491 9090<tel:+61%203%209491%209090>
|
m +61 482 014 113



Level 7, Cannons House
​12‑20 Flinders Lane,
​Melbourne 3000

www.nharchitecture.net<http://www.nharchitecture.net/>
[Instagram]<http://instagram/nharchitecture>
[LinkedIn]<https://www.linkedin.com/company/nharchitecture>
[Facebook]<https://www.facebook.com/NHArchitecture1>



[cid:image007.png@01D70F67.0C263E40]
NH Architecture is proud to acknowledge the Traditional Custodians of the land on which our studio and projects are situated. We pay our respects to their Elders, past, present and emerging.
Please consider the environment before printing this email.
Disclaimer: This message contains privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message, you are hereby notified that you must not disseminate, copy, or take action in reliance on it. If you have received this email in error please notify NH Architecture immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the view of NH Architecture.

**Comment by wojtekmaj** [comment]
Your attachments are not getting displayed on GitHub. I won't be able to help you. Still, I'm pretty sure it's not React-Calendar's fault.

**Comment by nharchitecture** [comment]
Thank you for your email.

The issue is React calendar as the entries display correctly everywhere else except in react calendar, but if you are not interested in fixing your product, then we will not use it.  That’s a shame, as it had promise, but it does not work and you are not interested in fixing it.


Alexis Spencer​

IT Manager
She/Her/Hers

[NH Architecture]<http://www.nharchitecture.net/>
t +61 3 9654 4955
|
d +61 3 9491 9090<tel:+61%203%209491%209090>
|
m +61 482 014 113



Level 7, Cannons House
​12‑20 Flinders Lane,
​Melbourne 3000

www.nharchitecture.net<http://www.nharchitecture.net/>
[Instagram]<http://instagram/nharchitecture>
[LinkedIn]<https://www.linkedin.com/company/nharchitecture>
[Facebook]<https://www.facebook.com/NHArchitecture1>



[cid:image005.png@01D7100B.7C79F110]
NH Architecture is proud to acknowledge the Traditional Custodians of the land on which our studio and projects are situated. We pay our respects to their Elders, past, present and emerging.
Please consider the environment before printing this email.
Disclaimer: This message contains privileged and confidential information intended only for the use of the addressee named above. If you are not the intended recipient of this message, you are hereby notified that you must not disseminate, copy, or take action in reliance on it. If you have received this email in error please notify NH Architecture immediately. Any views expressed in this message are those of the individual sender, except where the sender specifically states them to be the view of NH Architecture.

**Comment by qzw881130** [comment]
I solved it.
```
import moment from "moment-timezone";

export const getNowDate = ()=>{
    const parsedDate = moment().tz('Atlantic/Reykjavik').format('YYYY-MM-DD hh:m:s');
    console.log('parsedDate=', parsedDate, 'local=', moment().format('YYYY-MM-DD hh:m:s'))
    return parsedDate.toString();
}
```
```
const [selDate, setSelDate] = useState(getNowDate());

<Calendar onChange={setSelDate} minDate={new Date()} tileDisabled={tileDisabled} tileClassName={tileClassName} maxDate={momentTz().add(365, 'days').toDate()} value={selDate} />
```

the console outputs these:
```
parsedDate= 2024-09-23 02:35:18 local= 2024-09-22 10:35:18
parsedDate= 2024-09-23 02:35:18 local= 2024-09-22 10:35:18
```

![date1](https://github.com/user-attachments/assets/9724b879-5826-4a47-bbcb-a94157f32a30)
