### ISSUE TITLE
Typescript does not include inputRef

### ISSUE THREAD

**Issue by BrianBenninger** [wojtekmaj/react-calendar#493]
At current if you install the latest and greatest and install the types, the types file does not include inputRef.

Recreate by following:
npm install react-calendar
npm install @types/react-calendar

**Comment by wojtekmaj** [comment]
That's external package and there's nothing I can do about it here

**Comment by wojtekmaj** [comment]
FYI, React-Calendar is now natively in TypeScript, as of #785, coming to npm very soon.
