### ISSUE TITLE
Allow to update calendar state from outside when in the middle or range selection

### ISSUE THREAD

**Issue by CezaryH** [wojtekmaj/react-calendar#494]
Use case:
1) I allow users to set predefined range (eg last 7 days, 30 days ...) set by different component
2) I allow users to select only one day from calendar. I fill end date with the same date but time set to 23:59:59
3) I have set allowPartialRange to true

Issue:
When user selects one day (calendar is in the middle of range selection) and then clicks on "select last 7 days" I'm not able to update range on calendar. It's because calendars local state has precedence over passed dates.
https://github.com/wojtekmaj/react-calendar/blob/fe83e095f0b744ddaf09bb909bf15d9e45054809/src/Calendar.jsx#L193

Can you make it possible to force state change from outside.
I think that check in get value function could check if action was invoke by clicking on day component or passed from parent component

**Comment by maciejregula** [comment]
I have the same issue. Is there any solution for it?

**Comment by maciejregula** [comment]
Ok, I found a solution. The hack I use is to reinitialize the whole component of react calendar by chaning a key prop. Please see below:

```js
const [calendarKey, setCalendarKey] = useState(1);
<Calendar key={calendarKeyRef.current} ... />
```
If you want to reset the state, just change the key:
```js
setCalendarKey((prevState) => prevState+1);
```

**Comment by DaddyWarbucks** [comment]
I came to this thread with the same issue. I was hoping for a better solution than busting the key, but that works. Preferably the component would recognize the value change and update the selection/range as needed.

**Comment by hoanggtg** [comment]
I have the same issue.
