### ISSUE TITLE
Passing date to value props of MonthView component crashes

### ISSUE THREAD

**Issue by lauterry** [wojtekmaj/react-calendar#496]
Hello

```jsx
<MonthView
	value={new Date(2021, 3, 15, 0, 0, 0)}
	activeStartDate={new Date(2021, 3, 1, 0, 0, 0)}
/>
```

I have the error : 

```Uncaught Error: getTileClasses(): Unable to get tile activity classes because one or more required arguments were not passed.```

I do not have the error when passing an array of date to value props

Is it a bug or did I missed something ?

Best regards

**Comment by wojtekmaj** [comment]
Try adding `valueType="day"` 🤔
