### ISSUE TITLE
how can I disable past dates and all sundays .

### ISSUE THREAD

**Issue by Mayank8085** [wojtekmaj/react-calendar#497]
I am having a problem in disabling all Sundays and past days simultaneously by using tileDisabled

**Comment by wojtekmaj** [comment]
> past dates 

minDate

> all sundays

tileDisabled

Or, if you're feeling adventurous, you can use tileDisabled only, by essentially writing something along the lines:

```js
function tileDisabled({activeStartDate, date, view }) {
  if (isPast(date) {
    return false;
  }

  if (isSunday(date) {
    return false;  
  }

  return true;
}
```
