### ISSUE TITLE
Issue with DST and onClickDay

### ISSUE THREAD

**Issue by VisakanMathy** [wojtekmaj/react-calendar#498]
Hello,

I am using a controlled and an uncontrolled setup for the calendar and seem to be getting contradictory values. 

Using the following setup on clicking 29/03/21, I get a date value of "Sun Mar 28 2021 00:00:00 GMT+0000 (Greenwich Mean Time)"

` <Calendar onClickDay={(date) => {console.log(date)} value={this.props.date}`/>

Then using the following uncontrolled setup, I get a date value of "Mon Mar 29 2021 00:00:00 GMT+0100 (British Summer Time)", which is what I would want for the above setup.

` <Calendar onClickDay={(date) => {console.log(date)} value={undefined}`/>

Is this a bug or am I using onClickDay incorrectly? (The first one also uses the tileDisabled props)

Many Thanks,

**Comment by wojtekmaj** [comment]
See #174, #492 and especially https://github.com/wojtekmaj/react-calendar/issues/492#issuecomment-787807224.

**Comment by VisakanMathy** [comment]
I'm still confused about this interaction because surely the browser and the Calendar would provide the same Date Object, regardless of time zone and DST. However, for both the mentioned methods I click 29/03/21 but two different dates are logged? 

I am aware that the date object is browser dependant and needs to be adjusted for time zone but the initial date returned by the calendar seems to be inconsistent.

**Comment by wojtekmaj** [comment]
That sounds quite odd. You think you could help me reproduce that on CodeSandbox?

Here's a starter: https://codesandbox.io/s/react-calendar-jcc1p

**Comment by VisakanMathy** [comment]
Thanks. I realised I should have mentioned that I've been using tileDisabled as well this is roughly the setup.

https://codesandbox.io/s/react-calendar-forked-8jozr?file=/src/index.js

**Comment by VisakanMathy** [comment]
Having rebuilt it in sandbox I've just realised it is being caused by not creating a new Date Object when disabling the tiles. Thanks for your time.
