### ISSUE TITLE
Support for different locals

### ISSUE THREAD

**Issue by spoldman** [wojtekmaj/react-calendar#5]
Thank you for all your hard work of bringing this back.

I noticed when updating that few features were missing. Most of them I was able to go around but there are issues regarding locals. As Intl.DateTimeFormat does not support Icelandic. 

I need the weekDayNames because current implementation does not work with Icelandic (is-IS). Intl.DateTimeFormat method that this library uses does not return correct names for days. The same is for months, the months names are wrong

![image](https://user-images.githubusercontent.com/10643226/32656748-1b1e1af6-c60b-11e7-880d-2b37b01955bf.png)

This should return 'Fös' instead of 'Fri'

![image](https://user-images.githubusercontent.com/10643226/32656999-f159d682-c60b-11e7-8481-1c6683578d35.png)

'M11' should be 'Nóv'

**Comment by wojtekmaj** [comment]
Hey @spoldman,
thanks for the report. Unfortunately, that is beyond my responsibilities. ECMAScript Internationalization API is implemented by the browsers. From the screenshot, I think you're using Chrome. I suggest you [reporting the issue to them](https://www.chromium.org/issue-tracking).
Be sure to share the link to your report. I'll gladly support it!

**Comment by spoldman** [comment]
Thanks for the response.

Thats true that it is not your responsibilities to fix how Intl.DateTimeFormat is implemented in the browsers. I was just thinking of if there is a better way as DateTimeFormat is not reliable enough for many locals. Does it makes sense to add a property to provide the component with methods to format months and day names. That way you could use moment or any other library that you use in your application.

I'm willing to do a PR if that is something you would be interested in.

**Comment by wojtekmaj** [comment]
Hmmm. That doesn't seem like a bad idea, actually. Custom formatters would be easy to implement. I could work on this over the weekend if I find some time.

...although I still urge you to file an issue for the sake of better web ;) By the way, Firefox formats is-IS dates quite nicely from what I can see!

![obraz](https://user-images.githubusercontent.com/5426427/32668116-fe414732-c63c-11e7-917f-2231ca77f93a.png)

So now you can shame Google by Mozilla's example :D

**Comment by spoldman** [comment]
I created the following issue https://bugs.chromium.org/p/chromium/issues/detail?id=783809# 
But custom dateTime formatters would be awesome as that would allow me to do 'M' instad of 'Mon' for weekday names.
