### ISSUE TITLE
Day view and Week view is missing in the calendar

### ISSUE THREAD

**Issue by developersatyajit** [wojtekmaj/react-calendar#500]
I am looking for day & week view in the calendar. Can you show me how to do that or is this feature available in this package?

**Comment by wojtekmaj** [comment]
No, neither is available.

Also what would you expect from day view? Setting hour/minute? Sounds like you need [React-DateTime-Picker](https://github.com/wojtekmaj/react-datetime-picker).

**Comment by developersatyajit** [comment]
No I need to set defaultView props to day only instead of setting month, year, decade. I know what React Datetimepicker does. My requirement is quite simple here. let me give you an example.
![day-view](https://user-images.githubusercontent.com/4978681/113007374-cbc77a80-9193-11eb-9990-896bebc6e944.png)

**Comment by developersatyajit** [comment]
Is it possible ? Or does your package support this feature?

**Comment by developersatyajit** [comment]
Leave it, I got it from Fullcalendar. Your package is not needed anymore. By the way thanks for your time.
