### ISSUE TITLE
Text content did not match - Server and Client. Using Nextjs

### ISSUE THREAD

**Issue by pr1m0x** [wojtekmaj/react-calendar#501]
Hey,

using the react-calendar with NextJs produces the following Error-Msg: 
<img width="1438" alt="Bildschirmfoto 2021-03-30 um 13 06 43" src="https://user-images.githubusercontent.com/44192336/112979883-74a4b400-9159-11eb-93f5-2ff9e2df5394.png">

Regards

**Comment by wojtekmaj** [comment]
Your server, unlike your browser, can't detect user's locale automatically so it falls back to en-US.

Provide consistent `locale` to React-Calendar to get rid of this.

**Comment by devagja** [comment]
@pr1m0x 
currently the solution in react 18 would be the following:

```
import dynamic from "next/dynamic";
const Calendar = dynamic(() => import("react-calendar"), { ssr: false });
```
