### ISSUE TITLE
MonthView locale 'ar-lb' showing in numbers instead of numerals

### ISSUE THREAD

**Issue by yschoueri** [wojtekmaj/react-calendar#508]
I am using react-calendar 3.3.1 with my own styling and when my locale is 'ar-lb', in the month view, the days are shown in numbers instead of arabic numerals whereas in the year view, it is correctly shown in numerals. I couldn't find a function formatDays similar to all the other format prop methods provided.

Month view vs Year view

![image](https://user-images.githubusercontent.com/2871713/114992752-64037600-9e9b-11eb-9b7a-0c1678e80757.png)

**Comment by wojtekmaj** [comment]
Oh that's an interesting one!

Pardon my ignorance, does that look like correct to you?

<img width="358" alt="obraz" src="https://user-images.githubusercontent.com/5426427/114995042-b5ad0000-9e9d-11eb-8098-db14a6657845.png">

**Comment by yschoueri** [comment]
Yes that's more like it :)

**Comment by wojtekmaj** [comment]
Released with `v3.4.0`. You now have locale-aware day number formatting as well as `formatDay` custom prop functin available.

Maintaining this project has been so educating!

**Comment by yschoueri** [comment]
Thank you so much for your quick response!

**Comment by wojtekmaj** [comment]
Thanks! Consider [sponsoring the project](https://github.com/wojtekmaj/react-calendar?sponsor=1), or convincing your employer to do so!

**Comment by yschoueri** [comment]
Quick question, when would the v3.4.0 release be available on npm?

**Comment by wojtekmaj** [comment]
It should already be, maybe it was just a hiccup?

**Comment by wojtekmaj** [comment]
@yschoueri Number formatting is done based on Intl implementation in your browser. Looks like all browser vendors form some reason decided ar-AE should result in numbers returned. There's nothing I can do on my side.

**Comment by manoj7594** [comment]
@wojtekmaj Thank you :)
