### ISSUE TITLE
It's not clear which dates are interpreted as UTC or local time

### ISSUE THREAD

**Issue by racoleman** [wojtekmaj/react-calendar#511]
When a UTC date object is passed to react-calendar (e.g. `Date('2021-04-20')` or `Date(1618876800000)`), it assumes the date is local time. This results in incorrect date values, as react-calendar calls `Date` methods internally that are only intended for local time (`setHours()` vs `setUTCHours()`).

I understand there have been a number of prior issues opened around timezone support (#174, #492, etc.), but I believe that this date mutation may be the actual cause of many of these issues. It is not well-known that the result of the `Date` constructor may be in local or UTC depending the parameters passed. At a minimum, updating the documentation to reflect that the Date object passed to `value` must be in local time may help alleviate some confusion. Ideally, detecting (or providing a flag) for UTC dates would ensure that users get the output they expect, even if they have to perform their own timezone conversion in post.

**Comment by wojtekmaj** [comment]
> At a minimum, updating the documentation to reflect that the Date object passed to value must be in local time may help alleviate some confusion.

Absolutely agree.

**Comment by aamorozov** [comment]
What would be the correct approach to deal with the location-specific timezone in the Calendar component? 
I have a use case where the locations I display the Calendar for can vary, and so will their time zones. 
I want to let users across the world see the exact same date *in the location-specific timezone*. I thought to use UTC for that, but it does seem like it's being converted to local time regardless of me manually formatting the date to UTC.

**Comment by wojtekmaj** [comment]
@aamorozov Dates in JavaScript in general are "local" and "timezone specific". There's no concept of "UTC" date, or dates in any other timezones than the one you're in right now.

Consequently, React-Calendar, you'll always select century/decade/year/month/day "start time", which is local midnight. 

There are a number of approaches you can take to get "non-local" midnight, like midnight in UTC, or midnight in other timezone.

You can create a new Date object that will have UTC midnight using `getTimezoneOffset()`:

```js
function handleDateChange(dateWithLocalMidnight) {
  const dateWithUtcMidnight = new Date(dateWithLocalMidnight.getTime() - dateWithLocalMidnight.getTimezoneOffset() * 60 * 1000);
}
```

This way, you will get a date that's 2 AM local time if your local timezone is UTC+2, which is 12 AM in UTC. So when using methods that apply to UTC, you will get an expected result, e.g. `"2020-05-01T00:00:00.000Z"`.

Alternative way would be to store the Date as is, sparing you all the conversion e.g. when keeping date in local state, and built a function that stringifies the date to ISO-like string based on local date:

```js
function toISOLikeString(d) {
  return `${
    d.getFullYear()
  }-${
    `${d.getMonth() + 1}`.padStart(2, '0')
  }-${
    `${d.getDate()}`.padStart(2, '0')
  }T${
    `${d.getHours()}`.padStart(2, '0')
  }:${
    `${d.getMinutes()}`.padStart(2, '0')
  }:${
    `${d.getSeconds()}`.padStart(2, '0')
  }Z`;
}
```

Lastly, there are 3rd party utilities like [date-fns-tz](https://www.npmjs.com/package/date-fns-tz) that let you do complex timezone operations if you need more than simply converting to UTC or back.

**Comment by wojtekmaj** [comment]
@racoleman `Date('2021-04-20')` is not the correct way to initialize JavaScript date and will return a string with current time (kinda WTF, I know). `new Date('2021-04-20')` will, however, be interpreted as Apr 20 2021 UTC midnight just fine. With `Date(1618876800000)` it's exact same story.

**Comment by racoleman** [comment]
> @aamorozov **Dates in JavaScript in general are "local"** and "timezone specific". There's no concept of "UTC" date, or dates in any other timezones than the one you're in right now.

Are you referring to the prototype methods of `Date`? Most of them operate in the local timezone, but core value of the object itself is still UTC.

> @racoleman `Date('2021-04-20')` is not the correct way to initialize JavaScript date and will return a string with current time (kinda WTF, I know). `new Date('2021-04-20')` will, however, be interpreted as Apr 20 2021 UTC midnight just fine. With `Date(1618876800000)` it's exact same story.

Yep, accidentally left that out of my opening post 😅

**Comment by tapanpatra87** [comment]
How to add a new custom button below of the calendar ?
