### ISSUE TITLE
How to change styles of weekday

### ISSUE THREAD

**Issue by crystalball808** [wojtekmaj/react-calendar#515]
Need to remove these underlines and fix align. How can I fix this? I use tailwindcss so solution without css files is preferred.
![image](https://user-images.githubusercontent.com/34882650/116398183-2eae3f00-a830-11eb-9c19-7fa52378cde9.png)

**Comment by tpriyanshu90** [comment]
react_calendar abbr[data-original-title], .react_calendar abbr[title] {
    cursor: default;
    text-decoration: none;
}

**Comment by tpriyanshu90** [comment]
this worked for me
