### ISSUE TITLE
[Feature Request] - Take the user to minDate or maxDate by pressing next2button/prev2button

### ISSUE THREAD

**Issue by farrukhrashid1997** [wojtekmaj/react-calendar#516]
When the user clicks on the prev2button, he goes to the previous year. But if for example: he clicks on the prev2button on 3rd May, 2021, minimum date is 3rd June 2020, then the button wont work and will get disabled. How about instead of disabling it. we take the user to the min date or max date? 
I have written the code for it and tested it as well. Let me know if I can contribute. @wojtekmaj, please advise.

**Comment by Chikouni** [comment]
@wojtekmaj +1 for this features !!

@farrukhrashid1997  Do you have an hacky way to fix this until your PR ?

**Comment by farrukhrashid1997** [comment]
Following up so that it doesnt go stale.
