### ISSUE TITLE
How can I store dates and their tile content in state?

### ISSUE THREAD

**Issue by Trym2** [wojtekmaj/react-calendar#519]
I want to store the next 14 days in a state, but I can't figure out how to access the tile content and values of the dates, besides with inputRef

**Comment by tpriyanshu90** [comment]
use a useffect on selectedDate state variable, then set your value inside useEffect

**Comment by wojtekmaj** [comment]
@Trym2 I don't understand what you're trying to achieve here, sorry, I won't be able to help you without further details.
