### ISSUE TITLE
How can i start the calendar from a specific date and hide all previous inactive dates?

### ISSUE THREAD

**Issue by vforvaios2** [wojtekmaj/react-calendar#521]
For example. If i want the calendar to start from 1-1-1980 and never give the ability to the user to go further back, how can i do it?

**Comment by tpriyanshu90** [comment]
provide custom class to the every tile, make two states 
1. (tempValue, setTempValue)
2. (value, setValue)
 and pass setTempValue to onChange of Calendar component, let the calendar component change tempValue, and put a useEffect for tempValue, if the value change verify if you want to perform some action on this date (like providing any class)

**Comment by tpriyanshu90** [comment]
in Calendar value prop pass the state `value` , this way you can modify the date according to your choice or any condition

**Comment by wojtekmaj** [comment]
>How can i start the calendar from a specific date 

Set defaultActiveStartDate or activeStartDate (depending on whether you're using React-Calendar as controlled or uncontrolled component) to 1980-01-01.

>and hide all previous inactive dates?

Set minDate to 1980-01-01 and make sure `showNeighboringMonth` is disabled so that 1979 won't "leak" to 1980.
