### ISSUE TITLE
I can't see anything by using 'tileContent'

### ISSUE THREAD

**Issue by mjseok** [wojtekmaj/react-calendar#522]
## Code
This is my code.
```js
const Calendar=()=>{
 const show=(date,view)=>{
   const day1=new Date();
    if(date.getTime() ===day1.getTime()){
            return "today";
    }
   return "nothing";
  }
  return(
   <ReactCalendar
        onChange={onChange}
        value={value}
        calendarType={"US"}
        onClickDay={showJournal}
        tileContent={show}
      />
);
```
## Problems
I want to make Calendar like this.
But, I can't see anything. How can I fix it....? 
![image](https://user-images.githubusercontent.com/57527380/120280482-afaa9b80-c2f2-11eb-91a4-6fa3caac8b0a.png)

**Comment by wojtekmaj** [comment]
`date.getTime()` returns the exact millisecond of a given `Date`. Write your own `isSameDay` function that compares years, months and days of the month only, or use `isSameDay` e.g. [from `date-fns`](https://date-fns.org/v2.22.1/docs/isSameDay).
