### ISSUE TITLE
How to get Week number when pressing on `onClickDay` ? 

### ISSUE THREAD

**Issue by MariuzM** [wojtekmaj/react-calendar#526]
Does Reac calendar provide something that when pressing on `onClickDay` i can get that day's Week number?

**Comment by wojtekmaj** [comment]
It does not, but you can use internal utils like so:

```js
import { getWeekNumber } from 'react-calendar/dist/esm/shared/dates';
import { CALENDAR_TYPES } from 'react-calendar/dist/esm/shared/const';

getWeekNumber(date, CALENDAR_TYPES.US);
```

to get the week number.

Of course, if you use other calendar type, then you will need to pass other const from `CALENDAR_TYPES`: `ARABIC`, `HEBREW`, or `ISO_8601`.
