### ISSUE TITLE
Which handler to go to previous / next month view 

### ISSUE THREAD

**Issue by Kay2dan** [wojtekmaj/react-calendar#532]
![image](https://user-images.githubusercontent.com/6276091/124378197-9ddd5f00-dcc9-11eb-96fa-1807160957c3.png)

I am struggling to find the onclick handler for the next/prev buttons on either side of the navigation button. Which onclick func is for controlling them? In the above image, its the pink background buttons. 

Thank you

**Comment by jnrdrgz** [comment]
onActiveStartDateChange is called when you navigate from one view to another using previous/next button

**Comment by Kay2dan** [comment]
Is my understanding that the above mentioned navigation buttons switch the months automatically, without my writing a function for `onActiveStartDateChange` to go back/forward to the next month?

Reason for asking is that in my app, the buttons are not working.

**Comment by mbelic** [comment]
Sorry for hijack, I am also trying to achieve something similar but with an outside component. 
I would like to introduce "set to today" button which would set calendar "view" to month of today's date. 

Is there a handler that can control just the view? Possibly achieve this without selecting a date, but just change month - like next  / previous month was clicked.
