### ISSUE TITLE
First day of week issue on different clients

### ISSUE THREAD

**Issue by manusabarros** [wojtekmaj/react-calendar#541]
Hi there!

My teammates and I are having a problem with the library. We are in different countries but we are using `locale="en-GB"` and `calendarType="ISO 8601"` as props, forcing the calendar to always be the same, but some of them get a calendar with the first day of the week as Sunday, while others have Monday as the first day. In fact, people from the same country get different results. I asked them to pass me the result of `navigator.language` and they get `en-GB` as locale in their browsers.

Maybe it is irrelevant, but the application is made in Next.js and deployed on Vercel's servers. Anyway the code runs only on the client since we don't show the calendar until the user is authenticated, so the component is sure that it only runs on the client.

Anyone have an idea what may be happening?

Thanks!

**Comment by wojtekmaj** [comment]
I think SSR behavior could be somehow relevant here, since prop you've mentioned and navigator.language is essentially everything Calendar bases its calculations on.
