### ISSUE TITLE
if calendar starts on a Sunday (calendarType = US), week number is off by one

### ISSUE THREAD

**Issue by mikeyyyzhao** [wojtekmaj/react-calendar#543]
if calendar starts on a Sunday (calendarType = US), week number is off by one

**Comment by wojtekmaj** [comment]
Unlikely. See https://github.com/wojtekmaj/react-calendar/issues/484#issuecomment-796538715

**Comment by mikeyyyzhao** [comment]
[sandbox example](https://codesandbox.io/s/react-calendar-wrong-week-numbers-forked-hmcgb?file=/src/App.js)

![Screen Shot 2021-09-07 at 12 17 38 PM](https://user-images.githubusercontent.com/4956032/132378175-357719c8-ef11-47f2-84a7-21c277f77b24.png)
![Screen Shot 2021-09-07 at 12 17 46 PM](https://user-images.githubusercontent.com/4956032/132378186-b7e408ca-9839-450e-99b6-079982963815.png)

Top is react-calendar and bottom is Google calendar both week starting on Sunday. week of Sept 5-11 should be week 36.

**Comment by wojtekmaj** [comment]
@mikeyyyzhao 

 * In ISO 8601, Arabic and Hebrew week 1 is the one with January 4.
 * In US calendar week 1 is the one with January 1.

Google Calendar marks week January 1st, 2021 as 2020 week 53. This is not as per "spec" of US calendar.

**Comment by mikeyyyzhao** [comment]
is there any way to keep using ISO 8601 but start week on Sunday? Start day of the week is more of a personal preference, I don't think it should be coupled so tightly together with calendarType
