### ISSUE TITLE
Not loading galician locale

### ISSUE THREAD

**Issue by paroar** [wojtekmaj/react-calendar#545]
Hi, I'm using react-calendar to render with galician locale but it doesn't work.

What did I expect?
I expected to load the galician locale

What have I tried?
I tried using 'gl', 'gl-ES', 'gl-es', 'ES-gl', 'es-gl', 'glg' codes but none of them works

Thank you for your time.

**Comment by wojtekmaj** [comment]
In my browser, `'gl', 'gl-GL', 'gl-ES', 'es-GL'` are supported as reported by `Intl.DateTimeFormat.supportedLocalesOf(['gl', 'gl-GL', 'gl-ES', 'gl-es', 'ES-gl', 'es-gl', 'glg'])`.

Not sure which is the one you're trying to render but have a look:

![Zrzut ekranu 2021-09-14 o 23 28 24](https://user-images.githubusercontent.com/5426427/133336427-cdeba908-0e52-4d87-ac0d-01950a16f32a.png)

![image](https://user-images.githubusercontent.com/5426427/133336443-94c4afa7-1b16-46a6-b570-34da8f2b3469.png)

**Comment by paroar** [comment]
Tried with another browser(Firefox) and works fine.

```sh
Intl.DateTimeFormat.supportedLocalesOf(['gl', 'gl-GL', 'gl-ES', 'gl-es', 'ES-gl', 'es-gl', 'glg'])
```
On Chrome it only returns 'es-GL' which doesn't render the language but running it on Firefox returns almost everything. Do I need to set up the languages on the browser or is it a problem beyond my scope?

OS: macOS Catalina 10.15.7
Chrome: Version 93.0.4577.82 (Official Build) (x86_64)


Thanks a lot!

**Comment by wojtekmaj** [comment]
Depends how much in control you want to be. You could 
* use `Intl.DateTimeFormat.supportedLocalesOf` to determine the locale to be used dynamically,
* run it on all browsers you'd like to support and find one locale that you can use on them all
* or leave it entirely and use default user's browser locale.
