### ISSUE TITLE
Manual input does not trigger onChange event

### ISSUE THREAD

**Issue by GerryLau** [wojtekmaj/react-calendar#549]
I expect onChange event will be triggered if user manually changed the input date but it is not.

**Comment by shanestreator** [comment]
Yes, I concur. @GerryLau were you able to find a prop or workaround?

**Comment by GerryLau** [comment]
Not really.. it is a great component and I find it easier to customize than react-datepicker, but I feel like Wojciech is too busy and looks like there is no other active developer in this project..

**Comment by shanestreator** [comment]
@GerryLau, after troubleshooting a bit more I found it actually does fire the onChange event. It seemingly returns an event object though if a max/min or an invalid date is hit.

This initial validation checking if date is an array in the onChange fixed my problem.
```
const onDateChange = (date) => {
        if (!Array.isArray(date)) return

        const start = date[0]
        const end = date[1]

        setDateValue([start, end])
    }
```

**Comment by GerryLau** [comment]
Thanks a lot, will have a try
