### ISSUE TITLE
Option to set calendar month index start at 1

### ISSUE THREAD

**Issue by davvyy00** [wojtekmaj/react-calendar#55]
Is there a property to change to months index to start at 1 instead of zero, ie march = 3 but the output on the calendar is april, I can manually do this but its very hacky, question, enhancement

**Comment by davvyy00** [comment]
@wojtekmaj My use case is that I use 3 for march saving to the server and getting from the server
Javascript datepicker intrepret 3 as index 3 ie 4 and displays april, I can hack the response from server but would prefer not too

**Comment by wojtekmaj** [comment]
React Date Picker doesn't "interpret" anything. It reads `Date()`. `Date()` is a native JS object. You can initialize it with a timestamp or UTC string if you'd like, but if you opt for `year, monthIndex, day` arguments then you have to deal with it.

More on that here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
