### ISSUE TITLE
tileContent not reading state

### ISSUE THREAD

**Issue by anshulmgupta** [wojtekmaj/react-calendar#550]
Hi, I am new to react and working with react calendar to show some data on tileContent for a specific date for which I have available data. I am calling the REST API to get the per date data and storing that in state
```
state = {
    date: new Date(),
    calStats: {}
};
```

```
async componentDidMount() {
    await this.getCalendarStats();
}
```
But when I am reading the state in tileContent hook I am seeing the state as empty
```
tileContent = ({ date }) => {
    console.log(this.state.calStats);
};
```
Use of the tileContent in the calendar component.
```
<Calendar
                    calendarType="US"
                    className="react-calendar"
                    onChange={this.onChange}
                    value={this.state.date}
                    tileContent={this.tileContent}
                  />
```
Also, seems like the state is getting updated later after the tileContent is called. I wanted to check and see if there is a way to populate the state using REST API and use it in tileContent? Thanks!

**Comment by wojtekmaj** [comment]
> seems like the state is getting updated later after the tileContent is called

This is likely the key. There's nothing that could cause `Calendar` to update, so `Calendar`... does not update. With React Hooks, my suggestion would be to write:

```js
const tileContent = useCallback(() => {
    console.log(calStats);
}, [calStats]);
```

so that you would get a new `tileContent` function every time `calStats` are updated. With legacy React Components, try moving `tileContent` to render function maybe?

If that won't help, you can fork this sandbox on CodeSandbox to reproduce your issue so that we could work on it.

https://codesandbox.io/s/react-calendar-jcc1p

**Comment by anshulmgupta** [comment]
@wojtekmaj Thank you so much for the response, moving it to render function worked. I tried using the useCallback hook but that gave the UI error Invalid hook call.
```
render() {
    const tileContent = ({ date, view }) => {
      if (view === "month") {
        const year = date.getUTCFullYear();
        const month = date.getUTCMonth() + 1;
        const day = date.getUTCDate();
        const key = year + "/" + month + "/" + day;
        if (key in this.state.calStats) {
          return (<p>({this.state.calStats[key]})</p>);
        }
      }
    };
  ...
}
```
Even moving it to render function was interesting as the data is loaded I believe until the entire component is fully rendered. I could see initially the state was empty but as the components may have completely rendered tileContent was able to read the state.

**Comment by wojtekmaj** [comment]
Yeah you can't use hooks in legacy components.
