### ISSUE TITLE
Hide input and render calendar only on icon click.

### ISSUE THREAD

**Issue by kurasaiteja** [wojtekmaj/react-calendar#553]
Hi, 
I want to implement a functionality where only the calendar icon is visible and I can open calendar on icon click.
Something like this.
Please help!
![Screenshot 2021-10-04 at 7 50 22 PM](https://user-images.githubusercontent.com/39938013/135868178-6bb4284f-b974-42ae-8a7a-a96cfb7bf0af.png)

**Comment by wojtekmaj** [comment]
@kurasaiteja This is unrelated to react-pdf itself. 

Seems like you could use just a simple flag toggle to show/hide React-Calendar.
