### ISSUE TITLE
Customizable number of years per page

### ISSUE THREAD

**Issue by wtomi** [wojtekmaj/react-calendar#554]
By default, there is only 10 years visible in the yearly view and there are two tiles left unoccupied. Is there a way to show 12 years so that all the tiles are filled? I think the empty space impacts negatively the user experience because users may think there are no more dates available due to empty space after last visible year. They may not try to go to the next page.
I went through all the properties and I can't find an option for customizing it.
 
<img width="384" alt="Zrzut ekranu 2021-10-10 o 16 13 54" src="https://user-images.githubusercontent.com/10536207/136699479-f2e32764-835a-4659-a787-c76d866dff2f.png">

**Comment by alisaliso** [comment]
Hi! `react-calendar` has different views like 'month', 'year', 'decade' and 'century', and the 'decade' view displays 10 years at once.

One of the things you can do to improve the view is to add styles to the last year tile and stretch it to fill the empty space.

The other thing is to add a new view to the `react-calendar` like `view="dozen"` or even custom view with number of years to display `view="12"`/`view={12}`, I can implement it, if it's something that can be implemented in `react-calendar`.
