### ISSUE TITLE
Enhancement - maxSelectRange

### ISSUE THREAD

**Issue by shanestreator** [wojtekmaj/react-calendar#556]
maxSelectRange={number}

The maxSelectRange prop would limit a user to select a maximum 'number' of days from start click.

```
Example:

maxSelectRange = 3
minDate = 9/11/2021
maxDate = 10/11/2021

event - start date clicked (start = 10/5/2021)

min hover date (10/2/2021) // start date clicked - maxSelectRange
max hover date (10/8/2021) // start date clicked + maxSelectRange
```

**Comment by Mohammad-Khalid** [comment]
@shanestreator Did you get any solution for this? I'm looking for a maximum number of days limit that one can select
