### ISSUE TITLE
tileDisabled function on multiple calendars

### ISSUE THREAD

**Issue by SamiMohr** [wojtekmaj/react-calendar#557]
I am trying to make sure of the tileDisabled function when using multiple calendars.

The idea is to render multiple calendars within a slide (npm react slick) and making sure every calendar has individual disabled dates.

Using tileDisabled works fine using one calendar as described in issue #49 and #79. But I cannot make use of it when rendering multiple calendars.

I am fetching data like this:

 `{ 
  "data":[
		{						
		"disabledDates":["2021-10-29"]
                },
		{		
		"disabledDates":["2021-10-30","2021-10-31"],
		}
	],
}`

Rendering the calendar looks like this: (sorry for the formatting, I will add a screenshot,too)

`<Slider {...settings}>
	{calendarDataRep ?
		(calendarDataRep.data.map((rep,index) => 
		<Calendar
			value={new Date()}
			maxDate={new Date(2022,4,20)}
			minDate={new Date()}
			minDetail={"year"}
			onClickDay={selectedDay}
			tileDisabled= {({date, view }) => { 
			 var dateArray = rep.disabledDates
			 var unavailableDates = dateArray.map((date) =>  new Date(date))
			 setDisabledDates(unavailableDates)
			 unavailableDates.some(disabledDate => 
			  Date.UTC(date.getFullYear()) === Date.UTC(disabledDate.getFullYear())  &&
			  Date.UTC(date.getMonth()) === Date.UTC(disabledDate.getMonth()) &&
			  Date.UTC(date.getDate()) === Date.UTC(disabledDate.getDate()) 
			 )
			}
		/>						
![react calendar issue 1](https://user-images.githubusercontent.com/67004602/138083352-963c7690-381a-4b27-93e9-6cbf746454ca.PNG)
![react calendar issue 2](https://user-images.githubusercontent.com/67004602/138083353-7813ed24-3046-4e48-a13c-96f772cf8202.PNG)

</Slider>`

Interestingly, `unavailableDates.some()` does return `true`, however it does it for all dates & the tiles aren't being disabled. Am I missing something?

**Comment by wojtekmaj** [comment]
@SamiMohr Your tileDisabled function has to return `true` for tiles that should be disabled. Currently, it does not return anything for any tile.
