### ISSUE TITLE
Question: How to change First Day of Week?

### ISSUE THREAD

**Issue by SherylHohman** [wojtekmaj/react-calendar#562]
I am in the US. typically our calendars show Sunday as first day of week. But I find that having either Mon, or Sat, as the first day of the week to be more useful in a calendar.  
Indeed, I always set my calendars this way.  
Is there a way to do this in this within react-calendar?  
My local would remain USA. Though if I could change it inside the app or this component only, without affecting anything else, I would be open to hacking it via locale. In that case, which locale ought I choose, and how to set it locally only?

**Comment by wojtekmaj** [comment]
Duplicate of #534
