### ISSUE TITLE
Selecting multiple unique dates

### ISSUE THREAD

**Issue by creativiii** [wojtekmaj/react-calendar#566]
React calendar is **by far** the best calendar component for React, but it only supports a single date or a range between two.

Would it be out of scope to implement selecting multiple dates, without including the range between them? 

For example:
- 2021-01-01
- 2021-03-01
- 2021-05-01

Would this be seen as useful? Would you accept PRs for it?

**Comment by davidalvarezr** [comment]
It would be useful. I want to create an app that has a calendar that shows the availability of a place (such as AirBNB). Would be great for that

**Comment by davidalvarezr** [comment]
@creativiii It looks like the final behaviour you want can be obtained using the prop `tileContent` or `tileClassName`: https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-add-content-to-tiles
