### ISSUE TITLE
How can I listen the event when User click the Prev Button or Next Button?

### ISSUE THREAD

**Issue by wine-fall** [wojtekmaj/react-calendar#570]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

when I click the Prev Button or Next Button, there is not any function can control it. eg: When I click the Prev Button, I want a Toast. However, there is no any Function can I write the code.

**Comment by wojtekmaj** [comment]
This is not a support forum, as [clearly stated here](https://github.com/wojtekmaj/react-calendar/issues/new/choose).

**Comment by wine-fall** [comment]
> when I click the Prev Button or Next Button, there is not any function can control it. eg: When I click the Prev Button, I want a Toast. However, there is no any Function can I write the code.
thanks for response! I post in here, please check https://stackoverflow.com/questions/70105092/how-can-i-disabled-the-view-change-of-react-calendar

**Comment by wine-fall** [comment]
Hi wojtekmaj:
thanks for response! I post in here, please check https://stackoverflow.com/questions/70105092/how-can-i-disabled-the-view-change-of-react-calendar
