### ISSUE TITLE
Custom tile components

### ISSUE THREAD

**Issue by codemonkey800** [wojtekmaj/react-calendar#572]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Thank you for this awesome library! It helped me finish my PR within a week 😉 

The only wonky thing I ran into was that the tiles are button elements. For my [calendar implementation](https://github.com/napari/napari.github.io/pull/302), I wanted to focus only on calendar events and not the days:

https://user-images.githubusercontent.com/2176050/146444687-98cbe1b1-52aa-469b-b731-5d17dba5ae75.mp4

I was eventually able to achieve this using DOM APIs:

```ts
function CalendarTile({ date }: { date: Date }) {
  const tileRef = useRef<HTMLDivElement>(null);

  // Effect to disable tabbing on the tile buttons. Since we can't customize the
  // button component used for the tiles, we need to modify the DOM attribute
  // directly.
  useEffect(() => {
    tileRef.current?.parentElement?.setAttribute('tabindex', '-1');
  }, []);
  
  return <div ref={tileRef>...</div>;
}

function Example() {
  return <Calendar view="month" tileContent={CalendarTile} />;
}
```

However, I don't find it very ideal. Instead, it might be better to allowing developers to pass a custom Tile component. I believe this would solve a class of issues that already exist:

- #354
- #247
- #143 
  - (not sure if this one is still an issue lol)

### Proposed solution

Add a new `TileComponent` prop to the `Calendar` component, and use that for rendering Tiles in every calendar view:

```ts
interface CalendarProps {
   TileComponent?: ComponentType<{ date: Date, ... }>;
   ...
}
```

https://github.com/wojtekmaj/react-calendar/blob/983412ea4c60fcb02f3e806e318b534acb2c1e2e/src/Calendar.jsx#L456-L562

### Alternatives

Not sure of any alternatives in the meantime aside from modifying the DOM directly in a `useEffect()`.

**Comment by wojtekmaj** [comment]
There's way too much going on in the Tile component to allow developers to override it. Best we could do is add something like tileProps to complement tileClassName, tileDisabled, and tileContent.
