### ISSUE TITLE
(Typescript) Property 'action' does not exist on type 'ViewCallbackProperties'.

### ISSUE THREAD

**Issue by adammo94** [wojtekmaj/react-calendar#575]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Just like in title. When I put Calendar with onViewChange prop that has destructured action it shows an error on action, that it doesn't exist. 

### Steps to reproduce

```<Calendar onViewChange={({action}) => console.log(action} />```

### Expected behavior

It shouldnt pop an error for action property.

### Actual behavior

It does pop an error for action property that is in documentation.

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Typings are externally provided - please raise/fix in @DefinitelyTyped repo.

**Comment by wojtekmaj** [comment]
FYI, React-Calendar is now natively in TypeScript, as of #785, coming to npm very soon.
