### ISSUE TITLE
Regression for display of the calendar on the default demo page

### ISSUE THREAD

**Issue by gissehel** [wojtekmaj/react-calendar#588]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Hello,

When I quickly need a calendar, I usually go to https://projects.wojtekmaj.pl/react-calendar/ to use the one on the page. (I've never used the component itself mainly because I never need a calendar, but it's in my "component to use" list if I ever need a calendar on a react app).

# Problem

I noted a regression recently:

![image](https://user-images.githubusercontent.com/199364/152676219-30aa13f5-4522-4f54-82b6-ff3864ad4db9.png)

The right navigation arrows are not in the top right corner anymore.

Doesn't look like something intentional. Also, I suppose the component was used correctly because it's the demo site for the component (if not, it's a regression in the demo at least, if not in the component).

# Analyse

![image](https://user-images.githubusercontent.com/199364/152676313-b550eb54-000e-4292-a65a-00c19412e8f9.png)

I can see flex-grow on the element classed with `react-calendar__navigation__label`. So I suppose the parent element miss a `display: flex`.

In deed. By adding `display: flex` on the element classed with `react-calendar__navigation` it does fix the component.

![image](https://user-images.githubusercontent.com/199364/152676466-26880c66-0b74-474a-8d48-f5af1ee6404f.png)

Note: I haven't search the source of the problem in the source.

### Steps to reproduce

* Go to https://projects.wojtekmaj.pl/react-calendar/

### Expected behavior

* The right arrows are in the corner
* The right arrows position doesn't change when the name of the month change

### Actual behavior

* The right arrows are just after the month
* The right arrows position change when the name of the month change

### Environment

- **Browser (if applicable)**: Chrome 97.0.4692.99 (64 bits) (cohort: Stable) running on Windows 10 Version 21H1 (Build 19043.1466)
- **JavaScript** : V8 9.7.106.19
- **React-Calendar version**: The one currently on the demo page
- **React version**: The one currently used on the demo page

**Comment by gissehel** [comment]
I've tried to look for the source of the problem:

- I found one commit : [35c1a68](https://github.com/wojtekmaj/react-calendar/commit/35c1a68485d7a420ca7f18de3e1b99d9e5860507#diff-819aac4b9d8e22ec050a31bf8cc052b53dc459c185cc3f80e3bb4c16ddb0640d) that seems "related" to this problem, but I still don't see why it would cause a problem (the refactoring is perfectly fine).
- It look like the component comes from a version *after* the commit, while the css comes from a css *before* the commit.

![image](https://user-images.githubusercontent.com/199364/152678022-5d4adf86-7bd8-428b-948f-a15ce0d7b5ef.png)

The name of the css file (*`src.9340530f.js`*) doesn't look like a filename that have cache problems (I suppose the `9340530f` part is generated from the content of the file, and then the file name is inserted inside the application source, so if the css wasn't deployed - for  any reason, and an old css was still present, you wouldn't see the old css, but just no css, still here it seems the CSS is an old one).

Current CSS:

![image](https://user-images.githubusercontent.com/199364/152678197-a28734d2-6d1f-462c-80fb-00fdfc90b11d.png)

**Comment by wojtekmaj** [comment]
Damn that's quite an analysis! Thanks!
Indeed, demo page used completely custom styling NOT built on top of what React-Calendar is being shipped with, and because of that, a non-breaking update has indeed broke the styling there. Fixed!

**Comment by k-funk** [comment]
This appears to still be broken for me. Just upgraded from 3.4 to 3.9.

## 3.4
Has inline `display: flex` on the `.react-calendar__navigation` div
<img width="287" alt="Screen Shot 2022-09-23 at 15 14 44" src="https://user-images.githubusercontent.com/1933021/191968440-5f37ec4c-67af-410b-abd8-00774770cb35.png">


## 3.9
No inline style on the `.react-calendar__navigation` div
<img width="303" alt="Screen Shot 2022-09-22 at 4 42 57 PM" src="https://user-images.githubusercontent.com/1933021/191967896-d7d5a02c-717e-4fb1-bbd8-7dd36fe2a2dc.png">
