### ISSUE TITLE
Feature Request - Add prop to customize current view title text

### ISSUE THREAD

**Issue by wdfinch** [wojtekmaj/react-calendar#599]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I would like to be able to customize the title text. By title text, I'm referring to the text that appears in the top center of the component. In this case "December 2021."

![Screenshot from 2021-12-09 12-01-09](https://user-images.githubusercontent.com/36898266/145467475-98fa2ea0-9c7c-42de-9cfa-acac00187a53.png)

### Proposed solution

I think the best way to do this would be to pass in a function as a prop that returns a string. The function would receive context data as args. So for example, things like the selected month, year, etc. so we could use to create our string.

### Alternatives

Haven't found any yet.

**Comment by shadesOfcodes** [comment]
whats the update on these

**Comment by wojtekmaj** [comment]
There's `navigationLabel` prop you can use. 

Example: https://codesandbox.io/s/react-calendar-navigation-label-46eu1o
