### ISSUE TITLE
March and October get messed up in Safari

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#6]
@jtwhittington reported in wojtekmaj/react-date-picker#14:

> <img width="397" alt="2007 ok" src="https://user-images.githubusercontent.com/1642289/32555227-320da242-c46a-11e7-9e13-9d6645ecddcc.png">
> <img width="433" alt="2006 broken" src="https://user-images.githubusercontent.com/1642289/32555228-321b9dd4-c46a-11e7-9517-f5f9f7ad05c8.png">
> 
> Happens only on Safari so far that I've seen. March duplicates itself and replaces April once you go back some years - October does the same to November. Looking into it myself, though if you have any ideas I'd be happy to hear them. Will make a PR if I figure it out.

**Comment by wojtekmaj** [comment]
The reason for this is very simple. To format date, I take the beginning of each month and use Intl.DateTimeFormat to get the name of the month in a given language. However, historical timezones are messed up on WebKit for some years. On Chrome, it happens for 1995 in my case.
I have filed a bug on that in Chrome already.
A workaround would be to use something like the middle of the month for taking month name and I think that would be a good approach.

**Comment by wojtekmaj** [comment]
Fixed, will be public with next release.

**Comment by jtwhittington** [comment]
Yeah I realized this was a bug on the Intl.DateTimeFormat, thanks for the fix!

**Comment by wojtekmaj** [comment]
Thank *you* for reporting! ;)
