### ISSUE TITLE
Highlight dates

### ISSUE THREAD

**Issue by UlrichMD** [wojtekmaj/react-calendar#607]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

It would be great if we could give a List of dates to the Calendar as prop and those dates are highlighted. ( note that it work with a range of date when value=[date1, date2]... But what i mean here is having specific dates, not a range. Ex: value = [date1, date2, date3, date4, date5]

**Comment by wojtekmaj** [comment]
https://codesandbox.io/s/react-calendar-tilecontent-multiple-b5bfg

See also #566, #555, and [other](https://github.com/wojtekmaj/react-calendar/issues?q=tileClassName).
