### ISSUE TITLE
onActiveDateChange not working

### ISSUE THREAD

**Issue by kevde** [wojtekmaj/react-calendar#61]
I was trying to add onActiveDateChange listener in the Calendar component and when I click on the next/previous buttons it doesnt trigger

**Comment by kevde** [comment]
Hi, do you know whats the root cause of it?

**Comment by wojtekmaj** [comment]
Not really, we even have automated tests covering this and I don't seem to be able to reproduce this at the moment. :( Will have a second look.

**Comment by wojtekmaj** [comment]
Hello @kevde, as discussed in your PR, you're not running minimum required version of React, and that's why the callback is not called. You're likely having two Reacts installed (!) because of this incompatibility. Please upgrade!
