### ISSUE TITLE
When selecting a range across two months, ending the selection should not return to previous month

### ISSUE THREAD

**Issue by nunocasteleira** [wojtekmaj/react-calendar#611]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

As written in the title, when I'm selecting across two months (29/April through 9/May), after I selected the last date, the calendar returns to the starting date. Can we let the calendar stay in the month where the last selection was done?

**Comment by swee76** [comment]
@nunocasteleira same issue, if you found a solution please drop a comment below

**Comment by rajdeepdatta2898** [comment]
Please look into this issue, if it can be solved!

**Comment by tizba** [comment]
The feature is already available via the _goToRangeStartOnSelect_ prop. It is true by default, you just have to set it to false.

**Comment by lemontini** [comment]
the feature (mentioned by @tizba ) seems to be not working (at least in double calendar view). It doesn't make a difference what is the setting of `goToRangeStartOnSelect` - the selection of ending date always switches to the range start on the first calendar.

**Comment by alexbu92** [comment]
goToRangeStartOnSelect has no effect

**Comment by alexbu92** [comment]
Are there any workarounds for this? @wojtekmaj  is this on the roadmap by any chance?

**Comment by tizba** [comment]
> goToRangeStartOnSelect has no effect

Could you provide a github repo where it does not work ? If I have a little bit of time I could check it and make a pull request

**Comment by mishabak** [comment]
> goToRangeStartOnSelect has no effect

>  try this :- `goToRangeStartOnSelect = {false}    defaultActiveStartDate = {departure date} . that time it will work
