### ISSUE TITLE
How can it possible that every month start with monday?

### ISSUE THREAD

**Issue by Hammad-CT** [wojtekmaj/react-calendar#621]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

In short! if i'am changing single month to double month and also removing extra dates from every month(extra dates are next or previous month dates, which are on current month calendar). then days names remains on its position like every month's Calendar days start from Monday, How can it possible that every month's 1st date starts from Monday as in screenshot? 

![Screenshot 2022-06-30 at 11 03 19 PM](https://user-images.githubusercontent.com/106424939/176748591-4fa453c3-df48-4e07-80bd-41b7444e4952.png)

### Steps to reproduce

...

### Expected behavior

...

### Actual behavior

![Screenshot 2022-06-30 at 11 03 19 PM](https://user-images.githubusercontent.com/106424939/176749954-84f24f92-871e-4549-951f-497e6132f7bc.png)

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by LouiseReid** [comment]
I have the same issue. Seems to happen when you set both `showNeighboringMonth` and `showFixedNumberOfWeeks` to false. I want them both false though.

**Comment by wojtekmaj** [comment]
Doesn't look like so:
https://codesandbox.io/s/react-calendar-flags-to-false-zhcjqy

This must be a styling issue. For example if you rewrote calendar grid to be an actual CSS grid instead of flexbox, then these subtleties may be lost.

**Comment by LouiseReid** [comment]
Yea, I changed it to grid styling. Thanks

**Comment by jupavic** [comment]
Setting `showDoubleView` as per documentation forces both `showNeighboringMonth` and `showFixedNumberOfWeeks` to true and that's why it's rendered like this in double view. Is there some workaround?
