### ISSUE TITLE
Manually entered dates reset on edit attempt or calendar icon click

### ISSUE THREAD

**Issue by marcaaron** [wojtekmaj/react-calendar#63]
Clicking away from and back onto the manual date entry field after user inputs will reset those fields. Similarly, clicking on the calendar icon will throw away the manually entered date. The behavior I expected is that the calendar icon would open up the date picker to the manually entered date and represent it's place on the calendar itself. But instead it clears it... thoughts?

**Comment by wojtekmaj** [comment]
Hey,
date picker resets to the last correct value when an incorrect value has been entered (entered being defined as in any other input, so on focusing away). If you type the correct date it should work fine... Would you share an example?

**Comment by marcaaron** [comment]
Ah sorry! This was meant for the react-date-picker repo issues, but either way I hadn't yet hooked up the onChange handler or set value (>.<) now it works fine!

**Comment by wojtekmaj** [comment]
Haha, I didn't even noticed :P No worries. Happy coding!
