### ISSUE TITLE
use "ISO-8601" as calendarType but set first day of the week to Sunday

### ISSUE THREAD

**Issue by mikeyyyzhao** [wojtekmaj/react-calendar#637]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I know you can set the start of the week to Sunday through `calendarType` but that also affects the week number. We have users who want to keep the week count consistent with everyone they work with but start their calendar on a Sunday.

### Proposed solution

Add a override prop to pass in start of the week

**Comment by wojtekmaj** [comment]
calendarType only affects week start date & week numbering, so do you really need a separate prop for your use case?

**Comment by mikeyyyzhao** [comment]
But it affects both at the same time. I don't think they should be coupled together. Often, start date is a personal preference but if I set the calendarType to match the start date, the week number is going to be incorrect/off.

**Comment by wojtekmaj** [comment]
Week numbers are calculated differently depending on calendar type. Not sure how could we mark week numbers if we introduce a separate options for week start weekday.

**Comment by hanzlahabib** [comment]
Would be great if we can get this option, because different regions have different weekend days, it would be great if we can dynamically pass weekend date


Thanks

**Comment by AlexandreSi** [comment]
@wojtekmaj Pinging you to have your input on this, I think it's worth the discussion.
