### ISSUE TITLE
Cannot npm install forked repository

### ISSUE THREAD

**Issue by maxforbang** [wojtekmaj/react-calendar#648]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

This is an amazing calendar. 

When I do `npm install react-calendar` and `npm start` everything works fine.

However, when I fork the repo and install with `npm install https://github.com/maxforbang/react-calendar` I get the following error:

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code 1
npm ERR! path C:\Users\Max\Documents\Code\calendar\node_modules\react-calendar
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install
npm ERR! 'husky' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Max\AppData\Local\npm-cache\_logs\2022-09-23T23_35_30_506Z-debug-0.log
```

Here is what is contained in "C:\Users\Max\AppData\Local\npm-cache\_logs\2022-09-23T23_35_30_506Z-debug-0.log":

```
107 verbose stack Error: command failed
107 verbose stack     at ChildProcess.<anonymous> (C:\Users\Max\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
107 verbose stack     at ChildProcess.emit (node:events:527:28)
107 verbose stack     at maybeClose (node:internal/child_process:1092:16)
107 verbose stack     at Socket.<anonymous> (node:internal/child_process:451:11)
107 verbose stack     at Socket.emit (node:events:527:28)
107 verbose stack     at Pipe.<anonymous> (node:net:709:12)
108 verbose pkgid react-calendar@3.9.0
109 verbose cwd C:\Users\Max\Documents\Code\calendar
110 verbose Windows_NT 10.0.19044
111 verbose node v16.16.0
112 verbose npm  v8.19.2
113 error code 1
114 error path C:\Users\Max\Documents\Code\calendar\node_modules\react-calendar
115 error command failed
116 error command C:\WINDOWS\system32\cmd.exe /d /s /c husky install
117 error 'husky' is not recognized as an internal or external command,
117 error operable program or batch file.
118 verbose exit 1
```

I forked it so that I could make custom changes own repository and be able to npm install those changes directly on a different server. This will allow me to create a bundle.js and import my source code into something like Webflow to do something like this:

```
<head>
<script src="https://unpkg.com/react@16.4.1/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@16.4.1/umd/react-dom.production.min.js"></script>
</head>

<body>
...
<script src="https://[MY_SERVER]/bundle.js"></script>
...
</body>
```

(From https://webflow.com/blog/react-components-in-webflow#:~:text=React%20allowed%20me%20to%20build,project%20with%20a%20Webflow%20site.)

If anyone has an ideas as to what the issue could be, it would make my week - I've been trying different solutions for around 6 hours. Thanks in advance!

### Steps to reproduce

1. Fork the repository
2. npm install with the provided Git repo url: `npm install --save https://github.com/[username]/[repository] --save`

(this is on a Windows machine)

### Expected behavior

Should install react-calendar as a dependency.

### Actual behavior

Npm gives the following error:
```
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install
npm ERR! 'husky' is not recognized as an internal or external command,
```

If you install husky with `npm install -g husky` then you get the following error instead:
![react-calendar-error](https://user-images.githubusercontent.com/50570544/192070603-55c044df-b2bd-47fe-8307-c1a4867c09b1.png)

`npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)`

### Environment

- **Browser (if applicable)**: Node (localhost:3000)
- **React-Calendar version**: 3.9.0
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
Installing React-Calendar from GitHub repo was never supported so I won't be able to help you with this.
