### ISSUE TITLE
meet a warning of Fit:  <Fit />'s child does not have absolute position. You should apply `position: absolute` to it

### ISSUE THREAD

**Issue by ShenAries** [wojtekmaj/react-calendar#649]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

when I click to open the dateRangePicker and it will show this warning in the console , and I think I followed the instructions to  install and use , and my environment is React 17 + TS, I installed "@wojtekmaj/react-daterange-picker": "^4.0.0" and "@types/wojtekmaj__react-daterange-picker": "^3.4.1", so what should I do can make this warning disappear?

### Steps to reproduce

        <DateRangePicker
            key={label}
            isOpen={isOpenDateRange}
            dayPlaceholder="dd"
            monthPlaceholder="mm"
            yearPlaceholder="yy"
            onChange={value => setRangeDate(value)}
            format="dd/MM/y"
            value={rangeDate}
            locale="en"
          />

### Expected behavior

when I click to open the picker, it won't show the warning  about "<Fit />'s child does not have absolute position. You should apply `position: absolute` to it"

### Actual behavior

it shows warning , I don't know how to fix it.

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:
 React 17
TS
@wojtekmaj/react-daterange-picker": "^4.0.0"
"@types/wojtekmaj__react-daterange-picker": "^3.4.1"

**Comment by mshakhriyorov** [comment]
@ShenAries Did you check if it is not from your `css` side?
