### ISSUE TITLE
Week view for Calendar

### ISSUE THREAD

**Issue by nhockool1002** [wojtekmaj/react-calendar#650]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I using a react-calendar, it's good. But when I only want to show a each week in month, this lib not support 
It's is a month view
<img width="413" alt="Screen Shot 2022-10-11 at 00 23 40" src="https://user-images.githubusercontent.com/29768725/194921494-17d17d7e-d005-47e5-ad50-319ed3b52dfb.png">

It's is week view, how to make it. Thanks.
<img width="414" alt="Screen Shot 2022-10-11 at 00 24 08" src="https://user-images.githubusercontent.com/29768725/194921558-c7d3ccca-51db-48b2-b22a-708e854744c9.png">

**Comment by wojtekmaj** [comment]
Duplicate of #70
