### ISSUE TITLE
Select Multiple Ranges

### ISSUE THREAD

**Issue by lagroms** [wojtekmaj/react-calendar#651]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Ability to select multiple ranges. 
Same as this : https://codesandbox.io/s/calendar-date-picker-with-multiple-ranges-f9e8r?file=/src/DatePickerRange/DatePickerRange.tsx

**Comment by rabbanirizwan** [comment]
@lagroms 
Can I work on this feature?

**Comment by lagroms** [comment]
I've actually switch to react-day-picker for the moment so I don't have an immediate need for this feature, unless someone else does ?
