### ISSUE TITLE
Invalid hook call in renderCustomHeader

### ISSUE THREAD

**Issue by potapovnikita** [wojtekmaj/react-calendar#677]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Invalid hook call in renderCustomHeader prop.

When I'm passing ReactComponent (with own useState hook inside) in renderCustomHeader prop, i'm getting error **Invalid hook call.....**.

Example: 
```
<DatePicker
          renderCustomHeader={DatePickerHeader}
          selected={value}
          onChange={(date) => setValue(date)}
          inline
          locale={LOCALE}
/>
```

where DatePickerHeader is React Component:

```
const DatePickerHeader: FC<ReactDatePickerCustomHeaderProps> = () => {
  const [someState, setSomeState] = useState(false);
  return (
    <div>Some Header</div>  
  );
}
```

### Steps to reproduce

1. Create React Component with inner state (useState) and pass it in renderCustomHeader (as in bug description).
2. See error in console.

### Expected behavior

Should working without error **Invalid hook call**

### Actual behavior

There is error in console **Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: .....**.

### Environment

- **Browser (if applicable)**: Google Chrome 106.0.5249.119 
- **React-Calendar version**: 4.8.0
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
This often happens if you have multiple versions of React in your bundle. Can't tell much else - the code you posted is fine, and the problem isn't directly related to React-Calendar itself.

**Comment by potapovnikita** [comment]
i have only one react version 

React version: 18.2.0

**Comment by wojtekmaj** [comment]
You confused React-Date-Picker with react-datepicker. I won't be able to help you out.
