### ISSUE TITLE
Week view?

### ISSUE THREAD

**Issue by madeinspace** [wojtekmaj/react-calendar#70]
Hi there,

Very nice component, thank you, I was wondering if a week view is planned somehow in the near future? or any advice on how I could achieve displaying such a view if possible?

thanks
Fabrice

**Comment by wojtekmaj** [comment]
Hello,
I wasn't planning on implementing this. If that would be a popular demand I may have a look on this though! Sadly it's far from being a low hanging fruit as we have an ordered list of views which cannot be changed, only limited from one side or the other. Adding the next view to the list would force people to use it with no easy way of getting around this. I need to give a lot of thought on how to design without affecting other people's projects.

**Comment by Jsalvat** [comment]
It would be nice a Week view for mobile purposes. React Calendar is not responsive atm

**Comment by decimoseptimo** [comment]
https://github.com/wojtekmaj/react-calendar/issues/314 https://github.com/wojtekmaj/react-calendar/issues/500 @wojtekmaj there's definitely demand.

It seems we're gonna need this, ala google calendar. Can you provide guidance?
