### ISSUE TITLE
Disabled days with MonthView

### ISSUE THREAD

**Issue by MariemMhenni** [wojtekmaj/react-calendar#704]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Hello, currently there is not a feature that allows users to disapled dates using `<MonthView>` is it possible to have a feature that allows to do that ( example  with `<Calendar/ >`   it exist props `"tileDisabled"` that allow to do that)

**Comment by wojtekmaj** [comment]
It's actually possible using the same prop, but it was never documented.
