### ISSUE TITLE
`locale` for uzbek language

### ISSUE THREAD

**Issue by mshakhriyorov** [wojtekmaj/react-calendar#705]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

I tried to change local to `uz-UZ`, but it doesn't behave in a correct way

### Steps to reproduce

Weeks and months are not translated into uzbek language: 
![image](https://user-images.githubusercontent.com/71601329/205495302-0e8738c2-5775-4031-929d-7bbcac9821c4.png)

### Expected behavior

It should be something like this
![image](https://user-images.githubusercontent.com/71601329/205495375-cb205326-f319-4b86-b683-25044ba006f0.png)

### Actual behavior

Weeks and months should be translated into uzbek language

### Additional information
Here is my code piece in case of any need
```
  <ReactCalendar
      className="react-calendar"
      nextLabel={<Icons.SvgChevronRight />}
      next2Label={null}
      prevLabel={<Icons.SvgChevronLeft />}
      prev2Label={null}
      minDetail="year"
      minDate={minDate || new Date(minDate)}
      maxDate={maxDate || new Date(maxDate)}
      onClickDay={(val) => setSelectedDate(val)}
      showFixedNumberOfWeeks
      value={value}
      locale="uz-UZ"
    />
 ```

### Environment

- **Browser (if applicable)**: Chrome
- **React-Calendar version**: `4.0.0`
- **React version**: `17.0.2`

**Comment by wojtekmaj** [comment]
That depends entirely on OS/browser `Intl` implementation. Here's Edge on macOS :)

<img width="362" alt="image" src="https://user-images.githubusercontent.com/5426427/223398633-f8346db8-cd2e-4530-9a38-e2187721e794.png">
