### ISSUE TITLE
Event calendar styling?

### ISSUE THREAD

**Issue by madeinspace** [wojtekmaj/react-calendar#71]
My use case here is simple, I'd like to style a tile based on some event related to particular dates, ie if I have an event on the day I'd like to put a single dot in the tile to indicate that there is an event that day?

How would you go about implementing this? thanks!

**Comment by wojtekmaj** [comment]
Hi,
you have `tileClassName` and `tileContent` props. In the examples, they are adding custom class and custom content for wednesdays and sundays respectively, but you should figure it out. Basically,

```js
({ date, view }) => view === 'month' && doIHaveEventOnThisDate(date) ? (class/content goes here) : null
```
