### ISSUE TITLE
selectRange example?

### ISSUE THREAD

**Issue by larsnystrom** [wojtekmaj/react-calendar#72]
I can no longer get react calendar to work when selectRange is true. It used to be that after selecting two dates, `onChange` was called with the selected range. But I can't make that work anymore and there's not reference/example I can compare my code to.

Could an example with selectRange be added to the repo and homepage?

**Comment by wojtekmaj** [comment]
Hello,
more advanced "playground", including "Select range" option, is available in /test folder of this repository. I use it to test all features manually when I need to, so you should be able to find every single option implemented there. Hope this helps!
