### ISSUE TITLE
Vertical Scroll to allow month change on scroll

### ISSUE THREAD

**Issue by chahatbahl** [wojtekmaj/react-calendar#726]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

This will be helpful in mobile devices where user can simply scroll

**Comment by wojtekmaj** [comment]
This is an excellent idea, but I doubt it would be possible to implement in the same component... Perhaps as an entirely different component, like InfiniteCalendar or something, could do the trick...

**Comment by chahatbahl** [comment]
Hello @wojtekmaj 
It's been implemented here: [showMonthView](https://www.npmjs.com/package/iui-react-calendar)
Prop used: showMonthView

This prop enables the vertical view

The project is forked from react-calendar :)

Let me know if we can somehow provide support in react-calendar library itself. I will be more than happy to contribute

**Comment by wojtekmaj** [comment]
This is a good idea, but too much of an architectural change to cope with for me.

However, you're free to use React-Calendar's subcomponents, also exported, to create a wrapping component that supports this kind of action.
