### ISSUE TITLE
Navigation doesn't work.

### ISSUE THREAD

**Issue by Naahuel** [wojtekmaj/react-calendar#75]
Hello! Love the plugin, but can't get it to work correctly.

I'm using `create-react-app` and I'm not sure if that's the problem. Here's my `package.json`

```
{
  "name": "sh-calendar-client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.4.0",
    "react-calendar": "^2.15.0",
    "react-dom": "^16.4.0",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
All I did was create a new app, delete the default App and just paste the example code:

```
import React, { Component } from 'react';
import Calendar from 'react-calendar';

class MyApp extends Component {
  state = {
    date: new Date(),
  }

  onChange = date => this.setState({ date })

  render() {
    return (
      <div>
        <Calendar
          onChange={this.onChange}
          value={this.state.date}
        />
      </div>
    );
  }
}
```
I get a working calendar as expected. The `onChange` method works fine. But I can't change the month or the year.  The arrow navigation does nothing. And If I click on the title, it changes the view correctly (year, century, etc) but the arrows continue to not work and no matter what year or month I select, it falls back to the date in `value`.

![peek 2018-05-25 20-36](https://user-images.githubusercontent.com/1612488/40569857-94d47f44-605b-11e8-8816-213548900606.gif)

**Comment by Naahuel** [comment]
Update: downgrading to 2.13.5 fixes the issue.

**Comment by balazsorban44** [comment]
same problem here

**Comment by basarevych** [comment]
downgrading to that version did help. thanks

**Comment by Naahuel** [comment]
Another thing I should add is that the sample in `/sample` does not work either. 

Steps to reproduce:

1.- Clone repository
2.- cd to `sample/`
3.- `npm install`
4.- `npm start`
5.- Open `http://localhost:1234` on your browser. 

Should show a Calendar working, except that I can't change the year or month.

**Comment by elboletaire** [comment]
Same here. Downgrading works, but the patch from @Naahuel doesn't work for me.

**Comment by wojtekmaj** [comment]
Guys,
this change was caused by a breaking change in minor version (!) of React 16.4. I'm working on a fix as I write. You should be able to downgrade to React 16.3 to resolve the issue or wait for my hotfix.

**Comment by wojtekmaj** [comment]
The issue has been fixed. Please refer to #78 for more details.
