### ISSUE TITLE
Broken <img> source in README.md

### ISSUE THREAD

**Issue by AlasdairWallaceMackie** [wojtekmaj/react-calendar#767]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Readme main image is pointing to this source: [https://projects.wojtekmaj.pl/react-calendar/react-calendar.jpg](https://projects.wojtekmaj.pl/react-calendar/react-calendar.jpg)
Now leads to a 404 page. I tried different URLs to see if the jpg name was simply changed, but no luck.
Readme: [https://github.com/wojtekmaj/react-calendar/blob/main/README.md](https://github.com/wojtekmaj/react-calendar/blob/main/README.md)

### Steps to reproduce

Readme img no longer visible

### Expected behavior

Image should appear

### Actual behavior

Broken image icon instead

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by AlasdairWallaceMackie** [comment]
![Screen Shot 2023-02-08 at 9 23 34 AM](https://user-images.githubusercontent.com/73504675/217557198-e006b9b0-4e7a-430b-8fb9-0dc5c4b2ae5c.png)

**Comment by wojtekmaj** [comment]
Ah lol, thanks a lot. Cleaned the directory after I migrated the entire showcase to Vite. :D
