### ISSUE TITLE
Format value to be displayed

### ISSUE THREAD

**Issue by Gtosta96** [wojtekmaj/react-calendar#77]
Hi,

There is some way to change the format of the value displayed on the input?
I mean, I want to hold the current value as a Date, but, I would like to format the displayed value as the image below:

![image](https://user-images.githubusercontent.com/11162653/40624322-45c765aa-6282-11e8-83c3-9399a61ae5e6.png)

Can I achieve that behavior?

**Comment by wojtekmaj** [comment]
Hi,
I don't think that's relevant to this package. React-Calendar simply returns a `Date()` in `onChange` and expects a `Date()` in `value`. React-Calendar does not come with an input like this, so it's your own or someone else's implementation.

**Comment by hugoh59** [comment]
I think this would be a great feature.

**Comment by wojtekmaj** [comment]
How can I implement a feature that formats input value if there's no input in this package? You may be looking for [React-Date-Picker](https://github.com/wojtekmaj/react-date-picker).
