### ISSUE TITLE
custom decade range

### ISSUE THREAD

**Issue by ShlomyYosef** [wojtekmaj/react-calendar#778]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Hello,
When the user goes to the decade view, there are only 10 years visible and there are two tiles left unoccupied. Is there a way to show 12 years?
also, there is a way to change the years?
I know we can use formatYear or tileContent, but then when I will click on the diary I will still get the original date.
for example, I want to show 2014-2025.

**Comment by wojtekmaj** [comment]
Sorry, the definition of a decade is pretty clear and there are no plans to introduce custom views at the moment.
