### ISSUE TITLE
Important message for React 16.4 users

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-calendar#78]
Hello,
React has released React version v16.4.0, which was considered a minor, non breaking update. This is sadly not a case and **it broke all React-Calendar versions from v2.14.0 to v2.15.0**.

#### Upgrade your React-Calendar

_Use this option if you'd like to help with further development of React-Calendar and you'd like to use the latest & greatest._

```shell
npm install react-calendar@latest
```
or
```shell
yarn upgrade react-calendar
```

If you went for this option, please vote with 👍 👎 reactions whether version v2.15.1 works fine for you and/or comment if you'd like to share your feedback. Thank you so much!

#### Downgrade React to version v16.3.x.

_Use this option if you are not comfortable with quick, relatively untested changes or you are not sure there are no more components that may have been broken by React 16.4._

```shell
npm install react@16.3.2 react-dom@16.3.2
yarn add react@16.3.2 react-dom@16.3.2
```
Thanks!

**Comment by Naahuel** [comment]
Thanks a lot @wojtekmaj for looking into it! Using v2.15.1 works great.
