### ISSUE TITLE
How can I select multiple disabled tiles?

### ISSUE THREAD

**Issue by barth12** [wojtekmaj/react-calendar#79]
Hi again :-)

Thanks for a new version of react-calendar. My question is pretty straightforward I guess. 
I need to disable many dates. How can I do that.

Till now I used:

                    tileDisabled={({date, view }) => 
                   date.getDate()===15 && date.getMonth()===4 && date.getFullYear()===2017}

Thank you for the wonderful work and great support!

**Comment by wojtekmaj** [comment]
I'd do this this way:

```js
const disabledDates = [
  new Date(2018, 0, 1),
  new Date(2018, 1, 2),
];

(...)

tileDisabled={(date, view) ->
  (view === 'month') && // Block day tiles only
  disabledDates.some(disabledDate =>
    date.getFullYear() === disabledDate.getFullYear() &&
    date.getMonth() === disabledDate.getMonth() &&
    date.getDate() === disabledDate.getDate()
  }
```

**Comment by barth12** [comment]
It works with a minor changes ;-) THANK YOU!

                    tileDisabled={({date, view}) =>
                        (view === 'month') && // Block day tiles only
                        disabledDates.some(disabledDate =>
                          date.getFullYear() === disabledDate.getFullYear() &&
                          date.getMonth() === disabledDate.getMonth() &&
                          date.getDate() === disabledDate.getDate()
                        )}
