### ISSUE TITLE
Preview more dates in calendar

### ISSUE THREAD

**Issue by Masshen** [wojtekmaj/react-calendar#805]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

To display the different dates of the events, we need another functionality (props) which can allow us to retrieve several dates and display them in the calendar.

![FireShot Capture 040 - react-calendar sample page - 127 0 0 1](https://user-images.githubusercontent.com/59833721/225075673-cf999773-f503-4124-ae79-d6c59afe142b.png)

**Comment by wojtekmaj** [comment]
I don't understand what the issue is, sorry. Happy to reopen if you elaborate.
