### ISSUE TITLE
Support for custom translations

### ISSUE THREAD

**Issue by naga-sanjay** [wojtekmaj/react-calendar#807]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Currently you are providing support for locales. But we have our own set of translations and it will be helpful if you can provide an option to provide our own custom translations of the content (day names, month names etc) to the package.

### Proposed solution

`<Calendar localeContent={jsonObject} />`

**Comment by wojtekmaj** [comment]
You can use `format*` props to achieve that. I like your idea, but I won't be adding second option to achieve the same thing, it's not very maintainable.
