### ISSUE TITLE
Missing dates in the calendar for some months 

### ISSUE THREAD

**Issue by AnuragChidanand** [wojtekmaj/react-calendar#813]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

In the component, there are some dates that are missing from certain months. like 20th and then 22nd, no 21st in between. 

### Steps to reproduce

1. Call the component
2. navigate thru the months
3. check the whole months calendar
4. might be missing some dates. 

### Expected behavior

The expected behavior must be to show all the dates and days present in a particular month. 

### Actual behavior

The actual behavior is that some dates are not showing in some particular months 

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Steps to reproduce? Code? Dates you're seeing the error in? Anything?
