### ISSUE TITLE
Showing two months at a time for range selection

### ISSUE THREAD

**Issue by ritz078** [wojtekmaj/react-calendar#82]
Thanks for this awesome component. 🎉  The no styling part makes this the best available solution for me. ❤️ 

I wanted to know if there is a way to show two months side by side for range view as generally, it makes sense if we are selecting a range.

I want something just like this.

<img width="635" alt="screen shot 2018-06-12 at 11 36 09 pm" src="https://user-images.githubusercontent.com/5389035/41308408-6a9a0c48-6e99-11e8-850a-262a1d8938b0.png">

**Comment by wojtekmaj** [comment]
Hello,
I think that's an awesome idea! Shouldn't be super hard to implement, too. I'm afraid that at the moment I'm super busy in my personal life, but I'm definitely keeping this in my backlog.

**Comment by wojtekmaj** [comment]
Coming soon... 👀 

<img width="726" alt="obraz" src="https://user-images.githubusercontent.com/5426427/61148221-9db68880-a521-11e9-9bdc-0b915e2960d3.png">

**Comment by jatindumka** [comment]
Hi @wojtekmaj  
showDoubleView prop not reflecting any change, not sure 🤔  below is how i have used.

  < Calendar
       // showDoubleView={true}
        showDoubleView={false}
        maxDate={new Date()}
        selectRange
      />

**Comment by jatindumka** [comment]
Hi @wojtekmaj 

Can a monthly rangepicker and yearly range picker also be achieved in new release???

**Comment by wojtekmaj** [comment]
Yes, absolutely. `showDoubleView` will show two months/years/decades/centuries side by side.

**Comment by jatindumka** [comment]
Hey @wojtekmaj  
How you are implementing MonthView, YearView, DecadeView, CenturyView .
There is  no demo code for these . Tried these as named export and default export , did not work for me. 
I m using v3 beta.
If you could explain on how to achieve month range selector , i.e just 2 month range panels similar to showDoubleView in Calendar.
 Thnx.

**Comment by wojtekmaj** [comment]
@jatindumka Use Calendar compononent, with prop `showDoubleView` + `minDetail` set to "month" if you don't want users to be able to select year/decade/century tanges.

**Comment by zigotica** [comment]
Hi,

Is it possible to decouple the `showDoubleView` and the `showFixedNumberOfWeeks`?  It actually causes some very weird behaviours like:

1. complete next/prev weeks unnecessarily shown in the other view
2. rangeStart/rangeEnd being shown twice in some scenarios

![showDoubleView-showFixedNumberOfWeeks](https://user-images.githubusercontent.com/178855/76513424-90f28780-6456-11ea-9523-2d7829cd640d.png)

Thank you anyway for the great component

**Comment by zigotica** [comment]
It can be "hacked" with a bit of CSS but shouldn't it be better to just avoid it?

```
.react-calendar__month-view__days__day--neighboringMonth:nth-last-of-type(7),
.react-calendar__month-view__days__day--neighboringMonth:nth-last-of-type(7) ~ .react-calendar__month-view__days__day--neighboringMonth {
  display: none;
}
```

Cheers

**Comment by wojtekmaj** [comment]
Actually decoupling `showFixedNumberOfWeeks` would just remove the last row on the right column in your case. I don't see how that would help...

Regarding pt 2, using class `.react-calendar__month-view__days__day--neighboringMonth` you should be able to style range in neighboring month just fine.

**Comment by zigotica** [comment]
I just hide all the`.react-calendar__month-view__days__day--neighboringMonth` days, problem solved. Thank you anyway for the component.
