### ISSUE TITLE
Only allow forward range selects

### ISSUE THREAD

**Issue by jorrit** [wojtekmaj/react-calendar#820]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Right now the following behavior seems default and unchangeable: when the user selects a start date, the next click will always be the end date, even when it is before the start date. In that case, the second date (which is earlier in time) becomes the start date of the range, and the first selected date is the end date.

My request is, to add a setting that when the user selects a date before the currently active start of the range, that date becomes the new start of the range.

Example:

1. User clicks January 10th.
2. User clicks January 3rd.

Current result:

Date range is January 3rd to January 10th.

New result (with feature flag turned on):

Date range is from January 3rd, but no end date is set yet.

**Comment by wojtekmaj** [comment]
Leverage `allowPartialRange` prop to read the work-in-progress range and set `minDate` equal to the value selected.
