### ISSUE TITLE
Tile being a button element interferes with content

### ISSUE THREAD

**Issue by samcarlinone** [wojtekmaj/react-calendar#85]
Currently the Tile class is implemented with its base element as a `button`.

This causes issues with certain pieces of content, in my case I cannot put tooltips on any custom content within the tile.

Could we either change the base element to `div` or offer the option to do so?

**Comment by wojtekmaj** [comment]
Hello,
I'm fairly certain `<button>` is the only way to go here. It's an active element and accessibility is one of the key features of React-Calendar.

Could you please elaborate on what you're trying to achieve? Maybe we'll figure something out!

**Comment by samcarlinone** [comment]
![image](https://user-images.githubusercontent.com/18744198/41413627-a545e592-6fb1-11e8-9cd3-b49f6018db01.png)

Basically I have complex content within calendar cells and I am trying to get a tooltip on a specific piece of the child content. Unfortunately both the builtin tooltip and bootstrap tooltip only work in Chrome unless I modify react calendar to use divs instead of buttons.

Perhaps expose a configuration option for using divs with the button role instead of actual buttons, for cases like mine where I need the functionality at a minor cost to accessibility since I know role="button" is not quite as well supported.

**Comment by wojtekmaj** [comment]
Whoa! You're doing quite a thing with this little widget :D 

Hmmm, custom solutions should be working, if you remember to preventDefault() and stopPropagation() so that the buttons won't be activated. Shouldn't they?

**Comment by samcarlinone** [comment]
It's a known bug in Firefox since they changed the original spec. `<button>` content doesn't receive mouse events, which is probably not a problem for 99% of applications that use this component. Luckily my client doesn't need it to work in Firefox, so you can close this if you want.

Like I said above though, switching `<div role="button">` for `<button>` should fix functionality, but I can't say for sure how it will affect accessibility ...

Thanks for the quick responses 👍

**Comment by wojtekmaj** [comment]
I can't say how it would affect accessibility either so I'd rather play it safe. Sorry for that! You're still welcome to make a fork if you would need this after all. We shouldn't have too many (if any) conflicts :)

**Comment by jhammersholt** [comment]
I tested the <div role="button"> (sadly have i client where it need to work in Firefox) and i need clickable events inside the tiles.

This has a number of issues where CSS is one (hover effect not working).
Also when limiting the calendar with minDate and maxDate the clickOnDay/onChange of a disabled tile makes it behave wonky (when clicking later than maxdate) the last acceptable tile gets marked as if it was selected.

Any pointers on how to solve this is greatly appreciated

**Comment by jonnycook** [comment]
> I'm fairly certain <button> is the only way to go here. It's an active element and accessibility is one of the key features of React-Calendar.

But what is the downside to giving users of your library the freedom to choose whether or not accessibility is a priority? I understand using buttons as a default element, but I do not understand imposing that decision on your users.
