### ISSUE TITLE
Chrome seems to override locale

### ISSUE THREAD

**Issue by andrewfairlie** [wojtekmaj/react-calendar#853]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

When setting locale, Safari and Firefox show the correct locale but Chrome seems to override it back to English.

### Steps to reproduce

1. Set a locale on a calendar
2. Go on Chrome
3. See error

### Expected behavior

It falls back to English

### Actual behavior

It should honour whatever locale is defined

**Comment by wojtekmaj** [comment]
Certain locales may not be supported well by certain browsers/ operating systems. Which locale are you trying to use?

**Comment by TGriffiths88** [comment]
Also having this issue when trying to use Welsh, 'cy' locale. Works perfectly in Firefox, Safari. But in Chrome it seems to just display in English. Tried disabling the browser translation to see if that was interfering but it doesn't change anything. 

Would appreciate if you had any thoughts on how to get this working? Many thanks
