### ISSUE TITLE
tileContent not working

### ISSUE THREAD

**Issue by Subho24** [wojtekmaj/react-calendar#854]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

The tileContent is sometimes not rendering '--' for the dates that has bookings and sometimes rendering '--' for the dates that does not has any bookings.

below is my code:

    const bookingAvailable = (date) => {
        if (allBookings) {
          for (let i = 0; i < allBookings.length; i++) {
            if (allBookings[i].booking_date === new Date(date).toISOString().split('T')[0]) {
              return true;
            }
          }
        }
        return false;
      };

    return(
        <Calendar 
            value={currDate}
            onChange={handleChange} 
            tileContent={({ activeStartDate, date, view }) => {
                if(allBookings.length > 1) {
                    console.log(`Checking bookings for ${date.toISOString().split("T")[0]}`);
                    console.log(`Booking available? ${bookingAvailable(date)}`);
                    if (bookingAvailable(date)) {
                      return "--";
                    } else {
                      return null;
                    }
                }
            }}              
        />
    )

### Steps to reproduce

..

### Expected behavior

Render '--' if condition met, otherwise render nothing

### Actual behavior

it is rendering '--' even if the condition is not met 

### Additional information

![react-calendar_issue](https://user-images.githubusercontent.com/87044211/236522681-a978505d-cdf4-43d0-8347-699334c37bb7.png)

### Environment

- **Browser (if applicable)**: Chrome
- **React-Calendar version**: 4.2.1
- **React version**:18.2.0

**Comment by wojtekmaj** [comment]
The way you're stringifying date is incorrect, as you are getting an ISO string, which is NOT local time (that the calendar uses). 

For example, in Berlin, UTC+1, if it's Tuesday midnight, it's still Monday 23:00 ISO (UTC+0) time. 

For this reason May 1st gets stringified to 2023-04-30, May 2nd to 2023-05-01 and so on.
