### ISSUE TITLE
Typescript error for value

### ISSUE THREAD

**Issue by DevTGhosh** [wojtekmaj/react-calendar#855]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

The sample example is throwing a ts error on the value prop. 

```
(property) value?: LooseValue | undefined
No overload matches this call.
  Overload 1 of 2, '(props: CalendarProps | Readonly<CalendarProps>): Calendar', gave the following error.
    Type 'Date | (Date | null)[] | null' is not assignable to type 'LooseValue | undefined'.
```

[Codesandbox](https://codesandbox.io/p/sandbox/recursing-chatelet-m6nbnn?file=%2Fsrc%2FApp.tsx%3A12%2C16)

### Steps to reproduce

1. Install react-calendar in a ts app
2. Follow the example from sample 
3. See the ts error on value

### Expected behavior

No ts error 

### Actual behavior

Ts error being shown on value

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**: 4.2.1
- **React version**: 17+

**Comment by wojtekmaj** [comment]
Thanks, my bad, types were improved since sample suite was updated.
