### ISSUE TITLE
export CalendarProps interface to allow for props typing in extending components

### ISSUE THREAD

**Issue by majdnaji** [wojtekmaj/react-calendar#856]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

i want to be able to import CalendarProps types to help with typing wrapper compontns

**Comment by wojtekmaj** [comment]
You don't need that :)

`type CalendarProps = React.ComponentProps<Calendar>;`

**Comment by maciejregula** [comment]
@wojtekmaj when I do this I receive: "Type 'Calendar' does not satisfy the constraint 'keyof IntrinsicElements | JSXElementConstructor '."

```js
import React from "react";
import { Calendar } from "react-calendar";
import "./Calendar.css";

//export interface CalendarProps extends ReactCalendarProps {}
type CalendarProps = React.ComponentProps<Calendar>;
```

**Comment by wojtekmaj** [comment]
I'd need to see full example to help out. What I proposed is what I exactly do in React-Date-Picker for example and it works great.

Nonetheless, exporting it makes sense. This is in the works.
