### ISSUE TITLE
Change weekend colors from Red to "X" in Calendar view?

### ISSUE THREAD

**Issue by slenderbowman** [wojtekmaj/react-calendar#86]
Hello, Using a calendar view on my webpage and I find the red color denoting the weekend dates a little jarring.  I tried modifying the following section of Calendar.less to a different color but did not observe any changes.

 &__days {
      &__day {
        &--weekend {
          color: red;
        }

I also cannot figure out a way to change just the color of the weekend dates using my CSS file. Any help with this issue would be appreciated, thanks.

**Comment by wojtekmaj** [comment]
Mmmm. That's exactly what you should be editing. Just remember if you edit Calendar.less, then you need to use `entry.nostyle` for default styles not to be imported, and import your modified LESS file yourself.

Check using Inspect element if your rule is properly applied to weekend days. Check if it's not overwtitten by anything.

**Comment by slenderbowman** [comment]
Is there a way that I can just modify the default styling rather than doing nostyle then importing the less. I really only want to change this one small thing?

**Comment by slenderbowman** [comment]
Solved my problem. For those curious, I copied and pasted the CSS file found in dist and placed it in the same folder as my reactjs files, and imported it. Then i simply changed 

.react-calendar__month-view__days__day--weekend {
    color: red;
  }

to my desired color. Did not need to import entry.nostyle for this fix. Thanks for your help!

**Comment by wojtekmaj** [comment]
However, this way you have two CSS files doing essentially the same. If you copied the CSS already, I suggest you using entry.nostyle to avoid it ;)
