### ISSUE TITLE
[Demo] The resource is not available in Belarus

### ISSUE THREAD

**Issue by corporate-rat** [wojtekmaj/react-calendar#864]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Tried to read the docs, or check the demo. 
Got 403. 
Not available. 
What's interesting, under VPN e.g. The Netherlands, website works correctly. 

website url: https://projects.wojtekmaj.pl/react-calendar/

### Steps to reproduce

1. go to Minsk. 
2. open internet browser
3. open url: https://projects.wojtekmaj.pl/react-calendar/
4. see 403. 

### Expected behavior

Expected https://projects.wojtekmaj.pl/react-calendar/ to be totally fine in BY zone. 

### Actual behavior

403 error

### Additional information

In case of need for remote testing please contact me via email.  k.yermakou@a1.by

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:
Microsoft Edge, Safari-Mobile.

**Comment by wojtekmaj** [comment]
That's deliberate, sorry

**Comment by corporate-rat** [comment]
@wojtekmaj, Well, np.  Are you interested in my next steps then?
