### ISSUE TITLE
TypeScript types aren't all exposed from the library

### ISSUE THREAD

**Issue by sernaferna** [wojtekmaj/react-calendar#866]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

When I was using `@types/react-calendar` *all* of the types were exposed, which allowed me to to create memo-ized callback functions to handle events coming from the calendar (via `useCallback()`). 

For example, I could do something like this:

```TSX
import React, { useCallback, useState } from 'react';
import Calendar, { CalendarTileProperties, ViewCallback } from 'react-calendar';

export const SomeComponent = () => {

  const getTileContent = useCallback(
    ({ date, view }: CalendarTileProperties) => {
      // do a bunch of work

      return <p>blah</p>;
    },
    [...]
  );

  return (
          <Calendar
            tileContent={getTileContent}
          />
  );
};
```

### Steps to reproduce

Any attempt to use types outside of the `<Calendar/>` component itself.

### Expected behavior

I'd like to see *all* of the types exposed from the library as types that can be leveraged in the calling application.

### Actual behavior

Everything works fine if writing the functions within the context of the component itself; e.g.

```TSX
<Calendar tileContent={({ activeStartDate }) => {
     // TypeScript can make use of the types in here
  }}
/>
```

### Additional information

The types are all defined in the library but they're not exposed from the package, so I have to import them from `react-calendar/dist/cjs/shared/types` which feels like a hack to me.

### Environment

- **Browser (if applicable)**: N/A
- **React-Calendar version**: 4.2.1
- **React version**: 18.2.0

**Comment by wojtekmaj** [comment]
You can always use `React.ComponentPropsWithoutRef<typeof Calendar>` but I totally get that, that's why it was done in b648740f4461bd68e1225cb90c3872fc711b3195 already.

Released in 4.3.0.

**Comment by sernaferna** [comment]
Thanks for this, but it only exposes `CalendarProps`, not `TileContentFunc` and/or `TileProps`.

**Comment by wojtekmaj** [comment]
Right. We could do that for you :D
