### ISSUE TITLE
Add support of calendar "view only" mode

### ISSUE THREAD

**Issue by felixmosh** [wojtekmaj/react-calendar#876]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

In my app there is a requirement to show a simple calendar with holidays, without the need to select days etc..., in this case there is no reason to render the `Tile` as `button` (interactive element) but it can be a simple `div`.

### Proposed solution

I've patched the lib, and rendered a `div` if `onClick` is not defined.

**Comment by felixmosh** [comment]
Ping

**Comment by wojtekmaj** [comment]
Tried to do that but the types in Calendar.tsx get too complex for me to handle it quicky. You're welcome to have a look if you'd like to get it done asap.
