### ISSUE TITLE
Month is disabled if first day of the month is disabled in tileDisabled

### ISSUE THREAD

**Issue by francesca-gk** [wojtekmaj/react-calendar#877]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

I need to make some of the days of the month unavailable based on the result of an API. It works great but, whenever the first day of the month is disabled in tileDisabled, if clicked on the month for the month view, the month is disabled and is not clickable anymore. 
It doesn't do that if there are other days disabled.
As you can see from the pictures I can select May, that has some dates disabled, but not June or July that have the first day disabled. July was selectable before we added 1st-2nd to the list of disabled dates. 
<img width="312" alt="Screenshot 2023-07-03 at 11 20 35" src="https://github.com/wojtekmaj/react-calendar/assets/122779654/38caee04-028f-4121-92ec-b11b9f61d3fb">
<img width="318" alt="Screenshot 2023-07-03 at 11 20 42" src="https://github.com/wojtekmaj/react-calendar/assets/122779654/19b9d571-696f-4339-a0a2-dd2911fa152f">
<img width="304" alt="Screenshot 2023-07-03 at 11 20 50" src="https://github.com/wojtekmaj/react-calendar/assets/122779654/28e49457-7efb-4019-97b2-2fe52a4105dd">

### Steps to reproduce

Disable first days of the month and it will be disabled

### Expected behavior

I would expect the month to be selectable if there is at least one date that is NOT disabled. 

### Actual behavior

The month is disabled even though there are selectable dates and, if it starts from that month, it lets me pick dates. 

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
I got you! :) Since `tileDisabled` works for all views, it is called on year, decade and century views, too. Note how `tileDisabled` gets passed an object with `activeStartDate`, `date`, and most notably, `view`. So What you need to do - I'll need to imagine your code here - is:

```diff
-function tileDisabled({ activeStartDate }) {
+function tileDisabled({ activeStartDate, view }) {
  // …

-  return shouldDateBeDisabled(activeStartDate);
+  return shouldDateBeDisabled(activeStartDate) && view === 'month';
}
```

That's it!

**Comment by francesca-gk** [comment]
> Since `tileDisabled` works for all views, it is called on year, decade and century views, too. Note how `tileDisabled` gets passed an object with `activeStartDate`, `date`, and most notably, `view`. So what you need to do - I'll need to imagine your code here - is:
> 
> ```diff
> -function tileDisabled({ activeStartDate }) {
> +function tileDisabled({ activeStartDate, view }) {
>   // …
> 
> -  return shouldDateBeDisabled(activeStartDate);
> +  return shouldDateBeDisabled(activeStartDate) && view === 'month';
> }
> ```
> 
> That's it!

Yes, I figured it out, thank you very much for the reply and the DatePicker!! :D
