### ISSUE TITLE
onViewChange isn't triggered when month is changed on clicking navigation "next"

### ISSUE THREAD

**Issue by twentyse7en** [wojtekmaj/react-calendar#878]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

![image](https://github.com/wojtekmaj/react-calendar/assets/59721339/8e1a0016-d392-441c-a67c-29f6d68c7e24)

`onViewChange` isn't triggering for month change by clicking next button.

### Steps to reproduce

1. add a callback to onViewChange
2. click on next button as on screenshot

### Expected behavior

When I click on next or prev button to change month onViewChange isn't triggered

### Actual behavior

onViewChange should be triggered

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**: 4.2.1
- **React version**:

**Comment by wojtekmaj** [comment]
This is correct. "View" is what we call one of "month", "year", "decade", "century". You're not changing the view when switching between months. What's changing when switching between months is activeStartDate.
