### ISSUE TITLE
TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by maheshlavanam** [wojtekmaj/react-calendar#88]
Hi,

We have installed react-calendar version 2.15.2 and rendered the calendar. but, we are experiencing the error as "TypeError: Super expression must either be null or a function, not undefined"

![upload](https://user-images.githubusercontent.com/40496612/41784030-1b228a6c-765c-11e8-80aa-012a10221f42.png)

Please do let us know how can we resolve this issue?

Thanks,
Mahesh

**Comment by wojtekmaj** [comment]
Hello,
which version of React are you using?

**Comment by maheshlavanam** [comment]
Hi,

We are using React version 0.13.3

Thanks,
Mahesh

**Comment by wojtekmaj** [comment]
Minimum requirement for React-Calendar is React 15.5. That was not stated in docs - thank you, I updated it.

I highly recommend you to upgrade!
