### ISSUE TITLE
Programmatically go to next/prev month

### ISSUE THREAD

**Issue by aamorozov** [wojtekmaj/react-calendar#885]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I was going through the readme & issues and haven't found a way to do this. The idea is that if an action outside of the component needs to "reset" the calendar to the initial state of the first available date. Currently even if the list of available dates changes, the calendar stays on a month it previously had active.

```
"react": "17.0.2",
"react-calendar": "4.4.0",
```

#### Update 
found this https://github.com/wojtekmaj/react-calendar/issues/532 issue, but not 100% certain if it's applicable to my use case;

**Comment by wojtekmaj** [comment]
That's very much your use case. You want to control Calendar state, much like you can have controlled or uncontrolled input.

https://github.com/wojtekmaj/react-calendar/issues/532#issuecomment-906372870

**Comment by aamorozov** [comment]
thank you! i'll give that a try
