### ISSUE TITLE
@types/lodash Type expected.  TS1110

### ISSUE THREAD

**Issue by gabrielvieiraes** [wojtekmaj/react-calendar#890]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

reactjs/node_modules/@types/lodash/common/object.d.ts(1025,21):
Type expected.  TS1110

    1023 |     type GetIndexedField<T, K> = K extends keyof T
    1024 |         ? T[K]
  > 1025 |         : K extends `${number}`
         |                     ^
    1026 |             ? 'length' extends keyof T
    1027 |                 ? number extends T['length']
    1028 |                     ? number extends keyof T

### Steps to reproduce

Install the library and show this error

### Expected behavior

Show component

### Actual behavior

Show error

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
* Can't reproduce
* Error comes from a package I don't maintain
* I find it unlikely that @types/lodash is broken, it's a super popular package; perhaps you have a really old TypeScript version?

**Comment by gabrielvieiraes** [comment]
TypeScript version = ^3.7.2

**Comment by wojtekmaj** [comment]
Yeah mate, you'll have to update. I'm afraid the TypeScript version you're using is basically useless at this point. Please see: https://github.com/DefinitelyTyped/DefinitelyTyped#support-window

**Comment by Hetape** [comment]
> Yeah mate, you'll have to update. I'm afraid the TypeScript version you're using is basically useless at this point. Please see: https://github.com/DefinitelyTyped/DefinitelyTyped#support-window

Hello . @wojtekmaj  , how's going ? I wanna ask one thing . so , how to fix this issue? I get in stuck with same issue . I haven't found out solutions to this issue yet. pls help me out .
