### ISSUE TITLE
Warning: Prop `aria-label` did not match

### ISSUE THREAD

**Issue by Muhameti-centralsoft** [wojtekmaj/react-calendar#891]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

The first time the calendar is displayed I get the following warning.

> Warning: Prop `aria-label` did not match. Server: "August 1, 2023" Client: "1 August 2023"

![image](https://github.com/wojtekmaj/react-calendar/assets/80449613/cdd43081-d747-470d-91e1-e286b3286c3c)

### Steps to reproduce

Go to the page where react-calendar is displayed and maybe refresh the page.

### Expected behavior

There is no warning

### Actual behavior

There is a warning

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
In SSR mode, the server side rendered component has no way of knowing what the browser's preferred locale might be. This is passed to the server in HTTP headers. You would need to figure out which locale to use based on this header.

Easier alternative: provide hardcoded locale.

**Comment by Muhameti-centralsoft** [comment]
Many thanks! It solved the issue for me :)
