### ISSUE TITLE
Calendar not working properly with iOS 16.6

### ISSUE THREAD

**Issue by MLAvolvo** [wojtekmaj/react-calendar#894]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

We are using react-calendar in one of our projects. Ever since they have updated to the new iOS 16.6 version the Calendar does not work properly. Users cannot select a date from the calendar, it is only possible to select the date that is the same as the month. i.e. 8th of August (8/8), 7/7, 6/6 and so on... 
Have tried in other browsers.
Anyone else with this issue or know how to solve it?

### Steps to reproduce

- Download iOS 16.6
- Nothing works

### Expected behavior

The date chosen to be selected

### Actual behavior

The date does not get selected unless its the same number as the month

### Additional information

Works for other iOS and OS versions. 

### Environment

- **Browser (if applicable)**: All browsers
- **React-Calendar version**: 3.7.0
- **React version**: ^17.0.2

**Comment by AndressaTonietto** [comment]
I am having the same problem! You can only select dates that are the same number as the month. And only for iOS 16.6, it doesn't matter which browser I use.

**Comment by MLAvolvo** [comment]
> I am having the same problem! You can only select dates that are the same number as the month. And only for iOS 16.6, it doesn't matter which browser I use.

So weird!!

**Comment by MLAvolvo** [comment]
.

**Comment by wojtekmaj** [comment]
Why did you close this? Is the issue resolved somehow?
