### ISSUE TITLE
How to color days to signify events that occur on those days?

### ISSUE THREAD

**Issue by PhilAndrew** [wojtekmaj/react-calendar#9]
Hi, is there any way to color the days on the calendar so that I can identify to the user that those days have events on them? Color the background of the cell?

**Comment by wojtekmaj** [comment]
Hey @PhilAndrew,
you can use `renderChildren` to add your custom content to the cell. The cell itself at the moment cannot get any custom styles, although I think about adding another function that would allow you to return the list of cell classes, given cell date.
Is that something you would be looking for?

**Comment by wojtekmaj** [comment]
Hey @PhilAndrew,
React-Calendar version 2.4.0 just went live! Check out `tileClassName` (and `tileContent`) in README.md.
Hope this helps!
