### ISSUE TITLE
Typings for onChange callback

### ISSUE THREAD

**Issue by inoyakaigor** [wojtekmaj/react-calendar#90]
onChange callback as fact can accept parameter with type equal `Date` or `Array<Date>` depending on the `returnValue` prop but in typings this function defined as function with only one type for parameter:
https://github.com/wojtekmaj/react-calendar/blob/59fde68e34729d604916bb5f62bd657b868f93ba/index.d.ts#L24
https://github.com/wojtekmaj/react-calendar/blob/59fde68e34729d604916bb5f62bd657b868f93ba/index.d.ts#L3

I was thinking about make PR with that code
```
type DateCallback = (date: Date | Date[]) => void 
```
but i not sure what this might affect

**Comment by wojtekmaj** [comment]
Hmmm, that looks like a pretty safe change to me. As far as I know, there's no way to make conditional typings, so declaring every possible value makes sense. I'd be happy to merge a PR if you make one!
