### ISSUE TITLE
WeekstartDay cant be configured by just using calenderType prop, because it accepts only 4 values

### ISSUE THREAD

**Issue by anitha96ashok** [wojtekmaj/react-calendar#915]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

i want to be able to configure weekstartday to any day of the week, as per user's discretion. there is no HOc directly available to control that, if i want the start of the week to be wednesday, i cant do that. 

### Steps to reproduce

There is no steps, its just a prop that u pass to component

### Expected behavior

there should be mapping of each calendarType to each specific day of the week, or simply a new prop can be introduced to control start of the week selection.

### Actual behavior

only 4 types of calendarTypes can be given which map to only 3 days of the week. so if user wants the start of the week to be wednesday, it cant be configured.

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Which calendar starts on Wednesday?
