### ISSUE TITLE
Setting the value of the calendar to undefined doesn't deselect the day that was previously selected

### ISSUE THREAD

**Issue by santiagopuentep** [wojtekmaj/react-calendar#921]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

I set the value to a certain date and that day turns blue. If I then set the value back to undefined, the day is still blue.

### Steps to reproduce

1. Set the value prop to a day.
2. Set the value prop to undefined.
3. See how the day that was set in step 1 is still blue.

### Expected behavior

The blue color should disappear if no date is selected.

### Actual behavior

The blue color is still there as if there was a date selected, but the value is undefined so there shouldn't be any.

### Environment

- **React-Calendar version**: 4.8.0
- **React version**: 18.2.0

**Comment by rlebascle** [comment]
@santiagopuentep If you set the value to null it will work as expected.

**Comment by santiagopuentep** [comment]
> @santiagopuentep If you set the value to null it will work as expected.

It worked. Thanks! It still looks like a bug so I'll leave the issue opened.

**Comment by jul0706** [comment]
It doesen't work for me.  In mode allowPartialRange=true, if selected just a begin of date ranges, when I want clear values, I get setValues(null), but the blue color is still there. If selected both of values date range, clearing (setValues(null)) is working

**Comment by rlebascle** [comment]
@jul0706 
Yes, I have met that bug too. But it doesn't seem to be related to allowPartialRange=true, it also happen with selectRange only.
I did investigate and it seems to come from that line: 
https://github.com/wojtekmaj/react-calendar/blob/v3.0.0/src/Calendar.jsx#L176
I didn't manage to fix it. From what I understand the Calendar is holding a "state" value internally.

**Comment by rlebascle** [comment]
I made a code sandbox to reproduce the bug.
[Code sanbox](https://codesandbox.io/p/sandbox/hidden-night-9mkqvl?file=%2Fsrc%2FApp.js%3A10%2C26&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxalzzb00063586mmlksl75%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxalzza00023586hsncbi8k%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxalzza00033586560wco9v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxalzza00053586v7siqm5s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxalzza00023586hsncbi8k%2522%253A%257B%2522id%2522%253A%2522clsxalzza00023586hsncbi8k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxb28j60002358d0k7c45bg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A26%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsxb28j60002358d0k7c45bg%2522%257D%252C%2522clsxalzza00053586v7siqm5s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxalzza00043586bav0l8t2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsxalzza00053586v7siqm5s%2522%252C%2522activeTabId%2522%253A%2522clsxalzza00043586bav0l8t2%2522%257D%252C%2522clsxalzza00033586560wco9v%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsxalzza00033586560wco9v%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Travis-Kirton** [comment]
This is still an issue, I'm able to workaround by setting a key prop on the calendar but that feels dirty. Any scope to pick this up and fix? Or I can take a look at some point.
