### ISSUE TITLE
Entire week selection

### ISSUE THREAD

**Issue by MichaelLiss** [wojtekmaj/react-calendar#929]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

I would like to be able to click on any day of any week and have the entire week selected
the control would return the start date and end date of the week selected.

### Proposed solution

I believe there should be method that is used to activate "week selection" mode.
In this example, the control would return a start date of 5 May 2024 and end date of 11 May 2024 and the clicked on date of 6 May 2024

![image](https://github.com/wojtekmaj/react-calendar/assets/39492750/f78b6091-ff7d-423b-a92a-8d3afdec93f9)

**Comment by Qodestackr** [comment]
How do you wish to go about this?

**Comment by wojtekmaj** [comment]
You could always use React-Calendar in a "controlled mode" and expand selection in onChange function.
