### ISSUE TITLE
Support Ethiopian calendar

### ISSUE THREAD

**Issue by girma336** [wojtekmaj/react-calendar#937]
### Before you start - checklist

- [ ] I have checked if this feature request is not already reported

### Description

- It has a locale for Ethiopians - am but the calendar is different from all over the world. If  you need any help to the calender you can contact me.

**Comment by wojtekmaj** [comment]
These are the calendars we can potentially support: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getCalendars

Is the one you're interested in listed here?
