### ISSUE TITLE
First date selection not clearable in selectRange mode

### ISSUE THREAD

**Issue by tayoawoyemi** [wojtekmaj/react-calendar#947]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

When using the calendar in range selection mode as a controlled component the first date selection of a range is currently not clearable.

### Steps to reproduce

Example: https://codesandbox.io/p/sandbox/react-calendar-example-6gq3tr

1. Go to the example codebox
2. Select a date range
3. Click the reset button
4. See that both selected dates are reset
5. Select a single date
6. Click the reset button
7. See that the selected date is not reset

### Expected behavior

Setting the calendars value to `null` should reset a single date selection in selectRange mode

### Actual behavior

Single date selection is not clearable while in selectRange mode

### Additional information

Looks like this code is responsible:

https://github.com/wojtekmaj/react-calendar/blob/main/packages/react-calendar/src/Calendar.tsx#L692

`// In the middle of range selection, use value from state
      if (selectRange && getIsSingleValue(valueState)) {
        return valueState;
 }`
 
 

### Environment

React-Calendar version: 5.0.0
React version: 18.0.2

**Comment by savayer** [comment]
@tayoawoyemi have you found a way to solve this problem?

**Comment by savayer** [comment]
only re-rendering helps me

```js
<ReactCalendar
  key={rerenderKey}
  ...
/>
```

**Comment by tiagotwistag** [comment]
Same issue here, and ended up with the same solution of forcing a a re-mount of the component by changing the key
