### ISSUE TITLE
Unexpected token (1:0) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by Joplinj** [wojtekmaj/react-calendar#97]
Hello,

I get the error "You may need an appropriate loader to handle this file type"

Google didn't help me, i'm really lost, He don't want to load Calendar.css

**Comment by wojtekmaj** [comment]
You do want to load calendar.css. Configure your style-loader in Webpack config to load css files as well and you should be good to go.

**Comment by KristerV** [comment]
I'll add the full error for Googlers. Haven't figured out how to fix this yet. Problem has likely to do with the fact that i'm using Next.js and/or styled-components. will look into webpack config.

```
Error in ./Calendar.css
Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type. | .react-calendar { | width: 350px; | max-width: 100%;

ModuleParseError: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```
