### ISSUE TITLE
Can't remove border via jsx

### ISSUE THREAD

**Issue by giorgosioak** [wojtekmaj/react-calendar#98]
Hello, i am using 'react-calendar: ^2.16.1' and i see at your code:

[src/Calendar.less#L5](https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less#L5): ` border: 1px solid rgb(160, 160, 150);`

border can not removed via jsx styling `ex. style={{ borderWidth: 5 }}`

i was able to workaround this by adding to my global css file:
```css
.reactCalendar {
    border: 0 !important;
}
```

 But this is not the right way to do it in react. **can you please remove it**?

Thank you for creating this. ^_^

![screenshot from 2018-08-05 22-24-44](https://user-images.githubusercontent.com/8626050/43689177-f21e4e2e-98fe-11e8-840e-fef12737a84d.png)

**Comment by wojtekmaj** [comment]
Hello,
If you don't like default styling there's a separate entry point which doesn't add them. You can copy default ones from this repository and modify it however you like.

**Comment by dondxniel** [comment]
Hi, @wojtekmaj.
Absolutely love the library, but is there a way to keep the default styling and remove just the border? I tried the above workaround by @giorgosioak but it didn't work.

**Comment by wojtekmaj** [comment]
> Hi, @wojtekmaj.
> Absolutely love the library, but is there a way to keep the default styling and remove just the border? I tried the above workaround by @giorgosioak but it didn't work. 

Copy the default styles, place them in your repo and edit them. Or keep the default styles import and write your own override.
